"""Visual Art curriculum: 5 tiers, 46 nodes.

Built from the compact template_builder DSL. Every node is parent-observed
because creative work is qualitatively assessed; benchmark_criteria are
phrased so a parent can evaluate without specialist expertise.
"""

from app.services.template_builder import register_domain

# (ref, node_type, title, description, benchmark, frequency, minutes)

ART_DATA = {
    "subject": "Visual Art",
    "color": "#E91E63",
    "assessment_type": "observed",
    "unit": "boolean",
    "tiers": [
        # ── Tier 1: Foundations ─────────────────────────────────────────
        {
            "id": "visual_art_foundations",
            "name": "Visual Art: Foundations",
            "desc": "First marks and first looks. Build the vocabulary of mark-making, shape, color, and seeing.",
            "nodes": [
                (
                    "va1-line",
                    "skill",
                    "Line Types",
                    "Draw a sheet of varied lines: straight, curved, zigzag, wavy, thick, thin, broken, continuous.",
                    "Child fills a page with at least 6 distinct line types named correctly.",
                    4,
                    15,
                ),
                (
                    "va1-shape",
                    "skill",
                    "Shape Recognition",
                    "Identify and draw circle, square, triangle, rectangle, oval, and diamond from observation and memory.",
                    "Child names and draws all 6 basic shapes without reference.",
                    4,
                    15,
                ),
                (
                    "va1-color",
                    "skill",
                    "Primary and Secondary Colors",
                    "Mix all three secondary colors (orange, green, purple) by combining primaries (red, yellow, blue).",
                    "Child mixes all 3 secondary colors from primaries without assistance and names each.",
                    3,
                    20,
                ),
                (
                    "va1-texture",
                    "skill",
                    "Texture Exploration",
                    "Make rubbings and a small collage that shows rough, smooth, bumpy, soft, and hard textures.",
                    "Child collects and labels at least 5 distinct textures in a single composition.",
                    2,
                    20,
                ),
                (
                    "va1-form",
                    "concept",
                    "Form: 3D vs 2D",
                    "Distinguish flat shapes from solid forms: circle vs sphere, square vs cube, triangle vs cylinder/cone.",
                    "Child correctly sorts 6 objects/drawings into '2D shape' or '3D form' and explains the difference.",
                    2,
                    15,
                ),
                (
                    "va1-space",
                    "concept",
                    "Positive and Negative Space",
                    "Identify the subject (positive) and the space around it (negative) in a drawing or photograph.",
                    "Child outlines positive space in one color and negative space in another on three sample images.",
                    2,
                    15,
                ),
                (
                    "va1-value",
                    "skill",
                    "Value Scale",
                    "Create a 5-step value scale from lightest to darkest using pencil pressure or paint dilution.",
                    "Child produces a 5-step value scale where each step is visibly distinct from its neighbors.",
                    3,
                    20,
                ),
                (
                    "va1-pencil",
                    "skill",
                    "Pencil Control",
                    "Practice grip, pressure variation, and steady straight and curved lines.",
                    "Child draws straight lines within 1/4 inch of a target and smooth curves without breaks for a full page.",
                    4,
                    20,
                ),
                (
                    "va1-watercolor",
                    "technique",
                    "Watercolor Wash",
                    "Wet the paper, lay a single-color wash, and grade it from saturated to pale.",
                    "Child produces a flat wash and a graded wash with no harsh lines or backruns.",
                    2,
                    25,
                ),
                (
                    "va1-observe",
                    "milestone",
                    "Observational Drawing",
                    "Draw a simple object from life — fruit, mug, shoe — using line, shape, and value learned in this tier.",
                    "Drawing is recognizable as the chosen object and uses at least 3 of the tier's elements (line variety, value, proportion, texture).",
                    2,
                    30,
                ),
            ],
            "edges": [
                ("va1-line", "va1-pencil"),
                ("va1-shape", "va1-form"),
                ("va1-shape", "va1-space"),
                ("va1-color", "va1-watercolor"),
                ("va1-line", "va1-observe"),
                ("va1-shape", "va1-observe"),
                ("va1-color", "va1-observe"),
                ("va1-texture", "va1-observe"),
                ("va1-form", "va1-observe"),
                ("va1-space", "va1-observe"),
                ("va1-value", "va1-observe"),
                ("va1-pencil", "va1-observe"),
                ("va1-watercolor", "va1-observe"),
            ],
        },
        # ── Tier 2: Development ─────────────────────────────────────────
        {
            "id": "visual_art_development",
            "name": "Visual Art: Development",
            "desc": "Add craft, vocabulary, and history. Bring drawings closer to what the eye actually sees.",
            "nodes": [
                (
                    "va2-prop",
                    "concept",
                    "Proportion Basics",
                    "Draw two or three objects in correct size relationship to each other from life.",
                    "Relative sizes of objects in the drawing match the actual scene within a reasonable margin.",
                    3,
                    25,
                ),
                (
                    "va2-1pt",
                    "technique",
                    "One-Point Perspective",
                    "Draw a hallway or room interior with a single vanishing point and converging orthogonal lines.",
                    "Child produces a one-point perspective drawing with a clear vanishing point and at least 4 correctly converging lines.",
                    2,
                    35,
                ),
                (
                    "va2-hatch",
                    "technique",
                    "Hatching and Cross-Hatching",
                    "Build value by stacking parallel lines and crossing them at angles.",
                    "Child produces a 5-value hatched scale and applies hatching to model a sphere or cylinder.",
                    3,
                    25,
                ),
                (
                    "va2-contour",
                    "skill",
                    "Contour Drawing",
                    "Draw an object's outline in a single continuous line without lifting the pencil and without looking at the paper for at least one round.",
                    "Child produces a blind contour and a slow contour drawing of the same object and reflects on differences.",
                    3,
                    20,
                ),
                (
                    "va2-gesture",
                    "skill",
                    "Gesture Drawing",
                    "Capture the essence of a figure or object in 60-second poses, prioritizing movement over detail.",
                    "Child produces a page of at least 6 gesture drawings that read as the action of the pose.",
                    3,
                    20,
                ),
                (
                    "va2-wheel",
                    "concept",
                    "Color Wheel Mastery",
                    "Build a 12-color wheel and create tints (color + white), shades (color + black), and tones (color + grey). Identify warm vs cool.",
                    "Child produces a labeled color wheel with one tint, shade, and tone for at least 6 hues, and groups colors warm vs cool.",
                    2,
                    35,
                ),
                (
                    "va2-brush",
                    "technique",
                    "Brushwork Control",
                    "Practice thin lines, thick lines, washes, and dry brush with the same brush.",
                    "Child shows all 4 brushwork techniques on a single sheet, each clearly distinct.",
                    3,
                    25,
                ),
                (
                    "va2-clay",
                    "technique",
                    "Clay Slab Construction",
                    "Roll a clay slab, cut shapes, and join them with slip and score to make a small dish or box.",
                    "Joins hold after drying and the form is structurally sound; no visible cracks at seams.",
                    1,
                    45,
                ),
                (
                    "va2-print",
                    "technique",
                    "Monoprint",
                    "Roll ink on a plate, draw into it, press paper to make a print, then pull a ghost print.",
                    "Child produces both a primary print and a recognizable ghost print from the same plate.",
                    1,
                    40,
                ),
                (
                    "va2-history",
                    "knowledge",
                    "Five Masters",
                    "Study one major work each by da Vinci, Michelangelo, Rembrandt, Monet, and van Gogh.",
                    "Child names each artist, identifies one major work, and describes one technique or quality of each in a sentence.",
                    1,
                    30,
                ),
                (
                    "va2-vocab",
                    "knowledge",
                    "Art Vocabulary",
                    "Learn and apply: composition, balance, contrast, emphasis, rhythm, unity.",
                    "Child uses at least 5 of the 6 terms correctly when describing artwork (their own or others').",
                    2,
                    20,
                ),
                (
                    "va2-portfolio",
                    "milestone",
                    "Portfolio: 5 Works",
                    "Photograph and present 5 best works from this tier with a sentence on each.",
                    "Portfolio shows variety of media and technique; each work has a one-sentence statement using tier vocabulary.",
                    1,
                    45,
                ),
            ],
            "edges": [
                ("va2-prop", "va2-1pt"),
                ("va2-hatch", "va2-portfolio"),
                ("va2-contour", "va2-gesture"),
                ("va2-wheel", "va2-brush"),
                ("va2-brush", "va2-portfolio"),
                ("va2-clay", "va2-portfolio"),
                ("va2-print", "va2-portfolio"),
                ("va2-1pt", "va2-portfolio"),
                ("va2-gesture", "va2-portfolio"),
                ("va2-history", "va2-portfolio"),
                ("va2-vocab", "va2-portfolio"),
                ("va2-prop", "va2-portfolio"),
                ("va2-contour", "va2-portfolio"),
                ("va2-wheel", "va2-portfolio"),
            ],
        },
        # ── Tier 3: Intermediate ────────────────────────────────────────
        {
            "id": "visual_art_intermediate",
            "name": "Visual Art: Intermediate",
            "desc": "Specialize. Develop technical depth in a chosen medium and a working understanding of art history.",
            "nodes": [
                (
                    "va3-2pt",
                    "technique",
                    "Two-Point Perspective",
                    "Draw a building or street corner using two vanishing points on a horizon line.",
                    "Child produces a two-point perspective drawing with a clearly readable architectural form.",
                    2,
                    40,
                ),
                (
                    "va3-figure",
                    "technique",
                    "Figure Drawing: 8-Head Canon",
                    "Draw the human figure using the 8-head proportional canon, front and 3/4 view.",
                    "Child draws a standing figure with proportions within ±1/2 head of the canon, front and 3/4.",
                    2,
                    45,
                ),
                (
                    "va3-portrait",
                    "technique",
                    "Portrait Proportions",
                    "Place the eye line at the halfway point and lay out features at canonical spacing.",
                    "Child draws a portrait where eyes, nose, and mouth are positioned within standard tolerances.",
                    2,
                    40,
                ),
                (
                    "va3-paint",
                    "technique",
                    "Painting Techniques",
                    "Practice glazing, impasto, palette knife, and underpainting in short studies.",
                    "Child shows all 4 techniques in dedicated studies and can describe when each is appropriate.",
                    2,
                    50,
                ),
                (
                    "va3-digital",
                    "technique",
                    "Digital Art",
                    "Use a tablet to draw with layers, basic selection tools, and simple photo editing.",
                    "Child completes a layered digital drawing demonstrating selection, layer order, and one photo edit.",
                    2,
                    45,
                ),
                (
                    "va3-history",
                    "knowledge",
                    "Art History Movements",
                    "Identify Impressionism, Post-Impressionism, Expressionism, Cubism, Surrealism, and Pop Art with two artists each.",
                    "Child names 2 artists per movement (12 total) and identifies one example work for each movement.",
                    1,
                    40,
                ),
                (
                    "va3-portfolio",
                    "project",
                    "Portfolio: 10 Works with Statement",
                    "Curate 10 works, photograph with consistent lighting, and write a 100-word artist statement.",
                    "Portfolio shows breadth and growth; statement names personal interests and tier vocabulary in 100 words.",
                    1,
                    60,
                ),
                (
                    "va3-spec-a",
                    "project",
                    "Media Specialization A",
                    "Parent-selected primary medium (e.g., drawing, painting, printmaking, ceramics, photography, digital, sculpture). Complete a focused 3-piece study.",
                    "Three works in the chosen medium show clear technical development from first to third piece.",
                    2,
                    60,
                ),
                (
                    "va3-spec-b",
                    "project",
                    "Media Specialization B",
                    "Parent-selected secondary medium. Complete a focused 3-piece study.",
                    "Three works in the chosen medium show clear technical development from first to third piece.",
                    2,
                    60,
                ),
                (
                    "va3-milestone",
                    "milestone",
                    "Intermediate Capstone",
                    "Present the portfolio, the two media specializations, and a short reflection on artistic growth this tier.",
                    "Child presents all artifacts and articulates one specific way their work has changed since Tier 2.",
                    1,
                    60,
                ),
            ],
            "edges": [
                ("va3-2pt", "va3-portfolio"),
                ("va3-figure", "va3-portrait"),
                ("va3-portrait", "va3-portfolio"),
                ("va3-paint", "va3-spec-a"),
                ("va3-paint", "va3-spec-b"),
                ("va3-digital", "va3-spec-a"),
                ("va3-digital", "va3-spec-b"),
                ("va3-history", "va3-milestone"),
                ("va3-portfolio", "va3-milestone"),
                ("va3-spec-a", "va3-milestone"),
                ("va3-spec-b", "va3-milestone"),
                ("va3-2pt", "va3-milestone"),
                ("va3-figure", "va3-milestone"),
                ("va3-portrait", "va3-milestone"),
                ("va3-paint", "va3-milestone"),
                ("va3-digital", "va3-milestone"),
            ],
        },
        # ── Tier 4: Advanced ────────────────────────────────────────────
        {
            "id": "visual_art_advanced",
            "name": "Visual Art: Advanced",
            "desc": "Move from technique to intent. Make work with a point of view, supported by analysis and presentation.",
            "nodes": [
                (
                    "va4-comp",
                    "concept",
                    "Composition Theory",
                    "Apply rule of thirds, golden ratio, visual weight, leading lines, and color psychology to original work.",
                    "Child analyzes their own piece using at least 3 composition concepts and explains a choice they made.",
                    2,
                    45,
                ),
                (
                    "va4-tech",
                    "technique",
                    "Advanced Technique in Specialization",
                    "Push the chosen medium with three studies that target specific advanced techniques (e.g., glazing in oils, dry-point intaglio, digital compositing).",
                    "Three studies show clear advanced techniques the child can name and demonstrate.",
                    2,
                    60,
                ),
                (
                    "va4-analysis",
                    "knowledge",
                    "Formal Art Analysis",
                    "Write a 300+ word formal analysis of a chosen artwork using elements and principles vocabulary.",
                    "Analysis covers description, formal analysis, interpretation, and judgment, ≥300 words.",
                    1,
                    60,
                ),
                (
                    "va4-contemp",
                    "knowledge",
                    "Contemporary Art History",
                    "Survey installation, performance, street art, digital art, and the contemporary art market.",
                    "Child names one artist and one work from each category and describes how the medium shapes meaning.",
                    1,
                    45,
                ),
                (
                    "va4-proj-1",
                    "project",
                    "Independent Project I",
                    "Self-directed piece: written concept, process documentation, artist statement.",
                    "Concept, process notes, finished work, and statement together show intentional decision-making.",
                    1,
                    90,
                ),
                (
                    "va4-proj-2",
                    "project",
                    "Independent Project II",
                    "Second self-directed piece building on lessons from the first.",
                    "Second piece shows at least one specific change from the first project's reflection.",
                    1,
                    90,
                ),
                (
                    "va4-proj-3",
                    "project",
                    "Independent Project III",
                    "Third self-directed piece — the strongest of the three.",
                    "Child can articulate why this is their strongest piece using formal vocabulary.",
                    1,
                    90,
                ),
                (
                    "va4-exhibit",
                    "milestone",
                    "Exhibition Portfolio",
                    "Curate 15 pieces with professional photo documentation and a cohesive presentation.",
                    "Portfolio reads as a coherent body of work; documentation is consistent in lighting and crop.",
                    1,
                    120,
                ),
            ],
            "edges": [
                ("va4-comp", "va4-proj-1"),
                ("va4-tech", "va4-proj-1"),
                ("va4-analysis", "va4-proj-2"),
                ("va4-contemp", "va4-proj-2"),
                ("va4-proj-1", "va4-proj-2"),
                ("va4-proj-2", "va4-proj-3"),
                ("va4-comp", "va4-exhibit"),
                ("va4-tech", "va4-exhibit"),
                ("va4-analysis", "va4-exhibit"),
                ("va4-contemp", "va4-exhibit"),
                ("va4-proj-1", "va4-exhibit"),
                ("va4-proj-2", "va4-exhibit"),
                ("va4-proj-3", "va4-exhibit"),
            ],
        },
        # ── Tier 5: Independent ─────────────────────────────────────────
        {
            "id": "visual_art_independent",
            "name": "Visual Art: Independent",
            "desc": "Operate as an artist. Develop personal voice, teach, communicate ideas, and plan for a creative life.",
            "nodes": [
                (
                    "va5-voice",
                    "project",
                    "Personal Voice",
                    "Produce a body of 5+ works with thematic or formal consistency that a viewer could identify as 'yours'.",
                    "Independent reviewer (parent, mentor) can identify a unifying thread across the 5 works.",
                    2,
                    120,
                ),
                (
                    "va5-teach",
                    "project",
                    "Teaching",
                    "Plan and deliver a 30-minute art lesson to a Tier 1-2 learner. Include a written lesson plan and reflection.",
                    "Lesson is delivered, learner produces a piece, and the teacher reflects on what worked and what didn't.",
                    1,
                    90,
                ),
                (
                    "va5-argument",
                    "project",
                    "Art as Communication",
                    "Create one visual work that communicates a complex idea without words. Write a 500-word reflection on choices.",
                    "Reflection explicitly ties formal choices (color, composition, medium) to the idea being communicated, ≥500 words.",
                    1,
                    120,
                ),
                (
                    "va5-cross",
                    "project",
                    "Cross-Domain Connections",
                    "Choose one: scientific illustration (art + science), historical scene reconstruction (art + history), or illustrated narrative (art + writing). Complete a finished piece with research notes.",
                    "Final piece is grounded in real research and demonstrates knowledge of the partner discipline.",
                    1,
                    120,
                ),
                (
                    "va5-pro",
                    "knowledge",
                    "Professional Practice",
                    "Research one gallery, commission, or exhibition opportunity. Prepare a complete submission package (artist statement, CV, work samples, cover letter).",
                    "Package includes all four components, formatted to the venue's stated guidelines.",
                    1,
                    90,
                ),
                (
                    "va5-plan",
                    "milestone",
                    "Lifetime Creative Plan",
                    "Write a personal philosophy of art-making, three concrete one-year goals, key influences, and chosen areas for growth.",
                    "Document covers all four parts and is reviewed with a mentor or parent who can affirm its specificity.",
                    1,
                    90,
                ),
            ],
            "edges": [
                ("va5-voice", "va5-teach"),
                ("va5-voice", "va5-argument"),
                ("va5-argument", "va5-cross"),
                ("va5-cross", "va5-pro"),
                ("va5-voice", "va5-plan"),
                ("va5-teach", "va5-plan"),
                ("va5-argument", "va5-plan"),
                ("va5-cross", "va5-plan"),
                ("va5-pro", "va5-plan"),
            ],
        },
    ],
}


register_domain(ART_DATA)
