"""Document generation service.

Generates PDF documents for compliance filing: IHIPs, quarterly reports,
attendance records, annual assessments, and transcripts.

Uses reportlab for PDF generation (lightweight, pure Python).
"""

import io
import uuid
from datetime import date

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.annual_curriculum import AnnualCurriculum
from app.models.curriculum import LearningMap, Subject
from app.models.evidence import WeeklySnapshot
from app.models.governance import Activity, Attempt, Plan, PlanWeek
from app.models.identity import Child, Household
from app.models.state import ChildNodeState
from app.services.compliance_engine import STATE_REQUIREMENTS, get_hours_breakdown


def _make_pdf(title: str, sections: list[tuple[str, str]], child_name: str,
              household_name: str, state_header: str | None = None) -> bytes:
    """Build a simple PDF from title + sections using reportlab."""
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.units import inch
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

        buf = io.BytesIO()
        doc = SimpleDocTemplate(buf, pagesize=letter,
                                leftMargin=inch, rightMargin=inch,
                                topMargin=inch, bottomMargin=inch)

        styles = getSampleStyleSheet()
        title_style = ParagraphStyle('DocTitle', parent=styles['Heading1'], fontSize=16, spaceAfter=6)
        subtitle_style = ParagraphStyle('Subtitle', parent=styles['Normal'], fontSize=10, textColor='#666666')
        heading_style = ParagraphStyle('SectionH', parent=styles['Heading2'], fontSize=12, spaceBefore=12)
        body_style = ParagraphStyle('Body', parent=styles['Normal'], fontSize=10, leading=14)
        disclaimer_style = ParagraphStyle('Disclaimer', parent=styles['Normal'], fontSize=7, textColor='#999999')

        story = []

        # Header
        story.append(Paragraph("METHEAN", styles['Heading3']))
        if state_header:
            story.append(Paragraph(state_header, subtitle_style))
        story.append(Spacer(1, 12))
        story.append(Paragraph(title, title_style))
        story.append(Paragraph(f"Student: {child_name}", subtitle_style))
        story.append(Paragraph(f"Household: {household_name}", subtitle_style))
        story.append(Paragraph(f"Generated: {date.today().isoformat()}", subtitle_style))
        story.append(Spacer(1, 24))

        # Sections
        for heading, content in sections:
            story.append(Paragraph(heading, heading_style))
            for line in content.split("\n"):
                if line.strip():
                    story.append(Paragraph(line.strip(), body_style))
            story.append(Spacer(1, 8))

        # Disclaimer
        story.append(Spacer(1, 24))
        story.append(Paragraph(
            "Generated by METHEAN. This document is provided for informational purposes only. "
            "Verify current requirements with your state Department of Education.",
            disclaimer_style
        ))

        doc.build(story)
        return buf.getvalue()

    except ImportError:
        # Fallback: return a plain text document if reportlab not available
        lines = [f"METHEAN — {title}", "=" * 60, ""]
        if state_header:
            lines.append(state_header)
        lines.extend([
            f"Student: {child_name}", f"Household: {household_name}",
            f"Generated: {date.today().isoformat()}", "",
        ])
        for heading, content in sections:
            lines.extend([f"\n{heading}", "-" * 40, content, ""])
        lines.append("\nGenerated by METHEAN. Verify requirements with your state DOE.")
        return "\n".join(lines).encode("utf-8")


async def _get_child_and_household(db: AsyncSession, child_id: uuid.UUID, household_id: uuid.UUID):
    child_r = await db.execute(select(Child).where(Child.id == child_id))
    child = child_r.scalar_one()
    hh_r = await db.execute(select(Household).where(Household.id == household_id))
    hh = hh_r.scalar_one()
    return child, hh


async def generate_ihip(
    db: AsyncSession,
    household_id: uuid.UUID,
    child_id: uuid.UUID,
    state_code: str,
    academic_year: str,
) -> bytes:
    """Generate an Individualized Home Instruction Plan (NY-style)."""
    child, hh = await _get_child_and_household(db, child_id, household_id)
    reqs = STATE_REQUIREMENTS.get(state_code.upper(), {})
    child_name = f"{child.first_name} {child.last_name or ''}"

    # Fetch curricula for this year
    curr_r = await db.execute(
        select(AnnualCurriculum).where(
            AnnualCurriculum.child_id == child_id,
            AnnualCurriculum.academic_year == academic_year,
        )
    )
    curricula = curr_r.scalars().all()

    sections = []

    # Student info
    sections.append(("I. Student Information", (
        f"Name: {child_name}\n"
        f"Grade Level: {child.grade_level or 'N/A'}\n"
        f"Date of Birth: {child.date_of_birth or 'N/A'}\n"
        f"Academic Year: {academic_year}"
    )))

    # Required subjects
    all_subjects = set()
    for grade_range, subj_list in reqs.get("required_subjects", {}).items():
        all_subjects.update(subj_list)
    curriculum_subjects = [c.subject_name for c in curricula]
    sections.append(("II. Required Subjects", (
        f"State required: {', '.join(sorted(all_subjects)) or 'See state requirements'}\n"
        f"Planned subjects: {', '.join(curriculum_subjects) or 'See attached curriculum'}"
    )))

    # Instruction hours
    hours_info = reqs.get("instruction_hours", {})
    hours_lines = []
    for grade_range, hrs in hours_info.items():
        annual = hrs.get("annual", "N/A")
        hours_lines.append(f"Grades {grade_range}: {annual} hours/year")
    sections.append(("III. Planned Instruction Hours",
        "\n".join(hours_lines) if hours_lines else "See state requirements"))

    # Curriculum overview
    for c in curricula:
        overview = c.scope_sequence.get("overview", "See detailed curriculum plan.")
        sections.append((f"IV. {c.subject_name} Curriculum", overview))

    # Assessment plan
    assess = reqs.get("annual_assessment", {})
    if assess.get("required"):
        options = assess.get("options", [])
        sections.append(("V. Assessment Plan",
            f"Assessment options: {'; '.join(options)}" if options else "Annual assessment required per state law."))

    return _make_pdf(
        f"Individualized Home Instruction Plan — {academic_year}",
        sections, child_name, hh.name or "Household",
        state_header=f"State of {reqs.get('name', state_code)}",
    )


async def generate_quarterly_report(
    db: AsyncSession,
    household_id: uuid.UUID,
    child_id: uuid.UUID,
    quarter: int,
    academic_year: str,
) -> bytes:
    """Generate a quarterly progress report."""
    child, hh = await _get_child_and_household(db, child_id, household_id)
    child_name = f"{child.first_name} {child.last_name or ''}"

    hours = await get_hours_breakdown(db, household_id, child_id)

    sections = [
        ("Student Information", f"Name: {child_name}\nGrade: {child.grade_level or 'N/A'}\nQuarter: {quarter}\nYear: {academic_year}"),
        ("Hours Summary", f"Total hours logged: {hours['total_hours']}\nBy subject:\n" +
         "\n".join(f"  {subj}: {hrs}h" for subj, hrs in hours["by_subject"].items())),
    ]

    return _make_pdf(
        f"Quarterly Progress Report — Q{quarter} {academic_year}",
        sections, child_name, hh.name or "Household",
    )


async def generate_attendance_record(
    db: AsyncSession,
    household_id: uuid.UUID,
    child_id: uuid.UUID,
    start_date: date,
    end_date: date,
) -> bytes:
    """Generate a formal attendance record."""
    child, hh = await _get_child_and_household(db, child_id, household_id)
    child_name = f"{child.first_name} {child.last_name or ''}"

    from app.services.attendance import get_attendance_record
    record = await get_attendance_record(db, household_id, child_id, start_date, end_date)

    sections = [
        ("Period", f"{start_date} to {end_date}"),
        ("Attendance Summary", f"Total school days: {record['total_school_days']}\nTotal instruction minutes: {record.get('total_minutes', 'N/A')}"),
    ]

    monthly = record.get("monthly_summary", {})
    if monthly:
        lines = [f"  {month}: {data.get('school_days', 0)} days" for month, data in monthly.items()]
        sections.append(("Monthly Breakdown", "\n".join(lines)))

    return _make_pdf(
        f"Attendance Record — {start_date} to {end_date}",
        sections, child_name, hh.name or "Household",
    )


async def generate_transcript(
    db: AsyncSession,
    household_id: uuid.UUID,
    child_id: uuid.UUID,
) -> bytes:
    """Generate a cumulative academic transcript."""
    child, hh = await _get_child_and_household(db, child_id, household_id)
    child_name = f"{child.first_name} {child.last_name or ''}"

    curr_r = await db.execute(
        select(AnnualCurriculum).where(
            AnnualCurriculum.child_id == child_id,
            AnnualCurriculum.household_id == household_id,
        ).order_by(AnnualCurriculum.academic_year)
    )
    curricula = curr_r.scalars().all()

    sections = [
        ("Student Information", f"Name: {child_name}\nGrade: {child.grade_level or 'N/A'}\nDate of Birth: {child.date_of_birth or 'N/A'}"),
    ]

    for c in curricula:
        actual = c.actual_record or {}
        completed_weeks = len(actual.get("weeks", {}))
        sections.append((
            f"{c.academic_year} — {c.subject_name}",
            f"Grade Level: {c.grade_level or 'N/A'}\n"
            f"Status: {c.status}\n"
            f"Weeks completed: {completed_weeks}/{c.total_weeks}\n"
            f"Hours/week: {c.hours_per_week or 'N/A'}"
        ))

    hours = await get_hours_breakdown(db, household_id, child_id)
    sections.append(("Cumulative Hours", f"Total: {hours['total_hours']}h\n" +
        "\n".join(f"  {subj}: {hrs}h" for subj, hrs in hours["by_subject"].items())))

    return _make_pdf("Academic Transcript", sections, child_name, hh.name or "Household")
