"""Physical fitness curriculum templates.

Five progression tiers from foundational movement (early childhood) through
independent programming (young adult). Each tier assumes mastery of the
previous tier. Nodes carry a structured `content` payload so the evaluator
can score benchmarks, record attempts, and schedule practice sessions.

Content schema for every fitness node:
    description           Plain-language explanation of the skill.
    benchmark_criteria    What mastery looks like (measurable).
    assessment_type       timed | counted | pass_fail | observed
    measurement_unit      seconds | minutes | repetitions |
                          distance_yards | distance_miles |
                          inches | pounds | boolean
    suggested_frequency   Practices per week (int).
"""

from app.services.templates import Template, TemplateEdge, TemplateNode


def _node(
    ref: str,
    title: str,
    *,
    node_type: str,
    description: str,
    benchmark: str,
    assessment_type: str,
    unit: str,
    frequency: int,
    minutes: int,
    sort_order: int,
) -> TemplateNode:
    """Build a fitness TemplateNode with content payload."""
    return TemplateNode(
        ref=ref,
        node_type=node_type,
        title=title,
        description=description,
        estimated_minutes=minutes,
        sort_order=sort_order,
        content={
            "description": description,
            "benchmark_criteria": benchmark,
            "assessment_type": assessment_type,
            "measurement_unit": unit,
            "suggested_frequency": frequency,
        },
    )


# ── Tier 1: Foundations ──

FITNESS_FOUNDATIONS = Template(
    template_id="physical_fitness_foundations",
    name="Physical Fitness: Foundations",
    description=(
        "Fundamental movement patterns for early learners: balance, locomotion, "
        "basic object control, and body awareness. No equipment required."
    ),
    subject_name="Physical Fitness",
    subject_color="#2E7D32",
    nodes=[
        _node(
            "pf1-walk",
            "Steady Walking",
            node_type="skill",
            description="Walk a straight line with controlled posture, heel-to-toe contact, and arm swing.",
            benchmark="Walk 25 yards in a straight line without stepping off a 6-inch-wide path.",
            assessment_type="pass_fail",
            unit="boolean",
            frequency=5,
            minutes=10,
            sort_order=0,
        ),
        _node(
            "pf1-balance",
            "Single-Leg Balance",
            node_type="skill",
            description="Stand on one foot with hands on hips, opposite knee raised.",
            benchmark="Hold a single-leg stance on either leg for 10 seconds without touching down.",
            assessment_type="timed",
            unit="seconds",
            frequency=4,
            minutes=10,
            sort_order=1,
        ),
        _node(
            "pf1-run",
            "Basic Running Form",
            node_type="skill",
            description="Jog with alternating arms and knees, soft foot strike, and eyes forward.",
            benchmark="Jog 50 yards continuously with relaxed form.",
            assessment_type="observed",
            unit="boolean",
            frequency=5,
            minutes=15,
            sort_order=2,
        ),
        _node(
            "pf1-jump",
            "Two-Foot Jump",
            node_type="skill",
            description="Jump forward from two feet and land on two feet with bent knees.",
            benchmark="Land balanced 8 out of 10 two-foot jumps covering at least 12 inches.",
            assessment_type="counted",
            unit="repetitions",
            frequency=4,
            minutes=10,
            sort_order=3,
        ),
        _node(
            "pf1-hop",
            "Single-Leg Hop",
            node_type="skill",
            description="Hop forward on one foot, maintaining balance on landing.",
            benchmark="Complete 5 consecutive hops on each leg without touching the opposite foot down.",
            assessment_type="counted",
            unit="repetitions",
            frequency=4,
            minutes=10,
            sort_order=4,
        ),
        _node(
            "pf1-underhand",
            "Underhand Toss",
            node_type="skill",
            description="Toss a light ball underhand to a target with eyes on the target.",
            benchmark="Hit a 2-foot target from 10 feet away on 6 of 10 attempts.",
            assessment_type="counted",
            unit="repetitions",
            frequency=3,
            minutes=15,
            sort_order=5,
        ),
        _node(
            "pf1-catch",
            "Two-Hand Catch",
            node_type="skill",
            description="Catch a softly tossed ball with both hands using a ready position.",
            benchmark="Catch 7 of 10 tosses from 8 feet away.",
            assessment_type="counted",
            unit="repetitions",
            frequency=3,
            minutes=15,
            sort_order=6,
        ),
        _node(
            "pf1-flex",
            "Sit and Reach",
            node_type="skill",
            description="Seated forward fold reaching toward the toes with straight legs.",
            benchmark="Reach fingertips to the toes while keeping knees flat.",
            assessment_type="pass_fail",
            unit="inches",
            frequency=4,
            minutes=5,
            sort_order=7,
        ),
        _node(
            "pf1-climb",
            "Climbing and Crawling",
            node_type="skill",
            description="Ascend a playground ladder and army-crawl through a tunnel using opposite-limb patterns.",
            benchmark="Safely complete a climb-and-crawl obstacle course on 3 consecutive attempts.",
            assessment_type="observed",
            unit="boolean",
            frequency=3,
            minutes=15,
            sort_order=8,
        ),
        _node(
            "pf1-milestone",
            "Foundations Assessment",
            node_type="milestone",
            description="Demonstrate all Tier 1 benchmarks in a single session.",
            benchmark="Pass every Tier 1 node assessment on the same day.",
            assessment_type="pass_fail",
            unit="boolean",
            frequency=1,
            minutes=30,
            sort_order=9,
        ),
    ],
    edges=[
        TemplateEdge("pf1-walk", "pf1-balance"),
        TemplateEdge("pf1-walk", "pf1-run"),
        TemplateEdge("pf1-balance", "pf1-hop"),
        TemplateEdge("pf1-run", "pf1-jump"),
        TemplateEdge("pf1-jump", "pf1-hop"),
        TemplateEdge("pf1-underhand", "pf1-catch"),
        TemplateEdge("pf1-run", "pf1-climb"),
        TemplateEdge("pf1-balance", "pf1-flex"),
        TemplateEdge("pf1-balance", "pf1-milestone"),
        TemplateEdge("pf1-run", "pf1-milestone"),
        TemplateEdge("pf1-jump", "pf1-milestone"),
        TemplateEdge("pf1-hop", "pf1-milestone"),
        TemplateEdge("pf1-catch", "pf1-milestone"),
        TemplateEdge("pf1-flex", "pf1-milestone"),
        TemplateEdge("pf1-climb", "pf1-milestone"),
    ],
)


# ── Tier 2: Development ──

FITNESS_DEVELOPMENT = Template(
    template_id="physical_fitness_development",
    name="Physical Fitness: Development",
    description=(
        "Builds on foundational movement with endurance, basic strength, "
        "coordination, and introductory object-control sports skills."
    ),
    subject_name="Physical Fitness",
    subject_color="#388E3C",
    nodes=[
        _node(
            "pf2-jog",
            "Continuous Jogging",
            node_type="skill",
            description="Maintain a conversational jog at a steady pace.",
            benchmark="Jog continuously for 10 minutes without walking breaks.",
            assessment_type="timed",
            unit="minutes",
            frequency=3,
            minutes=20,
            sort_order=0,
        ),
        _node(
            "pf2-sprint",
            "40-Yard Sprint Form",
            node_type="technique",
            description="Drive with the arms, land on the balls of the feet, and maintain a forward lean.",
            benchmark="Cover 40 yards with technically correct sprint mechanics at max effort.",
            assessment_type="timed",
            unit="seconds",
            frequency=2,
            minutes=20,
            sort_order=1,
        ),
        _node(
            "pf2-jump-rope",
            "Jump Rope Basics",
            node_type="skill",
            description="Two-foot jumping with a rope at a steady cadence.",
            benchmark="Perform 50 consecutive jumps without a miss.",
            assessment_type="counted",
            unit="repetitions",
            frequency=4,
            minutes=15,
            sort_order=2,
        ),
        _node(
            "pf2-squat",
            "Bodyweight Squat",
            node_type="technique",
            description="Squat to parallel with chest up, knees tracking over toes, heels planted.",
            benchmark="Perform 20 strict bodyweight squats with full depth and control.",
            assessment_type="counted",
            unit="repetitions",
            frequency=3,
            minutes=15,
            sort_order=3,
        ),
        _node(
            "pf2-pushup-incline",
            "Incline Push-Up",
            node_type="technique",
            description="Push-up with hands elevated on a bench or wall to reduce load.",
            benchmark="Perform 15 incline push-ups with chest touching the bench each rep.",
            assessment_type="counted",
            unit="repetitions",
            frequency=3,
            minutes=15,
            sort_order=4,
        ),
        _node(
            "pf2-plank",
            "Front Plank",
            node_type="technique",
            description="Hold a straight-body plank on forearms and toes without hip sag.",
            benchmark="Hold a proper plank for 45 seconds.",
            assessment_type="timed",
            unit="seconds",
            frequency=4,
            minutes=10,
            sort_order=5,
        ),
        _node(
            "pf2-overhand",
            "Overhand Throw",
            node_type="technique",
            description="Throw with step, hip rotation, and follow-through across the body.",
            benchmark="Throw a baseball-sized ball 30 yards on a consistent arc.",
            assessment_type="observed",
            unit="distance_yards",
            frequency=2,
            minutes=20,
            sort_order=6,
        ),
        _node(
            "pf2-agility",
            "Coordination Ladder",
            node_type="skill",
            description="Footwork drills through an agility ladder: in-in-out-out, lateral shuffle, high knees.",
            benchmark="Complete three ladder patterns cleanly at moderate speed.",
            assessment_type="observed",
            unit="boolean",
            frequency=3,
            minutes=15,
            sort_order=7,
        ),
        _node(
            "pf2-flex",
            "Dynamic Warm-Up Routine",
            node_type="knowledge",
            description="Lead a 5-movement dynamic warm-up including leg swings, arm circles, and inchworms.",
            benchmark="Independently lead a full dynamic warm-up without prompts.",
            assessment_type="pass_fail",
            unit="boolean",
            frequency=5,
            minutes=10,
            sort_order=8,
        ),
        _node(
            "pf2-milestone",
            "Development Assessment",
            node_type="milestone",
            description="Complete all Tier 2 benchmarks in a single session.",
            benchmark="Pass every Tier 2 node assessment on the same day.",
            assessment_type="pass_fail",
            unit="boolean",
            frequency=1,
            minutes=45,
            sort_order=9,
        ),
    ],
    edges=[
        TemplateEdge("pf2-jog", "pf2-sprint"),
        TemplateEdge("pf2-jog", "pf2-jump-rope"),
        TemplateEdge("pf2-squat", "pf2-pushup-incline"),
        TemplateEdge("pf2-plank", "pf2-pushup-incline"),
        TemplateEdge("pf2-overhand", "pf2-agility"),
        TemplateEdge("pf2-sprint", "pf2-agility"),
        TemplateEdge("pf2-flex", "pf2-sprint"),
        TemplateEdge("pf2-flex", "pf2-squat"),
        TemplateEdge("pf2-jog", "pf2-milestone"),
        TemplateEdge("pf2-sprint", "pf2-milestone"),
        TemplateEdge("pf2-jump-rope", "pf2-milestone"),
        TemplateEdge("pf2-squat", "pf2-milestone"),
        TemplateEdge("pf2-pushup-incline", "pf2-milestone"),
        TemplateEdge("pf2-plank", "pf2-milestone"),
        TemplateEdge("pf2-overhand", "pf2-milestone"),
        TemplateEdge("pf2-agility", "pf2-milestone"),
    ],
)


# ── Tier 3: Intermediate ──

FITNESS_INTERMEDIATE = Template(
    template_id="physical_fitness_intermediate",
    name="Physical Fitness: Intermediate",
    description=(
        "Formal fitness testing battery, introduction to resistance training, and sustained cardiovascular work."
    ),
    subject_name="Physical Fitness",
    subject_color="#1B5E20",
    nodes=[
        _node(
            "pf3-mile",
            "One-Mile Run",
            node_type="milestone",
            description="Steady-pace mile run as a standard cardiovascular benchmark.",
            benchmark="Complete a one-mile run in 10 minutes or better.",
            assessment_type="timed",
            unit="minutes",
            frequency=2,
            minutes=30,
            sort_order=0,
        ),
        _node(
            "pf3-pushup",
            "Full Push-Up",
            node_type="technique",
            description="Push-up on toes with full range of motion, elbows near the ribs.",
            benchmark="Perform 20 consecutive strict push-ups.",
            assessment_type="counted",
            unit="repetitions",
            frequency=3,
            minutes=20,
            sort_order=1,
        ),
        _node(
            "pf3-pullup-assist",
            "Assisted Pull-Up",
            node_type="technique",
            description="Pull-up with resistance band or spotter assistance, chin clearing the bar.",
            benchmark="Perform 5 assisted pull-ups with chin over the bar.",
            assessment_type="counted",
            unit="repetitions",
            frequency=3,
            minutes=20,
            sort_order=2,
        ),
        _node(
            "pf3-plank",
            "Extended Plank",
            node_type="technique",
            description="Forearm plank with a neutral spine and strong glute engagement.",
            benchmark="Hold a strict plank for 90 seconds.",
            assessment_type="timed",
            unit="seconds",
            frequency=3,
            minutes=10,
            sort_order=3,
        ),
        _node(
            "pf3-broad",
            "Broad Jump",
            node_type="skill",
            description="Standing long jump with two-foot takeoff and balanced landing.",
            benchmark="Jump a distance equal to or greater than body height from a standing start.",
            assessment_type="counted",
            unit="inches",
            frequency=2,
            minutes=15,
            sort_order=4,
        ),
        _node(
            "pf3-vertical",
            "Vertical Jump",
            node_type="skill",
            description="Measured vertical leap from a loaded countermovement.",
            benchmark="Reach a vertical jump of 14 inches or greater.",
            assessment_type="counted",
            unit="inches",
            frequency=2,
            minutes=15,
            sort_order=5,
        ),
        _node(
            "pf3-interval",
            "Interval Training Introduction",
            node_type="knowledge",
            description="Alternate 30 seconds hard effort with 60 seconds easy effort across multiple rounds.",
            benchmark="Complete 8 rounds of 30/60 interval work at the prescribed effort.",
            assessment_type="counted",
            unit="repetitions",
            frequency=2,
            minutes=25,
            sort_order=6,
        ),
        _node(
            "pf3-resistance",
            "Intro to Resistance Training",
            node_type="knowledge",
            description="Safe use of dumbbells and resistance bands: goblet squat, row, press.",
            benchmark="Demonstrate correct form on goblet squat, row, and press for 3 sets of 8.",
            assessment_type="observed",
            unit="boolean",
            frequency=2,
            minutes=30,
            sort_order=7,
        ),
        _node(
            "pf3-agility",
            "T-Drill Agility",
            node_type="skill",
            description="T-drill combining forward sprint, lateral shuffle, and backpedal.",
            benchmark="Complete the T-drill in 12 seconds or less.",
            assessment_type="timed",
            unit="seconds",
            frequency=2,
            minutes=20,
            sort_order=8,
        ),
        _node(
            "pf3-milestone",
            "Intermediate Testing Battery",
            node_type="milestone",
            description="Complete the full Tier 3 testing battery and log scores.",
            benchmark="Pass every Tier 3 node assessment on the same day.",
            assessment_type="pass_fail",
            unit="boolean",
            frequency=1,
            minutes=60,
            sort_order=9,
        ),
    ],
    edges=[
        TemplateEdge("pf3-mile", "pf3-interval"),
        TemplateEdge("pf3-pushup", "pf3-pullup-assist"),
        TemplateEdge("pf3-pushup", "pf3-resistance"),
        TemplateEdge("pf3-plank", "pf3-resistance"),
        TemplateEdge("pf3-broad", "pf3-vertical"),
        TemplateEdge("pf3-broad", "pf3-agility"),
        TemplateEdge("pf3-vertical", "pf3-agility"),
        TemplateEdge("pf3-interval", "pf3-milestone"),
        TemplateEdge("pf3-resistance", "pf3-milestone"),
        TemplateEdge("pf3-mile", "pf3-milestone"),
        TemplateEdge("pf3-pushup", "pf3-milestone"),
        TemplateEdge("pf3-pullup-assist", "pf3-milestone"),
        TemplateEdge("pf3-plank", "pf3-milestone"),
        TemplateEdge("pf3-broad", "pf3-milestone"),
        TemplateEdge("pf3-vertical", "pf3-milestone"),
        TemplateEdge("pf3-agility", "pf3-milestone"),
    ],
)


# ── Tier 4: Advanced ──

FITNESS_ADVANCED = Template(
    template_id="physical_fitness_advanced",
    name="Physical Fitness: Advanced",
    description=(
        "Strength training with external load, extended endurance, high-intensity "
        "interval work, and sport-performance assessment."
    ),
    subject_name="Physical Fitness",
    subject_color="#0D47A1",
    nodes=[
        _node(
            "pf4-distance",
            "Two-Mile Run",
            node_type="milestone",
            description="Two-mile steady-state run as an advanced aerobic benchmark.",
            benchmark="Complete a two-mile run in 18 minutes or better.",
            assessment_type="timed",
            unit="minutes",
            frequency=2,
            minutes=40,
            sort_order=0,
        ),
        _node(
            "pf4-pullup",
            "Unassisted Pull-Up",
            node_type="technique",
            description="Strict pull-up from a dead hang, chin clearing the bar.",
            benchmark="Perform 5 unassisted, strict pull-ups.",
            assessment_type="counted",
            unit="repetitions",
            frequency=3,
            minutes=20,
            sort_order=1,
        ),
        _node(
            "pf4-squat",
            "Back Squat — Bodyweight Load",
            node_type="technique",
            description="Barbell back squat with bar path over mid-foot and full depth.",
            benchmark="Perform 5 back squats at bodyweight load with coached form.",
            assessment_type="counted",
            unit="pounds",
            frequency=2,
            minutes=45,
            sort_order=2,
        ),
        _node(
            "pf4-deadlift",
            "Conventional Deadlift — Bodyweight Load",
            node_type="technique",
            description="Conventional deadlift from the floor with a neutral spine and locked-out hips.",
            benchmark="Perform 5 deadlifts at bodyweight load with coached form.",
            assessment_type="counted",
            unit="pounds",
            frequency=2,
            minutes=45,
            sort_order=3,
        ),
        _node(
            "pf4-bench",
            "Bench Press — Bodyweight Load",
            node_type="technique",
            description="Flat bench press with controlled descent and full lockout.",
            benchmark="Perform 3 bench press reps at bodyweight load with a spotter.",
            assessment_type="counted",
            unit="pounds",
            frequency=2,
            minutes=30,
            sort_order=4,
        ),
        _node(
            "pf4-hiit",
            "HIIT Conditioning",
            node_type="technique",
            description="High-intensity interval training: 20 seconds all-out, 10 seconds rest (Tabata), 8 rounds.",
            benchmark="Complete 4 Tabata sets across 4 different movements without compromising form.",
            assessment_type="counted",
            unit="repetitions",
            frequency=2,
            minutes=30,
            sort_order=5,
        ),
        _node(
            "pf4-sport",
            "Sport-Specific Performance",
            node_type="project",
            description="Apply fitness to a chosen sport: shuttle runs, sport-specific agility, sport skill drills.",
            benchmark="Complete a sport-specific testing protocol designed by the athlete and approved by coach.",
            assessment_type="observed",
            unit="boolean",
            frequency=3,
            minutes=45,
            sort_order=6,
        ),
        _node(
            "pf4-recovery",
            "Recovery and Mobility",
            node_type="knowledge",
            description="Foam rolling, active stretching, and sleep/nutrition basics for recovery.",
            benchmark="Maintain a 2-week recovery log with mobility work and sleep tracking.",
            assessment_type="pass_fail",
            unit="boolean",
            frequency=5,
            minutes=20,
            sort_order=7,
        ),
        _node(
            "pf4-battery",
            "Advanced Testing Battery",
            node_type="milestone",
            description="Complete the full Tier 4 testing battery and record all scores.",
            benchmark="Pass every Tier 4 node assessment on the same day.",
            assessment_type="pass_fail",
            unit="boolean",
            frequency=1,
            minutes=90,
            sort_order=8,
        ),
    ],
    edges=[
        TemplateEdge("pf4-distance", "pf4-hiit"),
        TemplateEdge("pf4-pullup", "pf4-sport"),
        TemplateEdge("pf4-squat", "pf4-deadlift"),
        TemplateEdge("pf4-squat", "pf4-bench"),
        TemplateEdge("pf4-deadlift", "pf4-sport"),
        TemplateEdge("pf4-bench", "pf4-sport"),
        TemplateEdge("pf4-hiit", "pf4-sport"),
        TemplateEdge("pf4-recovery", "pf4-squat"),
        TemplateEdge("pf4-recovery", "pf4-deadlift"),
        TemplateEdge("pf4-recovery", "pf4-bench"),
        TemplateEdge("pf4-distance", "pf4-battery"),
        TemplateEdge("pf4-pullup", "pf4-battery"),
        TemplateEdge("pf4-squat", "pf4-battery"),
        TemplateEdge("pf4-deadlift", "pf4-battery"),
        TemplateEdge("pf4-bench", "pf4-battery"),
        TemplateEdge("pf4-hiit", "pf4-battery"),
        TemplateEdge("pf4-sport", "pf4-battery"),
        TemplateEdge("pf4-recovery", "pf4-battery"),
    ],
)


# ── Tier 5: Independent ──

FITNESS_INDEPENDENT = Template(
    template_id="physical_fitness_independent",
    name="Physical Fitness: Independent",
    description=(
        "Self-directed programming, periodization, goal-based training, and "
        "lifelong fitness planning. The learner designs, executes, and "
        "evaluates their own training cycles."
    ),
    subject_name="Physical Fitness",
    subject_color="#263238",
    nodes=[
        _node(
            "pf5-assess",
            "Self-Assessment and Goal Setting",
            node_type="knowledge",
            description="Conduct a structured self-assessment and define SMART fitness goals.",
            benchmark="Produce a written self-assessment and three SMART goals with measurable targets.",
            assessment_type="pass_fail",
            unit="boolean",
            frequency=1,
            minutes=45,
            sort_order=0,
        ),
        _node(
            "pf5-periodize",
            "Program Periodization",
            node_type="knowledge",
            description="Design a 12-week periodized training block with specified phases and progression.",
            benchmark="Submit a 12-week written program with accumulation, intensification, and deload phases.",
            assessment_type="pass_fail",
            unit="boolean",
            frequency=1,
            minutes=90,
            sort_order=1,
        ),
        _node(
            "pf5-execute",
            "Program Execution and Log",
            node_type="project",
            description="Execute the personal program and maintain a daily training log.",
            benchmark="Complete 80% or more of planned training sessions over a 12-week block.",
            assessment_type="counted",
            unit="repetitions",
            frequency=5,
            minutes=60,
            sort_order=2,
        ),
        _node(
            "pf5-nutrition",
            "Training Nutrition",
            node_type="knowledge",
            description="Macronutrient basics, hydration, pre/post-training nutrition, recovery meals.",
            benchmark="Produce a 7-day nutrition plan aligned with the training program's goals.",
            assessment_type="pass_fail",
            unit="boolean",
            frequency=1,
            minutes=45,
            sort_order=3,
        ),
        _node(
            "pf5-recovery",
            "Advanced Recovery Protocols",
            node_type="knowledge",
            description="Sleep hygiene, HRV monitoring, mobility programming, and deload recognition.",
            benchmark="Maintain a 4-week recovery and readiness log with daily metrics.",
            assessment_type="pass_fail",
            unit="boolean",
            frequency=7,
            minutes=15,
            sort_order=4,
        ),
        _node(
            "pf5-specialize",
            "Activity Specialization",
            node_type="project",
            description="Select and train for a specific activity: strength sport, endurance event, team sport, or adventure goal.",
            benchmark="Compete in or complete the chosen activity with a documented performance outcome.",
            assessment_type="observed",
            unit="boolean",
            frequency=2,
            minutes=90,
            sort_order=5,
        ),
        _node(
            "pf5-reassess",
            "Mid-Block Reassessment",
            node_type="milestone",
            description="Repeat the fitness testing battery at the midpoint of the block and adjust the program.",
            benchmark="Produce a written reassessment with data-driven program adjustments.",
            assessment_type="pass_fail",
            unit="boolean",
            frequency=1,
            minutes=60,
            sort_order=6,
        ),
        _node(
            "pf5-lifelong",
            "Lifelong Fitness Plan",
            node_type="project",
            description="Draft a multi-year fitness roadmap across life stages: maintenance, progression, and longevity metrics.",
            benchmark="Submit a written multi-year plan reviewed and approved by a qualified adult.",
            assessment_type="pass_fail",
            unit="boolean",
            frequency=1,
            minutes=90,
            sort_order=7,
        ),
        _node(
            "coaching_fundamentals",
            "Coaching Fundamentals",
            node_type="project",
            description="Teach a fitness skill to a younger learner: plan a session, cue form, give feedback, and assess progress.",
            benchmark="Deliver a 20-minute fitness lesson to a younger learner with a written plan and reflection.",
            assessment_type="pass_fail",
            unit="boolean",
            frequency=1,
            minutes=60,
            sort_order=8,
        ),
        _node(
            "pf5-milestone",
            "Independent Capstone",
            node_type="milestone",
            description="Complete all Tier 5 deliverables and present results.",
            benchmark="Pass every Tier 5 node assessment and present the capstone to a reviewer.",
            assessment_type="pass_fail",
            unit="boolean",
            frequency=1,
            minutes=120,
            sort_order=9,
        ),
    ],
    edges=[
        TemplateEdge("pf5-assess", "pf5-periodize"),
        TemplateEdge("pf5-periodize", "pf5-execute"),
        TemplateEdge("pf5-nutrition", "pf5-execute"),
        TemplateEdge("pf5-recovery", "pf5-execute"),
        TemplateEdge("pf5-execute", "pf5-reassess"),
        TemplateEdge("pf5-reassess", "pf5-specialize"),
        TemplateEdge("pf5-specialize", "pf5-lifelong"),
        TemplateEdge("pf5-reassess", "pf5-lifelong"),
        TemplateEdge("pf5-specialize", "coaching_fundamentals"),
        TemplateEdge("pf5-assess", "pf5-milestone"),
        TemplateEdge("pf5-periodize", "pf5-milestone"),
        TemplateEdge("pf5-execute", "pf5-milestone"),
        TemplateEdge("pf5-nutrition", "pf5-milestone"),
        TemplateEdge("pf5-recovery", "pf5-milestone"),
        TemplateEdge("pf5-specialize", "pf5-milestone"),
        TemplateEdge("pf5-reassess", "pf5-milestone"),
        TemplateEdge("pf5-lifelong", "pf5-milestone"),
        TemplateEdge("coaching_fundamentals", "pf5-milestone"),
    ],
)


# Registry
FITNESS_TEMPLATES: dict[str, Template] = {
    t.template_id: t
    for t in [
        FITNESS_FOUNDATIONS,
        FITNESS_DEVELOPMENT,
        FITNESS_INTERMEDIATE,
        FITNESS_ADVANCED,
        FITNESS_INDEPENDENT,
    ]
}

# Register fitness templates into the shared TEMPLATES registry.
from app.services.templates import TEMPLATES as _CORE_TEMPLATES  # noqa: E402

_CORE_TEMPLATES.update(FITNESS_TEMPLATES)
