"""Starter learning map templates.

3 templates defined in code. Each is a read-only reference;
POST /v1/learning-maps/from-template/{template_id} deep-copies
into a household's map with new UUIDs.
"""

from dataclasses import dataclass, field


@dataclass
class TemplateNode:
    ref: str  # internal reference key for edge wiring
    node_type: str
    title: str
    description: str = ""
    estimated_minutes: int | None = None
    sort_order: int = 0
    content: dict | None = None


@dataclass
class TemplateEdge:
    from_ref: str
    to_ref: str
    relation: str = "prerequisite"


@dataclass
class Template:
    template_id: str
    name: str
    description: str
    subject_name: str
    subject_color: str
    nodes: list[TemplateNode] = field(default_factory=list)
    edges: list[TemplateEdge] = field(default_factory=list)


# ── Template 1: Mathematics Foundational ──

MATH_FOUNDATIONAL = Template(
    template_id="math-foundational",
    name="Mathematics Foundational",
    description="Complete K-1 mathematics covering counting, number recognition, addition and subtraction facts, place value, measurement, time, money, shapes, patterns, and word problems. 30 nodes with real prerequisite relationships matching the METHEAN scope and sequence.",
    subject_name="Mathematics",
    subject_color="#4A6FA5",
    nodes=[
        TemplateNode(
            "mf-01",
            "milestone",
            "Counting to 20",
            "Count objects to 20 with one-to-one correspondence. Recognize and write numerals 0-20.",
            20,
            0,
        ),
        TemplateNode(
            "mf-02",
            "concept",
            "Number Recognition 0-100",
            "Identify and read numerals from 0 to 100. Understand place value conceptually.",
            20,
            1,
        ),
        TemplateNode(
            "mf-03",
            "concept",
            "One-to-One Correspondence",
            "Match one object to one number when counting. Understand that the last number represents the total.",
            15,
            2,
        ),
        TemplateNode(
            "mf-04",
            "skill",
            "Counting to 100",
            "Count to 100 by ones. Count by tens to 100. Count forward from any number.",
            20,
            3,
        ),
        TemplateNode(
            "mf-05",
            "milestone",
            "Addition Facts to 10",
            "Learn all addition combinations that sum to 10 or less. Build toward automatic recall.",
            30,
            4,
        ),
        TemplateNode(
            "mf-06",
            "milestone",
            "Subtraction Facts to 10",
            "Learn all subtraction facts within 10. Connect subtraction to addition as inverse operations.",
            30,
            5,
        ),
        TemplateNode(
            "mf-07",
            "skill",
            "Addition Facts to 20",
            "Extend addition to sums within 20. Use strategies: counting on, making ten, doubles.",
            25,
            6,
        ),
        TemplateNode(
            "mf-08",
            "skill",
            "Subtraction Facts to 20",
            "Extend subtraction within 20. Use addition knowledge to solve subtraction problems.",
            25,
            7,
        ),
        TemplateNode(
            "mf-09",
            "concept",
            "Place Value Tens and Ones",
            "Understand that two-digit numbers are made of tens and ones. Decompose numbers like 34 = 3 tens + 4 ones.",
            25,
            8,
        ),
        TemplateNode(
            "mf-10",
            "skill",
            "Skip Counting by 2s 5s 10s",
            "Count by 2s, 5s, and 10s to 100. Recognize skip counting patterns.",
            20,
            9,
        ),
        TemplateNode(
            "mf-11",
            "concept",
            "Comparing Numbers",
            "Compare numbers using greater than, less than, and equal to. Use symbols > < =.",
            20,
            10,
        ),
        TemplateNode(
            "mf-12",
            "concept",
            "Ordinal Numbers",
            "Understand position words: first through tenth. Apply ordinal numbers to sequences.",
            15,
            11,
        ),
        TemplateNode(
            "mf-13",
            "skill",
            "Measurement Length",
            "Measure length using nonstandard units and rulers. Compare lengths of objects.",
            20,
            12,
        ),
        TemplateNode(
            "mf-14",
            "skill",
            "Measurement Weight",
            "Compare weights of objects using balance scales. Use nonstandard units.",
            20,
            13,
        ),
        TemplateNode(
            "mf-15",
            "skill",
            "Time Hours and Half Hours",
            "Read analog and digital clocks to the hour and half hour. Understand AM and PM.",
            20,
            14,
        ),
        TemplateNode(
            "mf-16",
            "skill",
            "Coins Identification",
            "Identify penny, nickel, dime, quarter. Know their values.",
            15,
            15,
        ),
        TemplateNode(
            "mf-17",
            "concept",
            "2D Shapes",
            "Identify and describe circles, squares, rectangles, triangles, hexagons. Count sides and vertices.",
            20,
            16,
        ),
        TemplateNode(
            "mf-18",
            "concept",
            "Patterns and Sequences",
            "Identify, extend, and create repeating and growing patterns using objects, numbers, and shapes.",
            20,
            17,
        ),
        TemplateNode(
            "mf-19",
            "skill",
            "Number Lines",
            "Use number lines to count, add, subtract, and compare numbers. Place numbers on a line.",
            20,
            18,
        ),
        TemplateNode(
            "mf-20",
            "concept",
            "Even and Odd Numbers",
            "Identify even and odd numbers. Understand that even numbers can be split into two equal groups.",
            15,
            19,
        ),
        TemplateNode(
            "mf-21",
            "concept",
            "Fractions Visual Half and Quarter",
            "Understand halves and quarters using pictures, objects, and folding. Equal parts of a whole.",
            20,
            20,
        ),
        TemplateNode(
            "mf-22",
            "skill",
            "Tally Charts and Data",
            "Collect data, organize it in tally charts, and answer questions about the data.",
            15,
            21,
        ),
        TemplateNode(
            "mf-23",
            "skill",
            "Word Problems Addition",
            "Solve single-step addition word problems. Identify key words and draw pictures to solve.",
            25,
            22,
        ),
        TemplateNode(
            "mf-24",
            "skill",
            "Word Problems Subtraction",
            "Solve single-step subtraction word problems. Identify the operation needed.",
            25,
            23,
        ),
        TemplateNode(
            "mf-25",
            "skill",
            "Addition of Three Numbers",
            "Add three single-digit numbers. Use strategies like making ten and doubles.",
            20,
            24,
        ),
        TemplateNode(
            "mf-26",
            "skill",
            "Mental Math Strategies",
            "Develop mental math strategies: counting on, making ten, using doubles, breaking apart numbers.",
            20,
            25,
        ),
        TemplateNode(
            "mf-27",
            "concept",
            "Estimation Introduction",
            "Estimate quantities and sums before calculating. Develop number sense for reasonableness.",
            15,
            26,
        ),
        TemplateNode(
            "mf-28",
            "skill",
            "Number Bonds to 20",
            "Know all number bonds (pairs that make a given number) for numbers to 20.",
            20,
            27,
        ),
        TemplateNode(
            "mf-29",
            "skill",
            "Sorting and Classifying",
            "Sort objects by color, shape, size, and other attributes. Classify into groups.",
            15,
            28,
        ),
        TemplateNode(
            "mf-30",
            "milestone",
            "Foundational Math Assessment",
            "Comprehensive review and assessment of all foundational math skills.",
            30,
            29,
        ),
        TemplateNode(
            "mf-31",
            "milestone",
            "Count to 5",
            "Count up to five objects with one-to-one correspondence, touching each object once and saying one number word per object. Recognize that the count words go 1, 2, 3, 4, 5 in a fixed order.",
            15,
            30,
        ),
        TemplateNode(
            "mf-32",
            "concept",
            "Count to 10 with objects",
            "Count up to ten objects with one-to-one correspondence, saying one number word per object in the fixed order 1 through 10, and state the total as the last number said.",
            15,
            31,
        ),
        TemplateNode(
            "mf-33",
            "skill",
            "Subitize quantities 1 to 5",
            "Instantly recognize how many are in a small set of one to five without counting one by one, on dot patterns, dice faces, and fingers.",
            15,
            32,
        ),
        TemplateNode(
            "mf-34",
            "concept",
            "Ten-frame to 10",
            "Represent quantities from zero to ten on a ten-frame, filling cells left to right and top to bottom, seeing a full frame as ten and reading 'five and some more' for quantities above five.",
            20,
            33,
        ),
        TemplateNode(
            "mf-35",
            "concept",
            "Cardinality principle",
            "Understand that the last number said when counting a set tells how many are in the whole set, and that the total stays the same no matter the order in which the objects are counted.",
            15,
            34,
        ),
        TemplateNode(
            "mf-36",
            "skill",
            "Count backward from 10",
            "Recite the number sequence backward from ten to one, and count down from any number within ten, understanding that each step back is one fewer.",
            15,
            35,
        ),
        TemplateNode(
            "mf-37",
            "skill",
            "Count backward from 20",
            "Recite the number sequence backward from twenty to one, and count down from any number within twenty, extending reverse counting through the teen numbers.",
            20,
            36,
        ),
        TemplateNode(
            "mf-38",
            "skill",
            "Count on within 20",
            "Begin counting from a given number rather than always from one, and count on to twenty from any starting point, building toward addition by counting up.",
            20,
            37,
        ),
        TemplateNode(
            "mf-39",
            "skill",
            "Write numerals 0 to 10",
            "Form and write the numerals zero through ten legibly, using correct starting points and stroke order, and match each written numeral to its quantity.",
            20,
            38,
        ),
        TemplateNode(
            "mf-40",
            "skill",
            "Write numerals 11 to 20",
            "Form and write the teen numerals eleven through twenty legibly, understanding that each is written as a ten and some ones, and match each written teen numeral to its quantity.",
            20,
            39,
        ),
        TemplateNode(
            "mf-41",
            "skill",
            "Count within 120",
            "Count by ones from any number up to one hundred twenty, continuing the counting sequence smoothly past one hundred and across the decade boundaries.",
            20,
            40,
        ),
        TemplateNode(
            "mf-42",
            "concept",
            "Hundreds chart navigation",
            "Read and move on a hundreds chart, understanding that moving one space right adds one, moving one space down adds ten, and using rows and columns to find numbers quickly.",
            20,
            41,
        ),
        TemplateNode(
            "mf-43",
            "skill",
            "Write numerals to 100",
            "Write any numeral from zero to one hundred legibly, forming two-digit numbers as tens and ones in the correct order, and write the numeral that matches a spoken or shown number.",
            20,
            42,
        ),
        TemplateNode(
            "mf-44",
            "skill",
            "Count on within 100",
            "Begin counting from any number within one hundred and count on by ones, crossing decade boundaries smoothly, building fluency for adding by counting up.",
            20,
            43,
        ),
        TemplateNode(
            "mf-45",
            "concept",
            "Compare two groups: more, fewer, same",
            "Compare two groups of objects by matching them one to one to decide which has more, which has fewer, or whether they are the same, without yet using numerals.",
            15,
            44,
        ),
        TemplateNode(
            "mf-46",
            "concept",
            "Comparison symbols",
            "Read and write the comparison symbols greater than, less than, and equal to between two numbers, understanding that the open side of the symbol always faces the larger number.",
            20,
            45,
        ),
        TemplateNode(
            "mf-47",
            "skill",
            "Order numbers within 100",
            "Arrange three or more numbers within one hundred from least to greatest and from greatest to least, comparing tens first and then ones.",
            20,
            46,
        ),
        TemplateNode(
            "mf-48",
            "skill",
            "One more, one less",
            "Find the number that is one more and the number that is one less than any number within one hundred, connecting it to counting forward and backward by one.",
            15,
            47,
        ),
        TemplateNode(
            "mf-49",
            "skill",
            "Ten more, ten less",
            "Find ten more and ten less than any two-digit number, understanding that only the tens digit changes by one while the ones digit stays the same.",
            20,
            48,
        ),
        TemplateNode(
            "mf-50",
            "concept",
            "Growing and repeating patterns",
            "Tell the difference between a repeating pattern, where a core unit repeats, and a growing pattern, where each step adds more, and extend both kinds.",
            20,
            49,
        ),
        TemplateNode(
            "mf-51",
            "milestone",
            "Skip-counting fluency to 100",
            "Skip-count by twos, fives, and tens to one hundred fluently and from memory, with quick, accurate recall that supports later multiplication and money.",
            20,
            50,
        ),
        TemplateNode(
            "mf-52",
            "concept",
            "Teen numbers as ten and ones",
            "Compose and decompose the teen numbers eleven through nineteen as one ten and some ones, building the foundation of place value.",
            20,
            51,
        ),
        TemplateNode(
            "mf-53",
            "skill",
            "Bundle tens with manipulatives",
            "Make groups of ten from loose objects, count collections by bundling tens and ones, and see that ten ones can be traded for one ten.",
            20,
            52,
        ),
        TemplateNode(
            "mf-54",
            "concept",
            "Two-digit numbers as tens and ones",
            "Read, build, and write any two-digit number as a number of tens and ones, including its expanded form, and explain the value of each digit.",
            20,
            53,
        ),
        TemplateNode(
            "mf-55",
            "concept",
            "Place value to hundreds",
            "Understand that ten tens make one hundred, and read the hundreds, tens, and ones places in numbers up to several hundred using base-ten materials.",
            20,
            54,
        ),
        TemplateNode(
            "mf-56",
            "concept",
            "Three-digit place value",
            "Read, build, and identify the hundreds, tens, and ones in any three-digit number, stating the value of each digit by its place.",
            20,
            55,
        ),
        TemplateNode(
            "mf-57",
            "concept",
            "Expanded form of three-digit numbers",
            "Write a three-digit number in expanded form as hundreds plus tens plus ones, and build a number from its expanded form.",
            20,
            56,
        ),
        TemplateNode(
            "mf-58",
            "skill",
            "Compare three-digit numbers",
            "Compare two three-digit numbers by looking at the hundreds first, then the tens, then the ones, and write the correct comparison symbol.",
            20,
            57,
        ),
        TemplateNode(
            "mf-59",
            "skill",
            "Numbers on a number line to 100",
            "Locate, place, and estimate the position of numbers up to one hundred on a number line, using the marked tens as benchmarks.",
            20,
            58,
        ),
        TemplateNode(
            "mf-60",
            "milestone",
            "Addition as putting together",
            "Understand addition as putting two parts together to make a whole, joining two groups and finding the total, and using part-part-whole language.",
            20,
            59,
        ),
        TemplateNode(
            "mf-61",
            "skill",
            "Addition within 5",
            "Join two groups within five and record the total with the plus and equals signs, writing the number sentence that matches a putting-together picture.",
            20,
            60,
        ),
        TemplateNode(
            "mf-62",
            "skill",
            "Addition facts within 5 to automaticity",
            "Build automatic recall of addition facts within five: accurate first, then quick, so the facts come without counting in a short timed practice.",
            20,
            61,
        ),
        TemplateNode(
            "mf-63",
            "skill",
            "Addition facts within 10 to automaticity",
            "Build automatic recall of addition facts within ten, leaning on partners of ten and doubles so the facts come quickly and accurately without counting.",
            20,
            62,
        ),
        TemplateNode(
            "mf-64",
            "skill",
            "Number bonds to 10",
            "Learn the number bonds to ten, the pairs of numbers that make ten, find the missing partner for any number, and use the bonds to add flexibly.",
            20,
            63,
        ),
        TemplateNode(
            "mf-65",
            "skill",
            "Doubles facts",
            "Recognize doubles facts as a number added to itself, find the doubles from one and one to five and five, and connect them to real equal pairs.",
            20,
            64,
        ),
        TemplateNode(
            "mf-66",
            "skill",
            "Doubles facts to ten and ten to automaticity",
            "Build automatic recall of all the doubles up to ten and ten, using doubles as anchor facts, with accuracy first and then speed in a short timed practice.",
            20,
            65,
        ),
        TemplateNode(
            "mf-67",
            "skill",
            "Near-doubles strategy",
            "Use a known double to solve a near-doubles fact by solving the hidden double and adding one more, and explain the strategy in words.",
            20,
            66,
        ),
        TemplateNode(
            "mf-68",
            "skill",
            "Make-a-ten strategy",
            "Add across ten by splitting an addend to make a ten and then adding the remainder, shown on a ten-frame, using known partners of ten.",
            20,
            67,
        ),
        TemplateNode(
            "mf-69",
            "skill",
            "Make-ten facts to automaticity",
            "Build automatic recall of across-ten addition facts using the make-a-ten idea mentally, with accuracy first and then speed in a short timed practice.",
            20,
            68,
        ),
        TemplateNode(
            "mf-70",
            "skill",
            "Commutative property of addition",
            "Understand that the order of two addends does not change the sum, write both number sentences for a pair, and start from the larger addend to add efficiently.",
            20,
            69,
        ),
        TemplateNode(
            "mf-71",
            "skill",
            "Adding zero",
            "Understand that adding zero leaves a number unchanged because zero is an empty group, solve plus-zero facts, and explain why nothing added means no change.",
            20,
            70,
        ),
        TemplateNode(
            "mf-72",
            "skill",
            "Count-on strategy for plus one, two, and three",
            "Add one, two, or three by counting on from the larger addend rather than counting all, tracking the count on fingers and reaching the correct total.",
            20,
            71,
        ),
        TemplateNode(
            "mf-73",
            "milestone",
            "Addition facts within 20 to automaticity",
            "Bring all addition facts within twenty to automatic recall, accurate first and then quick, drawing on doubles, near-doubles, make-a-ten, and partners of ten for the few facts not yet fluent.",
            20,
            72,
        ),
        TemplateNode(
            "mf-74",
            "skill",
            "Add three numbers using make-ten and doubles",
            "Add three one-digit numbers by first choosing a pair that makes ten or a double, adding that pair, then adding the third number, and explain why grouping a friendly pair first is easier.",
            20,
            73,
        ),
        TemplateNode(
            "mf-75",
            "skill",
            "Subtraction as taking from",
            "Understand subtraction as taking a part from a whole to find how many are left, name the whole and the two parts, and find a missing part given the whole and one part.",
            20,
            74,
        ),
        TemplateNode(
            "mf-76",
            "skill",
            "Subtraction within 5",
            "Take away within five and record the result with the minus and equals signs, writing the number sentence that matches a take-away picture.",
            20,
            75,
        ),
        TemplateNode(
            "mf-77",
            "skill",
            "Subtraction facts within 5 to automaticity",
            "Build automatic recall of subtraction facts within five: accurate first, then quick, so the differences come without counting in a short timed practice.",
            20,
            76,
        ),
        TemplateNode(
            "mf-78",
            "skill",
            "Subtraction facts within 10 to automaticity",
            "Build automatic recall of subtraction facts within ten, leaning on number bonds so the differences come quickly and accurately without counting.",
            20,
            77,
        ),
        TemplateNode(
            "mf-79",
            "skill",
            "Subtraction as an unknown addend",
            "Solve subtraction by thinking addition, rewriting a difference as a missing-addend question, and check the answer by adding the part back to make the whole.",
            20,
            78,
        ),
        TemplateNode(
            "mf-80",
            "skill",
            "Fact families",
            "Use three numbers to write the four related facts of an addition and subtraction fact family, identifying the whole and two parts, and use the family to find a missing number.",
            20,
            79,
        ),
        TemplateNode(
            "mf-81",
            "skill",
            "Count-back strategy for minus one, two, and three",
            "Subtract one, two, or three by counting back from the whole rather than counting all, tracking the count on fingers and reaching the correct difference.",
            20,
            80,
        ),
        TemplateNode(
            "mf-82",
            "skill",
            "Subtraction facts within 20 to automaticity",
            "Bring subtraction facts within twenty to automatic recall, accurate first and then quick, using think-addition, count-back, and number bonds for the few facts not yet fluent.",
            20,
            81,
        ),
        TemplateNode(
            "mf-83",
            "milestone",
            "Mixed addition and subtraction facts within 20 to automaticity",
            "Bring mixed addition and subtraction facts within twenty to automatic recall, reading the operation sign first and switching smoothly between adding and subtracting in a timed practice.",
            20,
            82,
        ),
        TemplateNode(
            "mf-84",
            "skill",
            "Missing addend and missing subtrahend equations",
            "Find the unknown in addition and subtraction equations with a blank, deciding whether the missing number is a part or the whole, and check the solution by substituting it back.",
            20,
            83,
        ),
        TemplateNode(
            "mf-85",
            "skill",
            "Meaning of the equal sign",
            "Understand the equal sign as the same amount on both sides, judge number sentences true or false, balance equations with an expression on each side, and reject equals as merely signaling an answer.",
            20,
            84,
        ),
        TemplateNode(
            "mf-86",
            "skill",
            "Two-digit plus one-digit without regrouping",
            "Add a one-digit number to a two-digit number without regrouping by adding the ones and keeping the tens the same, using place value to keep digits in the right columns.",
            20,
            85,
        ),
        TemplateNode(
            "mf-87",
            "skill",
            "Add tens to a two-digit number",
            "Add a multiple of ten to a two-digit number by adding the tens and keeping the ones the same, using counting on by tens and place value.",
            20,
            86,
        ),
        TemplateNode(
            "mf-88",
            "skill",
            "Two-digit plus two-digit without regrouping",
            "Add two two-digit numbers without regrouping by adding ones to ones and tens to tens, lining up digits by place value, with blocks and a written column form.",
            20,
            87,
        ),
        TemplateNode(
            "mf-89",
            "skill",
            "Subtract tens from a two-digit number",
            "Subtract a multiple of ten from a two-digit number by taking away the tens and keeping the ones the same, using counting back by tens and place value.",
            20,
            88,
        ),
        TemplateNode(
            "mf-90",
            "skill",
            "Two-digit minus two-digit without regrouping",
            "Subtract one two-digit number from another without regrouping by taking ones from ones and tens from tens, lined up by place value, and check the difference by adding it back.",
            20,
            89,
        ),
    ],
    edges=[
        TemplateEdge("mf-01", "mf-02"),
        TemplateEdge("mf-01", "mf-03"),
        TemplateEdge("mf-01", "mf-04", "prerequisite"),
        TemplateEdge("mf-01", "mf-05", "prerequisite"),
        TemplateEdge("mf-02", "mf-04"),
        TemplateEdge("mf-02", "mf-05"),
        TemplateEdge("mf-03", "mf-05"),
        TemplateEdge("mf-05", "mf-06"),
        TemplateEdge("mf-05", "mf-07"),
        TemplateEdge("mf-09", "mf-07"),
        TemplateEdge("mf-06", "mf-08"),
        TemplateEdge("mf-09", "mf-08"),
        TemplateEdge("mf-04", "mf-09"),
        TemplateEdge("mf-04", "mf-10"),
        TemplateEdge("mf-04", "mf-11"),
        TemplateEdge("mf-04", "mf-12"),
        TemplateEdge("mf-11", "mf-13"),
        TemplateEdge("mf-11", "mf-14"),
        TemplateEdge("mf-02", "mf-15"),
        TemplateEdge("mf-02", "mf-16"),
        TemplateEdge("mf-01", "mf-17"),
        TemplateEdge("mf-01", "mf-18"),
        TemplateEdge("mf-04", "mf-19"),
        TemplateEdge("mf-11", "mf-19"),
        TemplateEdge("mf-10", "mf-20"),
        TemplateEdge("mf-11", "mf-21"),
        TemplateEdge("mf-01", "mf-22"),
        TemplateEdge("mf-07", "mf-23"),
        TemplateEdge("mf-08", "mf-24"),
        TemplateEdge("mf-07", "mf-25"),
        TemplateEdge("mf-07", "mf-26"),
        TemplateEdge("mf-08", "mf-26"),
        TemplateEdge("mf-11", "mf-27"),
        TemplateEdge("mf-07", "mf-28"),
        TemplateEdge("mf-11", "mf-29"),
        TemplateEdge("mf-17", "mf-29"),
        TemplateEdge("mf-31", "mf-32"),
        TemplateEdge("mf-31", "mf-33"),
        TemplateEdge("mf-32", "mf-34"),
        TemplateEdge("mf-33", "mf-34"),
        TemplateEdge("mf-03", "mf-35"),
        TemplateEdge("mf-32", "mf-36"),
        TemplateEdge("mf-01", "mf-37"),
        TemplateEdge("mf-36", "mf-37"),
        TemplateEdge("mf-01", "mf-38"),
        TemplateEdge("mf-32", "mf-39"),
        TemplateEdge("mf-01", "mf-40"),
        TemplateEdge("mf-39", "mf-40"),
        TemplateEdge("mf-04", "mf-41"),
        TemplateEdge("mf-04", "mf-42"),
        TemplateEdge("mf-02", "mf-43"),
        TemplateEdge("mf-40", "mf-43"),
        TemplateEdge("mf-04", "mf-44"),
        TemplateEdge("mf-35", "mf-45"),
        TemplateEdge("mf-11", "mf-46"),
        TemplateEdge("mf-11", "mf-47"),
        TemplateEdge("mf-11", "mf-48"),
        TemplateEdge("mf-42", "mf-49"),
        TemplateEdge("mf-11", "mf-49"),
        TemplateEdge("mf-18", "mf-50"),
        TemplateEdge("mf-10", "mf-51"),
        TemplateEdge("mf-34", "mf-52"),
        TemplateEdge("mf-09", "mf-52"),
        TemplateEdge("mf-09", "mf-53"),
        TemplateEdge("mf-09", "mf-54"),
        TemplateEdge("mf-54", "mf-55"),
        TemplateEdge("mf-55", "mf-56"),
        TemplateEdge("mf-56", "mf-57"),
        TemplateEdge("mf-56", "mf-58"),
        TemplateEdge("mf-46", "mf-58"),
        TemplateEdge("mf-19", "mf-59"),
        TemplateEdge("mf-34", "mf-60"),
        TemplateEdge("mf-35", "mf-60"),
        TemplateEdge("mf-60", "mf-61"),
        TemplateEdge("mf-61", "mf-62"),
        TemplateEdge("mf-05", "mf-63"),
        TemplateEdge("mf-62", "mf-63"),
        TemplateEdge("mf-05", "mf-64"),
        TemplateEdge("mf-05", "mf-65"),
        TemplateEdge("mf-65", "mf-66"),
        TemplateEdge("mf-66", "mf-67"),
        TemplateEdge("mf-64", "mf-68"),
        TemplateEdge("mf-68", "mf-69"),
        TemplateEdge("mf-05", "mf-70"),
        TemplateEdge("mf-61", "mf-71"),
        TemplateEdge("mf-38", "mf-72"),
        TemplateEdge("mf-61", "mf-72"),
        TemplateEdge("mf-07", "mf-73"),
        TemplateEdge("mf-63", "mf-73"),
        TemplateEdge("mf-69", "mf-73"),
        TemplateEdge("mf-25", "mf-74"),
        TemplateEdge("mf-69", "mf-74"),
        TemplateEdge("mf-60", "mf-75"),
        TemplateEdge("mf-75", "mf-76"),
        TemplateEdge("mf-76", "mf-77"),
        TemplateEdge("mf-06", "mf-78"),
        TemplateEdge("mf-77", "mf-78"),
        TemplateEdge("mf-06", "mf-79"),
        TemplateEdge("mf-64", "mf-79"),
        TemplateEdge("mf-79", "mf-80"),
        TemplateEdge("mf-36", "mf-81"),
        TemplateEdge("mf-76", "mf-81"),
        TemplateEdge("mf-08", "mf-82"),
        TemplateEdge("mf-78", "mf-82"),
        TemplateEdge("mf-73", "mf-83"),
        TemplateEdge("mf-82", "mf-83"),
        TemplateEdge("mf-80", "mf-84"),
        TemplateEdge("mf-61", "mf-85"),
        TemplateEdge("mf-76", "mf-85"),
        TemplateEdge("mf-54", "mf-86"),
        TemplateEdge("mf-73", "mf-86"),
        TemplateEdge("mf-49", "mf-87"),
        TemplateEdge("mf-54", "mf-87"),
        TemplateEdge("mf-86", "mf-88"),
        TemplateEdge("mf-87", "mf-88"),
        TemplateEdge("mf-49", "mf-89"),
        TemplateEdge("mf-54", "mf-89"),
        TemplateEdge("mf-82", "mf-90"),
        TemplateEdge("mf-89", "mf-90"),
    ],
)

# ── Template 2: Elementary Core ──

ELEMENTARY_CORE = Template(
    template_id="elementary-core",
    name="Elementary Core",
    description="3rd-5th grade core curriculum: math, language arts, and science",
    subject_name="Elementary Core",
    subject_color="#2196F3",
    nodes=[
        # Math
        TemplateNode("math-root", "root", "Mathematics", "3rd-5th grade math", sort_order=0),
        TemplateNode("multiplication", "milestone", "Multiplication", "Multiplication facts and concepts", 30, 1),
        TemplateNode("division", "concept", "Division", "Division as inverse of multiplication", 30, 2),
        TemplateNode("fractions", "concept", "Fractions", "Fraction concepts and operations", 35, 3),
        TemplateNode("decimals", "skill", "Decimals", "Decimal notation and operations", 30, 4),
        # Language Arts
        TemplateNode("ela-root", "root", "Language Arts", "Reading comprehension and writing", sort_order=10),
        TemplateNode("paragraphs", "milestone", "Paragraph Writing", "Topic sentence, body, conclusion", 30, 11),
        TemplateNode("essay-intro", "concept", "Essay Structure", "Five-paragraph essay basics", 35, 12),
        TemplateNode("grammar", "skill", "Grammar & Mechanics", "Parts of speech, punctuation", 25, 13),
        # Science
        TemplateNode("sci-root", "root", "Science", "Elementary science foundations", sort_order=20),
        TemplateNode("sci-method", "milestone", "Scientific Method", "Observation, hypothesis, experiment", 30, 21),
        TemplateNode("life-sci", "concept", "Life Science", "Plants, animals, ecosystems", 35, 22),
        TemplateNode("earth-sci", "concept", "Earth Science", "Weather, rocks, water cycle", 35, 23),
    ],
    edges=[
        TemplateEdge("math-root", "multiplication"),
        TemplateEdge("multiplication", "division"),
        TemplateEdge("division", "fractions"),
        TemplateEdge("fractions", "decimals"),
        TemplateEdge("ela-root", "paragraphs"),
        TemplateEdge("paragraphs", "essay-intro"),
        TemplateEdge("paragraphs", "grammar"),
        TemplateEdge("sci-root", "sci-method"),
        TemplateEdge("sci-method", "life-sci"),
        TemplateEdge("sci-method", "earth-sci"),
    ],
)

# ── Template 3: Classical Logic ──

CLASSICAL_LOGIC = Template(
    template_id="classical-logic",
    name="Classical Logic Stage",
    description="Logic-stage curriculum (grades 5-8): formal reasoning, rhetoric foundations, and Latin roots",
    subject_name="Classical Logic",
    subject_color="#9C27B0",
    nodes=[
        # Logic
        TemplateNode("logic-root", "root", "Formal Logic", "Introduction to logical reasoning", sort_order=0),
        TemplateNode("propositions", "milestone", "Propositions", "Statements, truth values, negation", 30, 1),
        TemplateNode("syllogisms", "concept", "Syllogisms", "Major premise, minor premise, conclusion", 35, 2),
        TemplateNode("fallacies", "concept", "Logical Fallacies", "Common informal fallacies", 30, 3),
        TemplateNode("argument", "skill", "Argument Construction", "Build and evaluate arguments", 40, 4),
        # Rhetoric
        TemplateNode("rhet-root", "root", "Rhetoric Foundations", "Art of persuasion basics", sort_order=10),
        TemplateNode("ethos", "concept", "Ethos", "Credibility and character appeals", 25, 11),
        TemplateNode("pathos", "concept", "Pathos", "Emotional appeals", 25, 12),
        TemplateNode("logos", "concept", "Logos", "Logical appeals", 25, 13),
        TemplateNode("persuasive", "skill", "Persuasive Writing", "Combine appeals in writing", 40, 14),
    ],
    edges=[
        TemplateEdge("logic-root", "propositions"),
        TemplateEdge("propositions", "syllogisms"),
        TemplateEdge("syllogisms", "fallacies"),
        TemplateEdge("fallacies", "argument"),
        TemplateEdge("rhet-root", "ethos"),
        TemplateEdge("rhet-root", "pathos"),
        TemplateEdge("rhet-root", "logos"),
        TemplateEdge("ethos", "persuasive"),
        TemplateEdge("pathos", "persuasive"),
        TemplateEdge("logos", "persuasive"),
        # Cross-domain: logic strengthens rhetoric
        TemplateEdge("syllogisms", "logos"),
    ],
)


# ── Template 4: Welding Fundamentals ──

WELDING_FUNDAMENTALS = Template(
    template_id="welding-fundamentals",
    name="Welding Fundamentals",
    description="MIG, TIG, and stick welding from safety through certification prep.",
    subject_name="Welding",
    subject_color="#D84315",
    nodes=[
        TemplateNode(
            "weld-safety",
            "safety",
            "Shop Safety & PPE",
            "Welding hazards, PPE, fire prevention, ventilation, burn treatment.",
            60,
            0,
        ),
        TemplateNode(
            "weld-metals",
            "knowledge",
            "Metal Identification",
            "Mild steel, stainless, aluminum. Material properties, filler selection.",
            45,
            1,
        ),
        TemplateNode(
            "weld-positions",
            "knowledge",
            "Welding Positions & Joint Types",
            "Flat, horizontal, vertical, overhead. Butt, lap, T-joint, corner.",
            45,
            2,
        ),
        TemplateNode(
            "weld-mig-setup",
            "technique",
            "MIG Welder Setup",
            "Wire feed speed, voltage, gas flow. Contact tip, nozzle maintenance.",
            60,
            3,
        ),
        TemplateNode(
            "weld-mig-flat",
            "technique",
            "MIG Flat Position",
            "Bead runs on flat plate. Travel speed, work angle, push vs drag.",
            90,
            4,
        ),
        TemplateNode(
            "weld-mig-horiz",
            "technique",
            "MIG Horizontal & Vertical",
            "Horizontal fillet welds. Vertical up technique. Puddle control.",
            90,
            5,
        ),
        TemplateNode(
            "weld-stick-setup",
            "technique",
            "Stick (SMAW) Setup",
            "Polarity, electrode selection (6010, 7018), arc length, amperage.",
            60,
            6,
        ),
        TemplateNode(
            "weld-stick-flat",
            "technique",
            "Stick Flat Position",
            "Flat bead runs with 6013 and 7018. Rod angle, restart technique.",
            90,
            7,
        ),
        TemplateNode(
            "weld-tig-intro",
            "technique",
            "TIG (GTAW) Introduction",
            "Machine setup, tungsten selection, gas cup, filler rod on mild steel.",
            90,
            8,
        ),
        TemplateNode(
            "weld-inspection",
            "knowledge",
            "Weld Inspection & Testing",
            "Visual inspection. Undercut, porosity, lack of fusion. Bend test.",
            45,
            9,
        ),
        TemplateNode(
            "weld-project1",
            "project",
            "Project: Flat Table Bracket",
            "Fabricate steel bracket using MIG. Cut, fit, tack, weld, grind.",
            120,
            10,
        ),
        TemplateNode(
            "weld-project2",
            "project",
            "Project: Multi-Joint Weldment",
            "Structure with butt, lap, T-joints. Multiple positions. Inspection.",
            180,
            11,
        ),
        TemplateNode(
            "weld-cert-prep",
            "certification_prep",
            "AWS Certification Prep",
            "AWS D1.1 code basics. Qualification test format. Practice plates.",
            120,
            12,
        ),
    ],
    edges=[
        TemplateEdge("weld-safety", "weld-mig-setup"),
        TemplateEdge("weld-safety", "weld-stick-setup"),
        TemplateEdge("weld-safety", "weld-tig-intro"),
        TemplateEdge("weld-metals", "weld-mig-setup"),
        TemplateEdge("weld-positions", "weld-mig-flat"),
        TemplateEdge("weld-mig-setup", "weld-mig-flat"),
        TemplateEdge("weld-mig-flat", "weld-mig-horiz"),
        TemplateEdge("weld-stick-setup", "weld-stick-flat"),
        TemplateEdge("weld-mig-horiz", "weld-project1"),
        TemplateEdge("weld-stick-flat", "weld-project2"),
        TemplateEdge("weld-tig-intro", "weld-project2"),
        TemplateEdge("weld-inspection", "weld-cert-prep"),
        TemplateEdge("weld-project2", "weld-cert-prep"),
    ],
)


# ── Template 5: Electrical Fundamentals ──

ELECTRICAL_FUNDAMENTALS = Template(
    template_id="electrical-fundamentals",
    name="Electrical Fundamentals",
    description="Residential electrical from Ohm's law through circuit installation.",
    subject_name="Electrical",
    subject_color="#FFA000",
    nodes=[
        TemplateNode(
            "elec-safety",
            "safety",
            "Electrical Safety & Lockout/Tagout",
            "Shock hazards, GFCI, lockout/tagout, meter safety, arc flash.",
            60,
            0,
        ),
        TemplateNode(
            "elec-ohms",
            "knowledge",
            "Ohm's Law & Basic Circuits",
            "Voltage, current, resistance. Series and parallel. P=IV.",
            45,
            1,
        ),
        TemplateNode(
            "elec-tools",
            "technique",
            "Meter Usage & Wire Skills",
            "Multimeter operation. Wire stripping, termination, splicing.",
            60,
            2,
        ),
        TemplateNode(
            "elec-nec",
            "knowledge",
            "NEC Code Basics",
            "Wire sizing (AWG), breaker ratings, box fill, grounding.",
            60,
            3,
        ),
        TemplateNode(
            "elec-outlets",
            "technique",
            "Outlet & Switch Installation",
            "Single-pole, 3-way switch, duplex outlet, GFCI outlet.",
            90,
            4,
        ),
        TemplateNode(
            "elec-circuits",
            "technique",
            "Residential Circuit Design",
            "Branch circuit layout, load calculation, panel scheduling.",
            90,
            5,
        ),
        TemplateNode(
            "elec-rough",
            "technique",
            "Rough-In Wiring",
            "Running Romex, drilling studs, securing cable, box mounting.",
            120,
            6,
        ),
        TemplateNode(
            "elec-project1",
            "project",
            "Project: Wire a Room",
            "Complete rough-in and finish for a bedroom. Inspect and test.",
            180,
            7,
        ),
        TemplateNode(
            "elec-240v",
            "knowledge",
            "240V Circuits & Subpanels",
            "Double-pole breakers, 10/3 wire, dryer/range connections.",
            60,
            8,
        ),
        TemplateNode(
            "elec-project2",
            "project",
            "Project: Subpanel Installation",
            "Install subpanel in garage. Run feeder, land circuits, test.",
            180,
            9,
        ),
        TemplateNode(
            "elec-cert",
            "certification_prep",
            "Journeyman Exam Prep",
            "NEC code review, practice calculations, sample exam questions.",
            120,
            10,
        ),
    ],
    edges=[
        TemplateEdge("elec-safety", "elec-tools"),
        TemplateEdge("elec-safety", "elec-outlets"),
        TemplateEdge("elec-safety", "elec-rough"),
        TemplateEdge("elec-ohms", "elec-tools"),
        TemplateEdge("elec-ohms", "elec-nec"),
        TemplateEdge("elec-nec", "elec-circuits"),
        TemplateEdge("elec-tools", "elec-outlets"),
        TemplateEdge("elec-outlets", "elec-rough"),
        TemplateEdge("elec-circuits", "elec-rough"),
        TemplateEdge("elec-rough", "elec-project1"),
        TemplateEdge("elec-nec", "elec-240v"),
        TemplateEdge("elec-240v", "elec-project2"),
        TemplateEdge("elec-project1", "elec-project2"),
        TemplateEdge("elec-project2", "elec-cert"),
    ],
)


# ── Template 6: Automotive Fundamentals ──

AUTOMOTIVE_FUNDAMENTALS = Template(
    template_id="automotive-fundamentals",
    name="Automotive Fundamentals",
    description="Vehicle systems from basic maintenance through diagnostics.",
    subject_name="Automotive",
    subject_color="#37474F",
    nodes=[
        TemplateNode(
            "auto-safety",
            "safety",
            "Shop Safety & Tool ID",
            "Jack stand safety, chemical handling, fire extinguisher, eye protection.",
            45,
            0,
        ),
        TemplateNode(
            "auto-systems",
            "knowledge",
            "Vehicle Systems Overview",
            "Engine, transmission, brakes, suspension, electrical, cooling.",
            60,
            1,
        ),
        TemplateNode(
            "auto-oil",
            "technique",
            "Oil Change & Fluid Checks",
            "Oil drain, filter replacement, fluid level checks.",
            45,
            2,
        ),
        TemplateNode(
            "auto-tires",
            "technique",
            "Tires, Rotation & Brake Inspection",
            "Tire pressure, tread depth, rotation, visual brake inspection.",
            60,
            3,
        ),
        TemplateNode(
            "auto-brakes",
            "technique",
            "Brake Pad & Rotor Replacement",
            "Caliper removal, pad replacement, rotor inspection, bleeding.",
            120,
            4,
        ),
        TemplateNode(
            "auto-electrical",
            "knowledge",
            "Automotive Electrical Basics",
            "Battery testing, charging system, starting circuit, fuse diagnosis.",
            60,
            5,
        ),
        TemplateNode(
            "auto-obd",
            "technique",
            "OBD-II Diagnostics",
            "Scanner operation, DTC reading, freeze frame, live data.",
            60,
            6,
        ),
        TemplateNode(
            "auto-engine",
            "knowledge",
            "Engine Fundamentals",
            "Four-stroke cycle, timing, compression, fuel delivery, ignition.",
            90,
            7,
        ),
        TemplateNode(
            "auto-project1",
            "project",
            "Project: Full Brake Service",
            "Complete front and rear: pads, rotors, calipers, bleeding, test.",
            180,
            8,
        ),
        TemplateNode(
            "auto-project2",
            "project",
            "Project: Diagnose & Fix",
            "Use OBD-II and manual diagnostics to find and repair a real issue.",
            240,
            9,
        ),
        TemplateNode(
            "auto-cert",
            "certification_prep",
            "ASE Student Certification Prep",
            "ASE A-series practice tests. Study guide review.",
            120,
            10,
        ),
    ],
    edges=[
        TemplateEdge("auto-safety", "auto-oil"),
        TemplateEdge("auto-safety", "auto-tires"),
        TemplateEdge("auto-safety", "auto-brakes"),
        TemplateEdge("auto-systems", "auto-electrical"),
        TemplateEdge("auto-systems", "auto-engine"),
        TemplateEdge("auto-oil", "auto-tires"),
        TemplateEdge("auto-tires", "auto-brakes"),
        TemplateEdge("auto-electrical", "auto-obd"),
        TemplateEdge("auto-brakes", "auto-project1"),
        TemplateEdge("auto-obd", "auto-project2"),
        TemplateEdge("auto-engine", "auto-project2"),
        TemplateEdge("auto-project1", "auto-cert"),
        TemplateEdge("auto-project2", "auto-cert"),
    ],
)


# ── Template 7: Woodworking Fundamentals ──

WOODWORKING_FUNDAMENTALS = Template(
    template_id="woodworking-fundamentals",
    name="Woodworking Fundamentals",
    description="Hand and power tool skills from basic joinery through furniture.",
    subject_name="Woodworking",
    subject_color="#5D4037",
    nodes=[
        TemplateNode(
            "wood-safety",
            "safety",
            "Shop Safety & Hand Tool ID",
            "Tool safety, sharp tool handling, dust protection, clamp usage.",
            45,
            0,
        ),
        TemplateNode(
            "wood-measure",
            "technique",
            "Measuring, Marking & Layout",
            "Tape measure, combination square, marking gauge, knife lines.",
            45,
            1,
        ),
        TemplateNode(
            "wood-handsaw",
            "technique",
            "Hand Sawing",
            "Crosscut, rip cut, coping saw. Saw selection, sharpening basics.",
            60,
            2,
        ),
        TemplateNode(
            "wood-planes",
            "technique",
            "Planes & Chisels",
            "Block plane, smoothing plane, chisel technique. Water stones.",
            60,
            3,
        ),
        TemplateNode(
            "wood-joinery1",
            "technique",
            "Basic Joinery: Butt, Dado, Rabbet",
            "Butt joint, dado with router/saw, rabbet joint.",
            90,
            4,
        ),
        TemplateNode(
            "wood-power",
            "safety",
            "Power Tool Safety",
            "Circular saw, drill press, router, sander. Guards, push sticks.",
            60,
            5,
        ),
        TemplateNode(
            "wood-joinery2",
            "technique",
            "Intermediate Joinery: M&T, Dovetail",
            "Hand-cut mortise and tenon. Half-blind dovetails.",
            120,
            6,
        ),
        TemplateNode(
            "wood-finishing",
            "technique",
            "Finishing: Sand, Stain, Seal",
            "Sanding progression, stain application, polyurethane/oil finish.",
            60,
            7,
        ),
        TemplateNode(
            "wood-project1",
            "project",
            "Project: Cutting Board",
            "Edge-grain cutting board. Ripping, gluing, planing, food-safe finish.",
            120,
            8,
        ),
        TemplateNode(
            "wood-project2",
            "project",
            "Project: Small Table or Shelf",
            "Design, cut list, joinery, assembly, finishing.",
            240,
            9,
        ),
        TemplateNode(
            "wood-project3",
            "project",
            "Project: Furniture Piece",
            "Bookshelf, workbench, or cabinet. Complex joinery, hardware.",
            360,
            10,
        ),
    ],
    edges=[
        TemplateEdge("wood-safety", "wood-measure"),
        TemplateEdge("wood-safety", "wood-handsaw"),
        TemplateEdge("wood-safety", "wood-planes"),
        TemplateEdge("wood-measure", "wood-joinery1"),
        TemplateEdge("wood-handsaw", "wood-joinery1"),
        TemplateEdge("wood-planes", "wood-joinery1"),
        TemplateEdge("wood-safety", "wood-power"),
        TemplateEdge("wood-power", "wood-joinery2"),
        TemplateEdge("wood-joinery1", "wood-joinery2"),
        TemplateEdge("wood-joinery1", "wood-finishing"),
        TemplateEdge("wood-joinery1", "wood-project1"),
        TemplateEdge("wood-finishing", "wood-project1"),
        TemplateEdge("wood-joinery2", "wood-project2"),
        TemplateEdge("wood-project1", "wood-project2"),
        TemplateEdge("wood-project2", "wood-project3"),
    ],
)


# Registry
TEMPLATES: dict[str, Template] = {
    t.template_id: t
    for t in [
        MATH_FOUNDATIONAL,
        ELEMENTARY_CORE,
        CLASSICAL_LOGIC,
        WELDING_FUNDAMENTALS,
        ELECTRICAL_FUNDAMENTALS,
        AUTOMOTIVE_FUNDAMENTALS,
        WOODWORKING_FUNDAMENTALS,
    ]
}

# Side-effect registration of additional template libraries. Keep at the very
# bottom so TEMPLATES already exists when the imported module registers.
import app.services.art_templates  # noqa: E402
import app.services.fitness_templates  # noqa: E402, F401
