import Link from "next/link";
import { MetheanLogo } from "@/components/Brand";

const sections = [
  { id: "service", title: "Service Description" },
  { id: "accounts", title: "Account Responsibilities" },
  { id: "billing", title: "Subscription and Billing" },
  { id: "ai", title: "AI Limitations" },
  { id: "ownership", title: "Data Ownership" },
  { id: "use", title: "Acceptable Use" },
  { id: "ip", title: "Intellectual Property" },
  { id: "termination", title: "Termination" },
  { id: "liability", title: "Limitation of Liability" },
  { id: "law", title: "Governing Law" },
  { id: "contact", title: "Contact" },
];

function Section({ id, title, children }: { id: string; title: string; children: React.ReactNode }) {
  return (
    <section id={id} className="mb-10">
      <h2 className="text-[20px] font-semibold text-(--color-text) border-b border-(--color-border) pb-2 mb-4">{title}</h2>
      <div className="text-[15px] leading-relaxed text-(--color-text-secondary) space-y-3">{children}</div>
    </section>
  );
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-(--color-page)">
      <header className="border-b border-(--color-border) bg-(--color-surface)">
        <div className="max-w-[720px] mx-auto flex items-center justify-between h-14 px-6">
          <Link href="/"><MetheanLogo markSize={22} wordmarkHeight={11} color="#0F1B2D" gap={8} /></Link>
          <Link href="/" className="text-sm text-(--color-text-secondary) hover:text-(--color-text)">Back to home</Link>
        </div>
      </header>

      <main className="max-w-[720px] mx-auto px-6 py-12">
        <h1 className="text-[28px] font-bold text-(--color-text) mb-1">Terms of Service</h1>
        <p className="text-sm text-(--color-text-tertiary) mb-6">Effective April 2026</p>

        <div className="bg-(--color-brand-cream) rounded-[12px] p-5 mb-8 text-sm text-(--color-text-secondary) leading-relaxed">
          These terms are written in plain English. The legal intent is serious; the language is human.
        </div>

        <nav className="mb-10">
          <h3 className="text-xs font-semibold text-(--color-text-tertiary) uppercase tracking-wider mb-3">Contents</h3>
          <ol className="space-y-1">
            {sections.map((s, i) => (
              <li key={s.id}><a href={`#${s.id}`} className="text-sm text-(--color-accent) hover:underline">{i + 1}. {s.title}</a></li>
            ))}
          </ol>
        </nav>

        <Section id="service" title="1. Service Description">
          <p>METHEAN is a learning operating system for homeschool families. It provides AI-augmented curriculum planning, mastery tracking with FSRS spaced repetition, compliance management for all 50 states + DC, and parent governance tools.</p>
          <p>METHEAN is a tool for parents, not a replacement for parental judgment. Every AI recommendation passes through your governance rules before taking effect.</p>
        </Section>

        <Section id="accounts" title="2. Account Responsibilities">
          <p>You must be 18 or older to create an account. You are responsible for maintaining the confidentiality of your password and for all activity under your account.</p>
          <p>One subscription covers your entire household, including all children and co-parents you invite.</p>
        </Section>

        <Section id="billing" title="3. Subscription and Billing">
          <p>$99/month with a 14-day free trial. Payment is processed by Stripe. Your subscription renews automatically each month.</p>
          <p>Cancel anytime — access continues through the end of your current billing period. No refunds for partial months.</p>
        </Section>

        <Section id="ai" title="4. AI Limitations">
          <p>AI recommendations are generated by third-party language models (Anthropic Claude, OpenAI). AI output is <strong>advisory, not authoritative</strong>.</p>
          <p>METHEAN's governance system ensures all AI output is logged, parent-reviewable, and parent-approvable. AI may occasionally produce inaccurate or inappropriate content — the governance layer exists to catch this.</p>
          <p>METHEAN does not guarantee the accuracy of AI-generated educational content. You are the teacher. The AI is your instrument.</p>
        </Section>

        <Section id="ownership" title="5. Data Ownership">
          <p><strong>You own your data.</strong> METHEAN does not claim ownership of your children's learning records, curriculum maps, governance rules, or any other household data.</p>
          <p>You can export all data at any time via Settings → Export Data. Upon account deletion, all data is permanently removed within 90 days.</p>
        </Section>

        <Section id="use" title="6. Acceptable Use">
          <p>Do not use METHEAN to harm children. Do not attempt to bypass governance controls. Do not reverse-engineer the platform. Do not use the AI tutor for purposes unrelated to education. Do not share your account credentials.</p>
        </Section>

        <Section id="ip" title="7. Intellectual Property">
          <p>METHEAN's software, design, and brand are owned by Spartan Solutions. The educational content generated by AI for your household is yours to use, export, and share as you see fit.</p>
          <p>Pre-built curriculum templates and scope sequences are licensed for use within METHEAN only.</p>
        </Section>

        <Section id="termination" title="8. Termination">
          <p>Either party can terminate at any time. METHEAN may suspend accounts that violate these terms. Upon termination, data retention follows the <Link href="/privacy" className="text-(--color-accent) hover:underline">privacy policy</Link> (90 days).</p>
        </Section>

        <Section id="liability" title="9. Limitation of Liability">
          <p>METHEAN is provided "as is." Spartan Solutions is not liable for educational outcomes, compliance decisions made based on METHEAN's tools, or AI-generated content.</p>
          <p>Maximum liability is limited to fees paid in the 12 months preceding the claim.</p>
        </Section>

        <Section id="law" title="10. Governing Law">
          <p>These terms are governed by the laws of the State of Utah, United States.</p>
        </Section>

        <Section id="contact" title="11. Contact">
          <p>Zack Fava · <a href="mailto:zack@spartansolutions.co" className="text-(--color-accent) hover:underline">zack@spartansolutions.co</a> · Spartan Solutions</p>
        </Section>
      </main>

      <footer className="border-t border-(--color-border) py-8 px-6">
        <div className="max-w-[720px] mx-auto flex flex-col sm:flex-row items-center justify-between gap-4">
          <MetheanLogo markSize={18} wordmarkHeight={9} color="#9A9A9A" gap={6} />
          <div className="flex items-center gap-4 text-[12px] text-(--color-text-tertiary)">
            <Link href="/privacy" className="hover:underline">Privacy Policy</Link>
            <span>·</span>
            <span>© 2026 Spartan Solutions</span>
          </div>
        </div>
      </footer>
    </div>
  );
}
