"""Pre-enriched content for Mathematics Foundational template nodes."""

MATH_FOUNDATIONAL_CONTENT = {
    "mf-01": {
        "enriched": True,
        "learning_objectives": ["Count objects to 20 with one-to-one correspondence", "Recognize and write numerals 0-20", "Count forward and backward from any number within 20", "Answer 'how many' questions after counting a set"],
        "teaching_guidance": {
            "introduction": "Begin with physical objects the child can touch and move: blocks, buttons, coins, or natural objects like acorns. Counting is a physical activity before it is an abstract one. Have the child touch each object as they say the number aloud.",
            "scaffolding_sequence": ["Count collections of 5 objects, touching each one", "Count collections of 10, grouping into fives", "Count collections of 15, grouping into fives and tens", "Count to 20 objects, then count backward from 20", "Match numeral cards to collections of objects", "Write numerals 0-20 from memory"],
            "socratic_questions": ["How do you know you counted every one?", "If I add one more, how many will there be?", "What number comes just before 15?", "Can you show me 12 with your blocks?"],
            "practice_activities": ["Count items during a nature walk and record the total", "Play counting games: hide objects and count to find them all", "Sort a collection and count each group separately"],
            "real_world_connections": ["Counting items at the grocery store", "Counting steps on a staircase", "Setting the table: one plate for each person"],
            "common_misconceptions": ["Skipping objects or counting the same object twice", "Confusing the last number with a label rather than the total", "Believing that rearranging objects changes the count"],
        },
        "assessment_criteria": {
            "mastery_indicators": ["Counts 20 objects accurately with 1:1 correspondence every time", "Writes numerals 0-20 without a model", "Counts backward from any number within 20"],
            "assessment_methods": ["oral counting", "object counting", "numeral writing"],
            "sample_assessment_prompts": ["Count these 18 buttons, touching each one", "Write the numbers from 0 to 20", "Start at 14 and count backward to 1"],
        },
        "practice_items": [
            {"type": "problem", "difficulty": 1, "prompt": "Count the stars: \u2b50\u2b50\u2b50\u2b50\u2b50\u2b50\u2b50 How many are there?", "expected_type": "number", "correct_answer": "7", "hints": ["Touch each star as you count it", "Start from the left and go to the right"], "explanation": "There are 7 stars. Counting each one: 1, 2, 3, 4, 5, 6, 7."},
            {"type": "problem", "difficulty": 1, "prompt": "What number comes after 9?", "expected_type": "number", "correct_answer": "10", "hints": ["Count: 7, 8, 9, ..."], "explanation": "After 9 comes 10."},
            {"type": "problem", "difficulty": 1, "prompt": "What number comes before 6?", "expected_type": "number", "correct_answer": "5", "hints": ["Count backward: 8, 7, 6, ..."], "explanation": "Before 6 is 5."},
            {"type": "problem", "difficulty": 2, "prompt": "Count backward from 12 to 7. What numbers did you say?", "expected_type": "text", "hints": ["Start at 12 and go down one at a time"], "explanation": "12, 11, 10, 9, 8, 7"},
            {"type": "problem", "difficulty": 2, "prompt": "I have 13 blocks. I get 1 more. How many do I have now?", "expected_type": "number", "correct_answer": "14", "hints": ["Start at 13 and count one more"], "explanation": "13 + 1 = 14. When you add one more to 13, you get 14."},
            {"type": "problem", "difficulty": 2, "prompt": "What number is between 15 and 17?", "expected_type": "number", "correct_answer": "16", "hints": ["Count: 15, ?, 17"], "explanation": "16 is between 15 and 17."},
            {"type": "problem", "difficulty": 3, "prompt": "Start at 4 and count to 19. How many numbers did you say?", "expected_type": "number", "correct_answer": "16", "hints": ["Count each one: 4, 5, 6, ... all the way to 19", "You can count on your fingers or use tally marks"], "explanation": "From 4 to 19 is 16 numbers: 4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19."},
            {"type": "problem", "difficulty": 3, "prompt": "Write the even numbers from 2 to 20.", "expected_type": "text", "hints": ["Even numbers: 2, 4, 6, ..."], "explanation": "2, 4, 6, 8, 10, 12, 14, 16, 18, 20"},
        ],
        "assessment_items": [
            {"prompt": "Count these objects and write the number: \U0001f535\U0001f535\U0001f535\U0001f535\U0001f535\U0001f535\U0001f535\U0001f535\U0001f535\U0001f535\U0001f535\U0001f535\U0001f535\U0001f535\U0001f535", "type": "number", "correct_answer": "15", "target_concept": "counting_to_20"},
            {"prompt": "Start at 20 and count backward to 10.", "type": "text", "rubric": "Mastery: counts 20,19,18...10 without errors. Proficient: one self-correction. Developing: needs help beyond 15.", "target_concept": "backward_counting"},
            {"prompt": "Write the numeral for 'seventeen'.", "type": "number", "correct_answer": "17", "target_concept": "numeral_writing"},
            {"prompt": "What is the number that is one more than 18?", "type": "number", "correct_answer": "19", "target_concept": "one_more"},
            {"prompt": "How do you know you counted every object without skipping any?", "type": "open_response", "rubric": "Mastery: explains touching each one and counting in order. Proficient: mentions being careful. Developing: cannot explain strategy.", "target_concept": "counting_strategy"},
        ],
        "resource_guidance": {"required": ["counting objects", "numeral cards 0-20"], "recommended": ["number line", "ten-frame boards"]},
        "time_estimates": {"first_exposure": 20, "practice_session": 15, "assessment": 10},
    },
    "mf-02": {
        "enriched": True,
        "learning_objectives": ["Identify and read numerals from 0 to 100", "Understand the difference between a number and a numeral", "Begin to understand place value conceptually"],
        "teaching_guidance": {
            "introduction": "Numbers are ideas. Numerals are the symbols we write to represent those ideas. The numeral '5' represents the idea of five things. Now we extend from 20 all the way to 100. Use a hundred chart as a visual anchor.",
            "scaffolding_sequence": ["Read numerals 0-50 from a hundred chart", "Read numerals 51-100", "Point to any named numeral on the chart", "Write numerals to 50 from memory", "Identify numerals in real-world contexts (addresses, prices, page numbers)"],
            "socratic_questions": ["What patterns do you see in the hundred chart?", "What changes when we go from 19 to 20?", "If I cover up a number, can you figure out what it is from the numbers around it?"],
            "practice_activities": ["Hundred chart puzzles: fill in missing numbers", "Number scavenger hunt: find numbers in books, signs, and packages", "Write numbers from 1 to 50 as fast as you can"],
            "real_world_connections": ["House numbers on your street", "Page numbers in a book", "Prices at a store"],
            "common_misconceptions": ["Reversing digits: writing 31 as 13", "Not understanding that 40 means 'four tens'", "Thinking numbers end at some point"],
        },
        "assessment_criteria": {
            "mastery_indicators": ["Reads any numeral 0-100 on sight", "Points to correct numeral when given orally", "Writes numerals to 50 from memory"],
            "assessment_methods": ["numeral identification", "hundred chart activities", "numeral writing"],
            "sample_assessment_prompts": ["Read these numbers: 47, 82, 15, 63, 90", "Write the number sixty-three", "Point to 78 on the hundred chart"],
        },
        "practice_items": [
            {"type": "problem", "difficulty": 1, "prompt": "What number is this: 25?", "expected_type": "text", "correct_answer": "twenty-five", "hints": ["The 2 means two tens, the 5 means five ones"], "explanation": "25 is read as twenty-five."},
            {"type": "problem", "difficulty": 1, "prompt": "Write the numeral for 'thirty-four'.", "expected_type": "number", "correct_answer": "34", "hints": ["Thirty means 3 tens, four means 4 ones"], "explanation": "Thirty-four is written as 34."},
            {"type": "problem", "difficulty": 2, "prompt": "What number comes right after 49?", "expected_type": "number", "correct_answer": "50", "hints": ["Count: 47, 48, 49, ..."], "explanation": "After 49 comes 50."},
            {"type": "problem", "difficulty": 2, "prompt": "What number is 10 more than 35?", "expected_type": "number", "correct_answer": "45", "hints": ["On the hundred chart, go down one row"], "explanation": "35 + 10 = 45. Adding 10 changes the tens digit by 1."},
            {"type": "problem", "difficulty": 3, "prompt": "Write all the numbers from 88 to 100.", "expected_type": "text", "hints": ["Start at 88 and keep counting"], "explanation": "88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100"},
        ],
        "assessment_items": [
            {"prompt": "Read this number: 76", "type": "text", "correct_answer": "seventy-six", "target_concept": "numeral_reading"},
            {"prompt": "Write the numeral for 'ninety-one'.", "type": "number", "correct_answer": "91", "target_concept": "numeral_writing"},
            {"prompt": "What number is between 59 and 61?", "type": "number", "correct_answer": "60", "target_concept": "number_sequence"},
        ],
        "resource_guidance": {"required": ["hundred chart", "numeral cards"], "recommended": ["number line to 100"]},
        "time_estimates": {"first_exposure": 20, "practice_session": 15, "assessment": 10},
    },
    "mf-03": {
        "enriched": True,
        "learning_objectives": ["Demonstrate one-to-one correspondence when counting", "Understand that each object gets exactly one count", "Recognize that the last number said represents the total", "Understand that counting order does not change the total"],
        "teaching_guidance": {
            "introduction": "One-to-one correspondence means each object gets exactly one number. The child touches, moves, or points to each object as they say one number. This is the bridge between reciting numbers and actually counting.",
            "scaffolding_sequence": ["Line up 5 objects and touch each while counting", "Count scattered objects by moving each to a counted pile", "Count objects in a circle without losing track", "Count the same group arranged differently to prove the total stays the same"],
            "socratic_questions": ["How can you make sure you don't count any twice?", "What if we move these blocks around, will the number change?", "Why did you touch each one as you counted?"],
            "practice_activities": ["Count a jar of buttons by moving each to a new pile", "Count steps as you walk across the room"],
            "real_world_connections": ["Passing out one napkin per person at dinner", "Giving one treat to each pet"],
            "common_misconceptions": ["Saying numbers faster than pointing", "Counting an object twice because it wasn't moved aside", "Thinking a spread-out group has more than a bunched-up group"],
        },
        "assessment_criteria": {
            "mastery_indicators": ["Counts 15 scattered objects without double-counting or skipping", "Explains that rearranging objects doesn't change the count"],
            "assessment_methods": ["object counting", "observation", "oral explanation"],
            "sample_assessment_prompts": ["Count these 12 scattered buttons", "If I spread these out more, will there be more?"],
        },
        "practice_items": [
            {"type": "problem", "difficulty": 1, "prompt": "Count the dots: * * * * * How many?", "expected_type": "number", "correct_answer": "5", "hints": ["Point to each dot as you count"], "explanation": "There are 5 dots."},
            {"type": "problem", "difficulty": 1, "prompt": "You have 8 blocks in a line. You push them into a pile. How many blocks are in the pile?", "expected_type": "number", "correct_answer": "8", "hints": ["Did you add or remove any blocks?"], "explanation": "Still 8. Moving objects doesn't change the count."},
            {"type": "problem", "difficulty": 2, "prompt": "Sam counted 10 apples. Someone moved them closer together. Sam counted again and got 8. What went wrong?", "expected_type": "text", "hints": ["Did the number of apples change?"], "explanation": "Sam probably skipped some. Moving objects doesn't change the count. Sam should touch each apple."},
            {"type": "problem", "difficulty": 3, "prompt": "You have 14 objects in a circle. How would you count them without counting any twice?", "expected_type": "text", "hints": ["Think about marking your starting point"], "explanation": "Start at one object and mark it. Count around until you get back to the marked one."},
        ],
        "assessment_items": [
            {"prompt": "Count these 11 scattered objects.", "type": "number", "correct_answer": "11", "target_concept": "one_to_one"},
            {"prompt": "If I spread 7 blocks far apart, how many are there?", "type": "number", "correct_answer": "7", "target_concept": "conservation"},
            {"prompt": "Show me your strategy for counting without missing any.", "type": "open_response", "rubric": "Mastery: describes moving or marking objects. Proficient: demonstrates a strategy. Developing: no clear strategy.", "target_concept": "counting_strategy"},
        ],
        "resource_guidance": {"required": ["small counting objects"], "recommended": ["sorting trays"]},
        "time_estimates": {"first_exposure": 15, "practice_session": 10, "assessment": 10},
    },
    "mf-04": {
        "enriched": True,
        "learning_objectives": ["Count to 100 by ones fluently", "Count by tens to 100", "Count forward from any given number within 100", "Understand the repeating pattern of tens"],
        "teaching_guidance": {
            "introduction": "Counting to 100 is the child's first encounter with the structure of our base-ten system. The pattern repeats every ten: 21,22,23...29,30. Use a hundred chart so the child can SEE the pattern.",
            "scaffolding_sequence": ["Count from 1 to 30, then 1 to 50, building up", "Use a hundred chart and point to each number", "Practice hard transitions: 29-30, 39-40, 49-50", "Count by 10s: 10, 20, 30...100", "Count forward from a random starting point"],
            "socratic_questions": ["What pattern do you notice after every 9?", "If you're at 57, what comes next?", "What's the same about 23, 33, 43, 53?"],
            "practice_activities": ["Hundred chart coloring: color every 5th number", "Count to 100 while doing jumping jacks", "Hundred chart puzzles: cut apart and reassemble"],
            "real_world_connections": ["Counting pennies to make a dollar", "Days of school on a hundred chart"],
            "common_misconceptions": ["Stalling at decade transitions", "Confusing teens and tens (13 vs 30)", "Thinking you must start at 1"],
        },
        "assessment_criteria": {
            "mastery_indicators": ["Counts to 100 without hesitation at transitions", "Counts by tens to 100 fluently", "Counts forward from any number to 100"],
            "assessment_methods": ["oral counting", "hundred chart completion"],
            "sample_assessment_prompts": ["Count from 1 to 100", "Count by tens", "Start at 46 and count to 70"],
        },
        "practice_items": [
            {"type": "problem", "difficulty": 1, "prompt": "Count by tens: 10, 20, 30, __, __, __", "expected_type": "text", "correct_answer": "40, 50, 60", "hints": ["Add 10 each time"], "explanation": "40, 50, 60."},
            {"type": "problem", "difficulty": 1, "prompt": "What number comes after 29?", "expected_type": "number", "correct_answer": "30", "hints": ["After 29, a new group of ten starts"], "explanation": "After 29 comes 30."},
            {"type": "problem", "difficulty": 2, "prompt": "Start at 55 and count to 65.", "expected_type": "text", "correct_answer": "55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65", "hints": ["Watch the transition from 59 to 60"], "explanation": "55 through 65, including the 59-60 transition."},
            {"type": "problem", "difficulty": 3, "prompt": "Start at 87 and count to 100. How many numbers did you say?", "expected_type": "number", "correct_answer": "14", "hints": ["Count from 87 through 100 on your fingers"], "explanation": "87 through 100 is 14 numbers."},
        ],
        "assessment_items": [
            {"prompt": "Count from 38 to 52.", "type": "text", "rubric": "Mastery: fluent. Proficient: one pause. Developing: stumbles at transitions.", "target_concept": "counting_to_100"},
            {"prompt": "What number comes after 99?", "type": "number", "correct_answer": "100", "target_concept": "counting_to_100"},
            {"prompt": "Count by tens from 10 to 100.", "type": "text", "correct_answer": "10, 20, 30, 40, 50, 60, 70, 80, 90, 100", "target_concept": "skip_counting_tens"},
        ],
        "resource_guidance": {"required": ["hundred chart"], "recommended": ["number line to 100"]},
        "time_estimates": {"first_exposure": 20, "practice_session": 15, "assessment": 10},
    },
    "mf-05": {
        "enriched": True,
        "learning_objectives": ["Recall all addition combinations within 10", "Demonstrate addition with manipulatives", "Write addition number sentences", "Solve missing addend problems within 10"],
        "teaching_guidance": {
            "introduction": "Addition means putting groups together. Start with objects: 'I have 3 blocks and you have 4. Put them together, how many?' Let the child discover by counting the combined group.",
            "scaffolding_sequence": ["Combine two groups and count the total", "Introduce + and = symbols alongside manipulatives", "Practice doubles: 1+1, 2+2, 3+3, 4+4, 5+5", "Practice near-doubles: 3+4 is one more than 3+3", "Practice make-ten for facts near 10", "Build recall through games, not timed tests"],
            "socratic_questions": ["If you have 5 and get 3 more, how could you find the total?", "You know 4+4=8. What would 4+5 be?", "Is 3+5 the same as 5+3? How could you check?"],
            "practice_activities": ["Roll two dice and add", "Number line hopping forward", "Card game war: flip two, add, highest sum wins"],
            "real_world_connections": ["Adding coins", "Combining groups of snacks", "Scoring in games"],
            "common_misconceptions": ["Counting from 1 instead of counting on", "Not understanding commutativity", "Counting the starting number in count-on"],
        },
        "assessment_criteria": {
            "mastery_indicators": ["Recalls any fact to 10 within 3 seconds", "Writes correct number sentences", "Solves missing addend: __ + 4 = 7"],
            "assessment_methods": ["oral recall", "manipulative demo", "written sentences"],
            "sample_assessment_prompts": ["What is 6+3?", "Show 4+5 with blocks", "What goes in the blank: __ + 3 = 8?"],
        },
        "practice_items": [
            {"type": "problem", "difficulty": 1, "prompt": "What is 3 + 2?", "expected_type": "number", "correct_answer": "5", "hints": ["Start with 3, count up 2"], "explanation": "3 + 2 = 5."},
            {"type": "problem", "difficulty": 1, "prompt": "What is 5 + 5?", "expected_type": "number", "correct_answer": "10", "hints": ["Doubles fact"], "explanation": "5 + 5 = 10."},
            {"type": "problem", "difficulty": 2, "prompt": "What is 4 + 5?", "expected_type": "number", "correct_answer": "9", "hints": ["4+4=8, so 4+5 is one more"], "explanation": "4 + 5 = 9."},
            {"type": "problem", "difficulty": 2, "prompt": "Fill in: __ + 4 = 9", "expected_type": "number", "correct_answer": "5", "hints": ["What plus 4 equals 9?"], "explanation": "5 + 4 = 9."},
            {"type": "problem", "difficulty": 3, "prompt": "How many ways can you make 8 with two numbers?", "expected_type": "text", "hints": ["Start with 0+8, then 1+7..."], "explanation": "0+8, 1+7, 2+6, 3+5, 4+4, 5+3, 6+2, 7+1, 8+0."},
        ],
        "assessment_items": [
            {"prompt": "What is 7 + 2?", "type": "number", "correct_answer": "9", "target_concept": "addition_facts"},
            {"prompt": "Fill in: __ + 6 = 10", "type": "number", "correct_answer": "4", "target_concept": "missing_addend"},
            {"prompt": "What is 5 + 4? Explain your strategy.", "type": "open_response", "rubric": "Mastery: correct (9) with strategy. Proficient: correct, vague strategy. Developing: incorrect.", "target_concept": "addition_strategy"},
        ],
        "resource_guidance": {"required": ["counting manipulatives", "number line"], "recommended": ["dice", "playing cards", "ten-frames"]},
        "time_estimates": {"first_exposure": 25, "practice_session": 15, "assessment": 10},
    },
}
