"""Pre-enriched content for Mathematics Foundational template nodes."""

MATH_FOUNDATIONAL_CONTENT = {
    "mf-01": {
        "enriched": True,
        "learning_objectives": ["Count objects to 20 with one-to-one correspondence", "Recognize and write numerals 0-20", "Count forward and backward from any number within 20", "Answer 'how many' questions after counting a set"],
        "teaching_guidance": {
            "introduction": "Begin with physical objects the child can touch and move: blocks, buttons, coins, or natural objects like acorns. Counting is a physical activity before it is an abstract one. Have the child touch each object as they say the number aloud.",
            "scaffolding_sequence": ["Count collections of 5 objects, touching each one", "Count collections of 10, grouping into fives", "Count collections of 15, grouping into fives and tens", "Count to 20 objects, then count backward from 20", "Match numeral cards to collections of objects", "Write numerals 0-20 from memory"],
            "socratic_questions": ["How do you know you counted every one?", "If I add one more, how many will there be?", "What number comes just before 15?", "Can you show me 12 with your blocks?"],
            "practice_activities": ["Count items during a nature walk and record the total", "Play counting games: hide objects and count to find them all", "Sort a collection and count each group separately"],
            "real_world_connections": ["Counting items at the grocery store", "Counting steps on a staircase", "Setting the table: one plate for each person"],
            "common_misconceptions": ["Skipping objects or counting the same object twice", "Confusing the last number with a label rather than the total", "Believing that rearranging objects changes the count"],
        },
        "assessment_criteria": {
            "mastery_indicators": ["Counts 20 objects accurately with 1:1 correspondence every time", "Writes numerals 0-20 without a model", "Counts backward from any number within 20"],
            "assessment_methods": ["oral counting", "object counting", "numeral writing"],
            "sample_assessment_prompts": ["Count these 18 buttons, touching each one", "Write the numbers from 0 to 20", "Start at 14 and count backward to 1"],
        },
        "practice_items": [
            {"type": "problem", "difficulty": 1, "prompt": "Count the stars: \u2b50\u2b50\u2b50\u2b50\u2b50\u2b50\u2b50 How many are there?", "expected_type": "number", "correct_answer": "7", "hints": ["Touch each star as you count it", "Start from the left and go to the right"], "explanation": "There are 7 stars. Counting each one: 1, 2, 3, 4, 5, 6, 7."},
            {"type": "problem", "difficulty": 1, "prompt": "What number comes after 9?", "expected_type": "number", "correct_answer": "10", "hints": ["Count: 7, 8, 9, ..."], "explanation": "After 9 comes 10."},
            {"type": "problem", "difficulty": 1, "prompt": "What number comes before 6?", "expected_type": "number", "correct_answer": "5", "hints": ["Count backward: 8, 7, 6, ..."], "explanation": "Before 6 is 5."},
            {"type": "problem", "difficulty": 2, "prompt": "Count backward from 12 to 7. What numbers did you say?", "expected_type": "text", "hints": ["Start at 12 and go down one at a time"], "explanation": "12, 11, 10, 9, 8, 7"},
            {"type": "problem", "difficulty": 2, "prompt": "I have 13 blocks. I get 1 more. How many do I have now?", "expected_type": "number", "correct_answer": "14", "hints": ["Start at 13 and count one more"], "explanation": "13 + 1 = 14. When you add one more to 13, you get 14."},
            {"type": "problem", "difficulty": 2, "prompt": "What number is between 15 and 17?", "expected_type": "number", "correct_answer": "16", "hints": ["Count: 15, ?, 17"], "explanation": "16 is between 15 and 17."},
            {"type": "problem", "difficulty": 3, "prompt": "Start at 4 and count to 19. How many numbers did you say?", "expected_type": "number", "correct_answer": "16", "hints": ["Count each one: 4, 5, 6, ... all the way to 19", "You can count on your fingers or use tally marks"], "explanation": "From 4 to 19 is 16 numbers: 4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19."},
            {"type": "problem", "difficulty": 3, "prompt": "Write the even numbers from 2 to 20.", "expected_type": "text", "hints": ["Even numbers: 2, 4, 6, ..."], "explanation": "2, 4, 6, 8, 10, 12, 14, 16, 18, 20"},
        ],
        "assessment_items": [
            {"prompt": "Count these objects and write the number: \U0001f535\U0001f535\U0001f535\U0001f535\U0001f535\U0001f535\U0001f535\U0001f535\U0001f535\U0001f535\U0001f535\U0001f535\U0001f535\U0001f535\U0001f535", "type": "number", "correct_answer": "15", "target_concept": "counting_to_20"},
            {"prompt": "Start at 20 and count backward to 10.", "type": "text", "rubric": "Mastery: counts 20,19,18...10 without errors. Proficient: one self-correction. Developing: needs help beyond 15.", "target_concept": "backward_counting"},
            {"prompt": "Write the numeral for 'seventeen'.", "type": "number", "correct_answer": "17", "target_concept": "numeral_writing"},
            {"prompt": "What is the number that is one more than 18?", "type": "number", "correct_answer": "19", "target_concept": "one_more"},
            {"prompt": "How do you know you counted every object without skipping any?", "type": "open_response", "rubric": "Mastery: explains touching each one and counting in order. Proficient: mentions being careful. Developing: cannot explain strategy.", "target_concept": "counting_strategy"},
        ],
        "resource_guidance": {"required": ["counting objects", "numeral cards 0-20"], "recommended": ["number line", "ten-frame boards"]},
        "time_estimates": {"first_exposure": 20, "practice_session": 15, "assessment": 10},
    },
    "mf-02": {
        "enriched": True,
        "learning_objectives": ["Identify and read numerals from 0 to 100", "Understand the difference between a number and a numeral", "Begin to understand place value conceptually"],
        "teaching_guidance": {
            "introduction": "Numbers are ideas. Numerals are the symbols we write to represent those ideas. The numeral '5' represents the idea of five things. Now we extend from 20 all the way to 100. Use a hundred chart as a visual anchor.",
            "scaffolding_sequence": ["Read numerals 0-50 from a hundred chart", "Read numerals 51-100", "Point to any named numeral on the chart", "Write numerals to 50 from memory", "Identify numerals in real-world contexts (addresses, prices, page numbers)"],
            "socratic_questions": ["What patterns do you see in the hundred chart?", "What changes when we go from 19 to 20?", "If I cover up a number, can you figure out what it is from the numbers around it?"],
            "practice_activities": ["Hundred chart puzzles: fill in missing numbers", "Number scavenger hunt: find numbers in books, signs, and packages", "Write numbers from 1 to 50 as fast as you can"],
            "real_world_connections": ["House numbers on your street", "Page numbers in a book", "Prices at a store"],
            "common_misconceptions": ["Reversing digits: writing 31 as 13", "Not understanding that 40 means 'four tens'", "Thinking numbers end at some point"],
        },
        "assessment_criteria": {
            "mastery_indicators": ["Reads any numeral 0-100 on sight", "Points to correct numeral when given orally", "Writes numerals to 50 from memory"],
            "assessment_methods": ["numeral identification", "hundred chart activities", "numeral writing"],
            "sample_assessment_prompts": ["Read these numbers: 47, 82, 15, 63, 90", "Write the number sixty-three", "Point to 78 on the hundred chart"],
        },
        "practice_items": [
            {"type": "problem", "difficulty": 1, "prompt": "What number is this: 25?", "expected_type": "text", "correct_answer": "twenty-five", "hints": ["The 2 means two tens, the 5 means five ones"], "explanation": "25 is read as twenty-five."},
            {"type": "problem", "difficulty": 1, "prompt": "Write the numeral for 'thirty-four'.", "expected_type": "number", "correct_answer": "34", "hints": ["Thirty means 3 tens, four means 4 ones"], "explanation": "Thirty-four is written as 34."},
            {"type": "problem", "difficulty": 2, "prompt": "What number comes right after 49?", "expected_type": "number", "correct_answer": "50", "hints": ["Count: 47, 48, 49, ..."], "explanation": "After 49 comes 50."},
            {"type": "problem", "difficulty": 2, "prompt": "What number is 10 more than 35?", "expected_type": "number", "correct_answer": "45", "hints": ["On the hundred chart, go down one row"], "explanation": "35 + 10 = 45. Adding 10 changes the tens digit by 1."},
            {"type": "problem", "difficulty": 3, "prompt": "Write all the numbers from 88 to 100.", "expected_type": "text", "hints": ["Start at 88 and keep counting"], "explanation": "88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100"},
        ],
        "assessment_items": [
            {"prompt": "Read this number: 76", "type": "text", "correct_answer": "seventy-six", "target_concept": "numeral_reading"},
            {"prompt": "Write the numeral for 'ninety-one'.", "type": "number", "correct_answer": "91", "target_concept": "numeral_writing"},
            {"prompt": "What number is between 59 and 61?", "type": "number", "correct_answer": "60", "target_concept": "number_sequence"},
        ],
        "resource_guidance": {"required": ["hundred chart", "numeral cards"], "recommended": ["number line to 100"]},
        "time_estimates": {"first_exposure": 20, "practice_session": 15, "assessment": 10},
    },
    "mf-03": {
        "enriched": True,
        "learning_objectives": ["Demonstrate one-to-one correspondence when counting", "Understand that each object gets exactly one count", "Recognize that the last number said represents the total", "Understand that counting order does not change the total"],
        "teaching_guidance": {
            "introduction": "One-to-one correspondence means each object gets exactly one number. The child touches, moves, or points to each object as they say one number. This is the bridge between reciting numbers and actually counting.",
            "scaffolding_sequence": ["Line up 5 objects and touch each while counting", "Count scattered objects by moving each to a counted pile", "Count objects in a circle without losing track", "Count the same group arranged differently to prove the total stays the same"],
            "socratic_questions": ["How can you make sure you don't count any twice?", "What if we move these blocks around, will the number change?", "Why did you touch each one as you counted?"],
            "practice_activities": ["Count a jar of buttons by moving each to a new pile", "Count steps as you walk across the room"],
            "real_world_connections": ["Passing out one napkin per person at dinner", "Giving one treat to each pet"],
            "common_misconceptions": ["Saying numbers faster than pointing", "Counting an object twice because it wasn't moved aside", "Thinking a spread-out group has more than a bunched-up group"],
        },
        "assessment_criteria": {
            "mastery_indicators": ["Counts 15 scattered objects without double-counting or skipping", "Explains that rearranging objects doesn't change the count"],
            "assessment_methods": ["object counting", "observation", "oral explanation"],
            "sample_assessment_prompts": ["Count these 12 scattered buttons", "If I spread these out more, will there be more?"],
        },
        "practice_items": [
            {"type": "problem", "difficulty": 1, "prompt": "Count the dots: * * * * * How many?", "expected_type": "number", "correct_answer": "5", "hints": ["Point to each dot as you count"], "explanation": "There are 5 dots."},
            {"type": "problem", "difficulty": 1, "prompt": "You have 8 blocks in a line. You push them into a pile. How many blocks are in the pile?", "expected_type": "number", "correct_answer": "8", "hints": ["Did you add or remove any blocks?"], "explanation": "Still 8. Moving objects doesn't change the count."},
            {"type": "problem", "difficulty": 2, "prompt": "Sam counted 10 apples. Someone moved them closer together. Sam counted again and got 8. What went wrong?", "expected_type": "text", "hints": ["Did the number of apples change?"], "explanation": "Sam probably skipped some. Moving objects doesn't change the count. Sam should touch each apple."},
            {"type": "problem", "difficulty": 3, "prompt": "You have 14 objects in a circle. How would you count them without counting any twice?", "expected_type": "text", "hints": ["Think about marking your starting point"], "explanation": "Start at one object and mark it. Count around until you get back to the marked one."},
        ],
        "assessment_items": [
            {"prompt": "Count these 11 scattered objects.", "type": "number", "correct_answer": "11", "target_concept": "one_to_one"},
            {"prompt": "If I spread 7 blocks far apart, how many are there?", "type": "number", "correct_answer": "7", "target_concept": "conservation"},
            {"prompt": "Show me your strategy for counting without missing any.", "type": "open_response", "rubric": "Mastery: describes moving or marking objects. Proficient: demonstrates a strategy. Developing: no clear strategy.", "target_concept": "counting_strategy"},
        ],
        "resource_guidance": {"required": ["small counting objects"], "recommended": ["sorting trays"]},
        "time_estimates": {"first_exposure": 15, "practice_session": 10, "assessment": 10},
    },
    "mf-04": {
        "enriched": True,
        "learning_objectives": ["Count to 100 by ones fluently", "Count by tens to 100", "Count forward from any given number within 100", "Understand the repeating pattern of tens"],
        "teaching_guidance": {
            "introduction": "Counting to 100 is the child's first encounter with the structure of our base-ten system. The pattern repeats every ten: 21,22,23...29,30. Use a hundred chart so the child can SEE the pattern.",
            "scaffolding_sequence": ["Count from 1 to 30, then 1 to 50, building up", "Use a hundred chart and point to each number", "Practice hard transitions: 29-30, 39-40, 49-50", "Count by 10s: 10, 20, 30...100", "Count forward from a random starting point"],
            "socratic_questions": ["What pattern do you notice after every 9?", "If you're at 57, what comes next?", "What's the same about 23, 33, 43, 53?"],
            "practice_activities": ["Hundred chart coloring: color every 5th number", "Count to 100 while doing jumping jacks", "Hundred chart puzzles: cut apart and reassemble"],
            "real_world_connections": ["Counting pennies to make a dollar", "Days of school on a hundred chart"],
            "common_misconceptions": ["Stalling at decade transitions", "Confusing teens and tens (13 vs 30)", "Thinking you must start at 1"],
        },
        "assessment_criteria": {
            "mastery_indicators": ["Counts to 100 without hesitation at transitions", "Counts by tens to 100 fluently", "Counts forward from any number to 100"],
            "assessment_methods": ["oral counting", "hundred chart completion"],
            "sample_assessment_prompts": ["Count from 1 to 100", "Count by tens", "Start at 46 and count to 70"],
        },
        "practice_items": [
            {"type": "problem", "difficulty": 1, "prompt": "Count by tens: 10, 20, 30, __, __, __", "expected_type": "text", "correct_answer": "40, 50, 60", "hints": ["Add 10 each time"], "explanation": "40, 50, 60."},
            {"type": "problem", "difficulty": 1, "prompt": "What number comes after 29?", "expected_type": "number", "correct_answer": "30", "hints": ["After 29, a new group of ten starts"], "explanation": "After 29 comes 30."},
            {"type": "problem", "difficulty": 2, "prompt": "Start at 55 and count to 65.", "expected_type": "text", "correct_answer": "55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65", "hints": ["Watch the transition from 59 to 60"], "explanation": "55 through 65, including the 59-60 transition."},
            {"type": "problem", "difficulty": 3, "prompt": "Start at 87 and count to 100. How many numbers did you say?", "expected_type": "number", "correct_answer": "14", "hints": ["Count from 87 through 100 on your fingers"], "explanation": "87 through 100 is 14 numbers."},
        ],
        "assessment_items": [
            {"prompt": "Count from 38 to 52.", "type": "text", "rubric": "Mastery: fluent. Proficient: one pause. Developing: stumbles at transitions.", "target_concept": "counting_to_100"},
            {"prompt": "What number comes after 99?", "type": "number", "correct_answer": "100", "target_concept": "counting_to_100"},
            {"prompt": "Count by tens from 10 to 100.", "type": "text", "correct_answer": "10, 20, 30, 40, 50, 60, 70, 80, 90, 100", "target_concept": "skip_counting_tens"},
        ],
        "resource_guidance": {"required": ["hundred chart"], "recommended": ["number line to 100"]},
        "time_estimates": {"first_exposure": 20, "practice_session": 15, "assessment": 10},
    },
    "mf-05": {
        "enriched": True,
        "learning_objectives": ["Recall all addition combinations within 10", "Demonstrate addition with manipulatives", "Write addition number sentences", "Solve missing addend problems within 10"],
        "teaching_guidance": {
            "introduction": "Addition means putting groups together. Start with objects: 'I have 3 blocks and you have 4. Put them together, how many?' Let the child discover by counting the combined group.",
            "scaffolding_sequence": ["Combine two groups and count the total", "Introduce + and = symbols alongside manipulatives", "Practice doubles: 1+1, 2+2, 3+3, 4+4, 5+5", "Practice near-doubles: 3+4 is one more than 3+3", "Practice make-ten for facts near 10", "Build recall through games, not timed tests"],
            "socratic_questions": ["If you have 5 and get 3 more, how could you find the total?", "You know 4+4=8. What would 4+5 be?", "Is 3+5 the same as 5+3? How could you check?"],
            "practice_activities": ["Roll two dice and add", "Number line hopping forward", "Card game war: flip two, add, highest sum wins"],
            "real_world_connections": ["Adding coins", "Combining groups of snacks", "Scoring in games"],
            "common_misconceptions": ["Counting from 1 instead of counting on", "Not understanding commutativity", "Counting the starting number in count-on"],
        },
        "assessment_criteria": {
            "mastery_indicators": ["Recalls any fact to 10 within 3 seconds", "Writes correct number sentences", "Solves missing addend: __ + 4 = 7"],
            "assessment_methods": ["oral recall", "manipulative demo", "written sentences"],
            "sample_assessment_prompts": ["What is 6+3?", "Show 4+5 with blocks", "What goes in the blank: __ + 3 = 8?"],
        },
        "practice_items": [
            {"type": "problem", "difficulty": 1, "prompt": "What is 3 + 2?", "expected_type": "number", "correct_answer": "5", "hints": ["Start with 3, count up 2"], "explanation": "3 + 2 = 5."},
            {"type": "problem", "difficulty": 1, "prompt": "What is 5 + 5?", "expected_type": "number", "correct_answer": "10", "hints": ["Doubles fact"], "explanation": "5 + 5 = 10."},
            {"type": "problem", "difficulty": 2, "prompt": "What is 4 + 5?", "expected_type": "number", "correct_answer": "9", "hints": ["4+4=8, so 4+5 is one more"], "explanation": "4 + 5 = 9."},
            {"type": "problem", "difficulty": 2, "prompt": "Fill in: __ + 4 = 9", "expected_type": "number", "correct_answer": "5", "hints": ["What plus 4 equals 9?"], "explanation": "5 + 4 = 9."},
            {"type": "problem", "difficulty": 3, "prompt": "How many ways can you make 8 with two numbers?", "expected_type": "text", "hints": ["Start with 0+8, then 1+7..."], "explanation": "0+8, 1+7, 2+6, 3+5, 4+4, 5+3, 6+2, 7+1, 8+0."},
        ],
        "assessment_items": [
            {"prompt": "What is 7 + 2?", "type": "number", "correct_answer": "9", "target_concept": "addition_facts"},
            {"prompt": "Fill in: __ + 6 = 10", "type": "number", "correct_answer": "4", "target_concept": "missing_addend"},
            {"prompt": "What is 5 + 4? Explain your strategy.", "type": "open_response", "rubric": "Mastery: correct (9) with strategy. Proficient: correct, vague strategy. Developing: incorrect.", "target_concept": "addition_strategy"},
        ],
        "resource_guidance": {"required": ["counting manipulatives", "number line"], "recommended": ["dice", "playing cards", "ten-frames"]},
        "time_estimates": {"first_exposure": 25, "practice_session": 15, "assessment": 10},
    },
    "mf-06": {
        "enriched": True,
        "learning_objectives": ["Recall all subtraction facts within 10", "Understand subtraction as taking away or finding difference", "Connect subtraction to addition as inverse operations", "Write subtraction number sentences"],
        "teaching_guidance": {
            "introduction": "Subtraction means taking some away or finding how many more. Start with objects: 'You have 8 grapes. You eat 3. How many are left?' Let the child physically remove objects and count what remains.",
            "scaffolding_sequence": ["Remove objects from a group and count what's left", "Introduce - and = symbols alongside manipulatives", "Connect to addition: if 3+5=8, then 8-5=3", "Practice counting back from the larger number", "Practice think-addition: 9-4=? Think 4+?=9"],
            "socratic_questions": ["You have 7 and take away 3. How could you figure out what's left?", "If 6+2=8, what is 8-2?", "Is 7-3 the same as 3-7? Why not?"],
            "practice_activities": ["Cover some objects, count what's visible", "Number line hopping backward", "Fact family triangles: 3, 5, 8"],
            "real_world_connections": ["Eating snacks: had 10, ate 4, how many left?", "Friends leaving a group", "Spending coins"],
            "common_misconceptions": ["Thinking subtraction is commutative", "Counting the starting number when counting back", "Not connecting subtraction to addition"],
        },
        "assessment_criteria": {
            "mastery_indicators": ["Recalls any subtraction fact within 10 in under 3 seconds", "Uses think-addition to solve subtraction", "Writes fact families"],
            "assessment_methods": ["oral recall", "manipulative demo", "fact family writing"],
            "sample_assessment_prompts": ["What is 9-4?", "Show 7-3 with blocks", "Write the fact family for 2, 6, 8"],
        },
        "practice_items": [
            {"type": "problem", "difficulty": 1, "prompt": "What is 5 - 2?", "expected_type": "number", "correct_answer": "3", "hints": ["Start with 5, take away 2"], "explanation": "5 - 2 = 3."},
            {"type": "problem", "difficulty": 1, "prompt": "What is 10 - 5?", "expected_type": "number", "correct_answer": "5", "hints": ["10 split in half"], "explanation": "10 - 5 = 5."},
            {"type": "problem", "difficulty": 2, "prompt": "What is 9 - 6?", "expected_type": "number", "correct_answer": "3", "hints": ["Think: 6 + ? = 9"], "explanation": "9 - 6 = 3."},
            {"type": "problem", "difficulty": 2, "prompt": "Fill in: 10 - __ = 4", "expected_type": "number", "correct_answer": "6", "hints": ["Think: 4 + ? = 10"], "explanation": "10 - 6 = 4."},
            {"type": "problem", "difficulty": 3, "prompt": "If 3+5=8, write two subtraction facts using the same numbers.", "expected_type": "text", "hints": ["Use 3, 5, and 8"], "explanation": "8-3=5 and 8-5=3."},
        ],
        "assessment_items": [
            {"prompt": "What is 9 - 7?", "type": "number", "correct_answer": "2", "target_concept": "subtraction_facts"},
            {"prompt": "Write the fact family for 4, 5, 9.", "type": "text", "rubric": "Mastery: all four facts. Proficient: 3 facts. Developing: 1-2 facts.", "target_concept": "fact_families"},
            {"prompt": "You had 8 crayons. Some broke. Now you have 3. How many broke?", "type": "number", "correct_answer": "5", "target_concept": "subtraction_word_problem"},
        ],
        "resource_guidance": {"required": ["counting manipulatives", "number line"], "recommended": ["fact family triangles"]},
        "time_estimates": {"first_exposure": 25, "practice_session": 15, "assessment": 10},
    },
    "mf-07": {
        "enriched": True,
        "learning_objectives": ["Add any two numbers with sums to 20", "Use strategies: counting on, making ten, doubles, doubles plus one", "Solve addition word problems within 20"],
        "teaching_guidance": {
            "introduction": "Extending beyond 10. The key strategy is making ten: to solve 8+5, think '8 needs 2 to make 10, then 3 left over, so 13.' Use ten-frames to make this visual.",
            "scaffolding_sequence": ["Review facts to 10, then extend with 10+1, 10+2, etc.", "Practice doubles to 20: 6+6=12, 7+7=14, 8+8=16, 9+9=18", "Practice doubles-plus-one: 6+7=13", "Master make-ten using ten-frames", "Solve word problems within 20"],
            "socratic_questions": ["How could you use 7+7 to solve 7+8?", "What's a fast way to add 9 to any number?", "If 8+5 is hard, could you rearrange it?"],
            "practice_activities": ["Ten-frame addition: fill first frame, overflow to second", "Double dice: roll one, double it", "Number bond puzzles for teens"],
            "real_world_connections": ["Adding two-digit scores", "Combining groups larger than 10"],
            "common_misconceptions": ["Treating teens as two separate digits", "Not decomposing to use make-ten", "Over-relying on finger counting"],
        },
        "assessment_criteria": {
            "mastery_indicators": ["Solves any addition within 20 in under 5 seconds", "Explains make-ten strategy", "Solves word problems within 20"],
            "assessment_methods": ["oral recall", "strategy explanation", "word problems"],
            "sample_assessment_prompts": ["What is 8+7?", "How would you solve 9+6 using make-ten?"],
        },
        "practice_items": [
            {"type": "problem", "difficulty": 1, "prompt": "What is 10 + 6?", "expected_type": "number", "correct_answer": "16", "hints": ["10 plus a number is easy"], "explanation": "10 + 6 = 16."},
            {"type": "problem", "difficulty": 1, "prompt": "What is 7 + 7?", "expected_type": "number", "correct_answer": "14", "hints": ["Doubles fact"], "explanation": "7 + 7 = 14."},
            {"type": "problem", "difficulty": 2, "prompt": "What is 8 + 5?", "expected_type": "number", "correct_answer": "13", "hints": ["Make ten: 8+2=10, then 3 more"], "explanation": "8 + 5 = 13. Break 5 into 2+3. 8+2=10, 10+3=13."},
            {"type": "problem", "difficulty": 2, "prompt": "What is 9 + 7?", "expected_type": "number", "correct_answer": "16", "hints": ["9 is close to 10. 10+7=17, minus 1"], "explanation": "9 + 7 = 16."},
            {"type": "problem", "difficulty": 3, "prompt": "Sara has 9 red flowers and 8 yellow. How many total? Explain your strategy.", "expected_type": "text", "hints": ["9+8. Try doubles: 9+9=18, minus 1"], "explanation": "9+8=17. Strategy: 9+9=18, minus 1 = 17."},
        ],
        "assessment_items": [
            {"prompt": "What is 8 + 6?", "type": "number", "correct_answer": "14", "target_concept": "addition_to_20"},
            {"prompt": "Solve 7+8 and explain your strategy.", "type": "open_response", "rubric": "Mastery: correct (15) with clear strategy. Proficient: correct, vague. Developing: incorrect.", "target_concept": "addition_strategy"},
            {"prompt": "Jake found 6 shells then 9 more. How many?", "type": "number", "correct_answer": "15", "target_concept": "word_problem"},
        ],
        "resource_guidance": {"required": ["ten-frame boards", "counters"], "recommended": ["Rekenrek"]},
        "time_estimates": {"first_exposure": 25, "practice_session": 15, "assessment": 10},
    },
    "mf-08": {
        "enriched": True,
        "learning_objectives": ["Subtract within 20 fluently", "Use think-addition strategy for subtraction", "Solve subtraction word problems within 20", "Understand: if 8+7=15, then 15-7=8"],
        "teaching_guidance": {
            "introduction": "Subtraction within 20 builds on addition within 20. The most powerful strategy is think-addition: to solve 15-8, think '8 + what = 15?' Also use subtract-through-ten: 13-5 = 13-3-2 = 10-2 = 8.",
            "scaffolding_sequence": ["Review subtraction within 10", "Subtract teen numbers by thinking addition: 12-5, think 5+?=12", "Subtract through ten: 14-6 = 14-4-2 = 8", "Practice fact families for teen numbers", "Solve word problems: take-away, comparison, missing part"],
            "socratic_questions": ["If you know 7+6=13, how does that help with 13-6?", "How would you solve 15-9?", "What's the connection between 8+8=16 and 16-8?"],
            "practice_activities": ["Fact family flashcards for teen numbers", "Subtraction stories for problems like 17-9", "Number line jumps backward"],
            "real_world_connections": ["Had 15 grapes, ate some, how many left?", "Comparing: 18 vs 11, how much more?"],
            "common_misconceptions": ["Trying to count back large amounts instead of thinking addition", "Not connecting subtraction to known addition facts"],
        },
        "assessment_criteria": {
            "mastery_indicators": ["Solves any subtraction within 20 in under 5 seconds", "Explains think-addition strategy", "Solves comparison word problems"],
            "assessment_methods": ["oral recall", "strategy explanation", "word problems"],
            "sample_assessment_prompts": ["What is 16-9?", "How does 6+8=14 help with 14-8?"],
        },
        "practice_items": [
            {"type": "problem", "difficulty": 1, "prompt": "What is 12 - 2?", "expected_type": "number", "correct_answer": "10", "hints": ["Take 2 from 12"], "explanation": "12 - 2 = 10."},
            {"type": "problem", "difficulty": 2, "prompt": "What is 13 - 7?", "expected_type": "number", "correct_answer": "6", "hints": ["Think: 7 + ? = 13"], "explanation": "13 - 7 = 6."},
            {"type": "problem", "difficulty": 2, "prompt": "What is 16 - 8?", "expected_type": "number", "correct_answer": "8", "hints": ["8+8=16, so 16-8=?"], "explanation": "16 - 8 = 8. Doubles in reverse."},
            {"type": "problem", "difficulty": 3, "prompt": "Amy has 17 beads. She gives 8 away. How many left?", "expected_type": "number", "correct_answer": "9", "hints": ["17-8. Think: 8+?=17"], "explanation": "17 - 8 = 9."},
            {"type": "problem", "difficulty": 3, "prompt": "Write the fact family for 7, 9, 16.", "expected_type": "text", "hints": ["2 addition + 2 subtraction using 7, 9, 16"], "explanation": "7+9=16, 9+7=16, 16-7=9, 16-9=7."},
        ],
        "assessment_items": [
            {"prompt": "What is 15 - 7?", "type": "number", "correct_answer": "8", "target_concept": "subtraction_within_20"},
            {"prompt": "Lee has 14 crayons, Sam has 6. How many more does Lee have?", "type": "number", "correct_answer": "8", "target_concept": "comparison"},
            {"prompt": "Explain how knowing 8+5=13 helps solve 13-5.", "type": "open_response", "rubric": "Mastery: explains inverse relationship. Proficient: correct answer. Developing: counts back.", "target_concept": "inverse_relationship"},
        ],
        "resource_guidance": {"required": ["ten-frames", "counters"], "recommended": ["fact family triangles"]},
        "time_estimates": {"first_exposure": 25, "practice_session": 15, "assessment": 10},
    },
    "mf-09": {
        "enriched": True,
        "learning_objectives": ["Understand that two-digit numbers are made of tens and ones", "Decompose numbers: 45 = 4 tens + 5 ones", "Use base-ten blocks to represent two-digit numbers"],
        "teaching_guidance": {
            "introduction": "Place value is the biggest idea in elementary math. The digit 3 in 35 means something different from 3 in 53. Use base-ten blocks: a ten-rod is ten cubes stuck together. To build 34, grab 3 ten-rods and 4 unit cubes.",
            "scaffolding_sequence": ["Build numbers 10-19 with ten-rods and units", "Build numbers 20-50", "Build numbers 50-99", "Say tens and ones: '42 is 4 tens and 2 ones'", "Write expanded form: 42 = 40 + 2"],
            "socratic_questions": ["In 67, what does the 6 mean? The 7?", "Which is worth more: the 3 in 36 or the 3 in 63?", "How many tens are in 80?"],
            "practice_activities": ["Build numbers with blocks and write the numeral", "Place value mat: sort blocks into tens and ones columns", "Riddles: I have 5 tens and 3 ones. What number am I?"],
            "real_world_connections": ["Dimes (10 cents) and pennies (1 cent)", "Bundles of 10 sticks vs loose sticks"],
            "common_misconceptions": ["Thinking 16 means '1 and 6' not '1 ten and 6 ones'", "Reversing digits", "Thinking ones digit is worth more"],
        },
        "assessment_criteria": {
            "mastery_indicators": ["Decomposes any two-digit number into tens and ones", "Builds any two-digit number with blocks", "Explains why digit position matters"],
            "assessment_methods": ["block building", "expanded form writing", "oral explanation"],
            "sample_assessment_prompts": ["Build 73 with blocks", "Write 58 in expanded form", "Which digit is worth more in 49?"],
        },
        "practice_items": [
            {"type": "problem", "difficulty": 1, "prompt": "How many tens are in 30?", "expected_type": "number", "correct_answer": "3", "hints": ["30 = ? tens and 0 ones"], "explanation": "30 has 3 tens."},
            {"type": "problem", "difficulty": 1, "prompt": "I have 5 tens and 2 ones. What number?", "expected_type": "number", "correct_answer": "52", "hints": ["5 tens = 50, plus 2"], "explanation": "52."},
            {"type": "problem", "difficulty": 2, "prompt": "Write 67 in expanded form.", "expected_type": "text", "correct_answer": "60 + 7", "hints": ["Break into tens and ones"], "explanation": "67 = 60 + 7."},
            {"type": "problem", "difficulty": 3, "prompt": "Which is greater: 47 or 74? Explain using place value.", "expected_type": "text", "hints": ["Compare tens digits"], "explanation": "74 is greater: 7 tens vs 4 tens."},
        ],
        "assessment_items": [
            {"prompt": "What number has 6 tens and 9 ones?", "type": "number", "correct_answer": "69", "target_concept": "place_value"},
            {"prompt": "Explain why the 5 in 56 is worth more than the 6.", "type": "open_response", "rubric": "Mastery: 5 means 50, 6 means 6. Proficient: says 5 means 50. Developing: cannot explain.", "target_concept": "place_value_understanding"},
        ],
        "resource_guidance": {"required": ["base-ten blocks"], "recommended": ["place value mat", "dimes and pennies"]},
        "time_estimates": {"first_exposure": 25, "practice_session": 15, "assessment": 10},
    },
    "mf-10": {
        "enriched": True,
        "learning_objectives": ["Skip count by 2s to 30", "Skip count by 5s to 100", "Skip count by 10s to 100", "Recognize patterns in skip counting"],
        "teaching_guidance": {
            "introduction": "Skip counting is counting by groups. It's faster, reveals patterns, and builds the foundation for multiplication. Start with physical objects grouped in twos, fives, and tens.",
            "scaffolding_sequence": ["Group objects in pairs, count by 2s", "Use a hundred chart: color every 2nd number", "Count by 5s using tally marks", "Count by 10s using ten-rods", "Identify patterns: 5s end in 0 or 5, 10s end in 0"],
            "socratic_questions": ["What pattern do you see counting by 2s?", "If counting by 5s and we're at 35, what's next?", "Why is counting by 10s so easy?"],
            "practice_activities": ["Count pairs of shoes by 2s", "Count nickels by 5s", "Hundred chart: circle patterns for 2s, 5s, 10s in different colors"],
            "real_world_connections": ["Counting nickels", "Counting dimes", "Counting pairs of socks"],
            "common_misconceptions": ["Starting at 0 instead of the skip number", "Losing the pattern mid-sequence"],
        },
        "assessment_criteria": {
            "mastery_indicators": ["Skip counts by 2s to 30 fluently", "By 5s to 100 fluently", "By 10s to 100 fluently"],
            "assessment_methods": ["oral skip counting", "pattern completion"],
            "sample_assessment_prompts": ["Count by 2s to 24", "Count by 5s to 60", "Count by 10s to 100"],
        },
        "practice_items": [
            {"type": "problem", "difficulty": 1, "prompt": "Count by 10s: 10, 20, 30, __, __, __", "expected_type": "text", "correct_answer": "40, 50, 60", "hints": ["Add 10 each time"], "explanation": "40, 50, 60."},
            {"type": "problem", "difficulty": 1, "prompt": "Count by 5s: 5, 10, 15, 20, __, __", "expected_type": "text", "correct_answer": "25, 30", "hints": ["Add 5 each time"], "explanation": "25, 30."},
            {"type": "problem", "difficulty": 2, "prompt": "Count by 2s: 12, 14, 16, __, __, __", "expected_type": "text", "correct_answer": "18, 20, 22", "hints": ["Add 2 each time"], "explanation": "18, 20, 22."},
            {"type": "problem", "difficulty": 3, "prompt": "Count by 5s from 35 to 70.", "expected_type": "text", "correct_answer": "35, 40, 45, 50, 55, 60, 65, 70", "hints": ["Start at 35, add 5 each time"], "explanation": "35, 40, 45, 50, 55, 60, 65, 70."},
        ],
        "assessment_items": [
            {"prompt": "Count by 2s from 2 to 20.", "type": "text", "correct_answer": "2, 4, 6, 8, 10, 12, 14, 16, 18, 20", "target_concept": "skip_counting_2s"},
            {"prompt": "What pattern do you notice counting by 5s?", "type": "open_response", "rubric": "Mastery: all end in 0 or 5, alternating. Proficient: end in 0 or 5. Developing: no pattern identified.", "target_concept": "patterns"},
        ],
        "resource_guidance": {"required": ["hundred chart"], "recommended": ["coins", "objects for grouping"]},
        "time_estimates": {"first_exposure": 20, "practice_session": 15, "assessment": 10},
    },
    "mf-11": {
        "enriched": True,
        "learning_objectives": ["Compare two numbers using greater than, less than, equal to", "Use > < = symbols correctly", "Compare two-digit numbers by tens first, then ones", "Order numbers from least to greatest"],
        "teaching_guidance": {
            "introduction": "Comparing answers 'which is more?' Use two groups side by side. For two-digit numbers, compare tens first. If equal, compare ones. The alligator mouth faces the bigger number.",
            "scaffolding_sequence": ["Compare groups of objects by matching one-to-one", "Compare single-digit numbers with > < =", "Introduce alligator mouth mnemonic", "Compare two-digit numbers: tens first", "Order 3-5 numbers least to greatest"],
            "socratic_questions": ["Which group has more? How do you know?", "Is 34 greater or less than 43? How did you decide?", "If tens are the same, how do you compare?"],
            "practice_activities": ["Comparison war card game", "Number line ordering", "Build both numbers with blocks and compare"],
            "real_world_connections": ["Comparing ages", "Comparing prices", "Comparing game scores"],
            "common_misconceptions": ["Comparing ones instead of tens first", "Reversing > and <"],
        },
        "assessment_criteria": {
            "mastery_indicators": ["Correctly compares any two numbers within 100", "Explains using place value", "Orders 5 numbers least to greatest"],
            "assessment_methods": ["symbol placement", "ordering", "explanation"],
            "sample_assessment_prompts": ["Put > < or = between 45 and 54", "Order: 72, 27, 45, 54, 63"],
        },
        "practice_items": [
            {"type": "problem", "difficulty": 1, "prompt": "Which is greater: 7 or 3?", "expected_type": "number", "correct_answer": "7", "hints": ["Which comes later when counting?"], "explanation": "7 is greater."},
            {"type": "problem", "difficulty": 1, "prompt": "Put > < or = between 5 and 5.", "expected_type": "text", "correct_answer": "=", "hints": ["Are they the same?"], "explanation": "5 = 5."},
            {"type": "problem", "difficulty": 2, "prompt": "Which is greater: 38 or 83?", "expected_type": "number", "correct_answer": "83", "hints": ["Compare tens: 3 vs 8"], "explanation": "83. It has 8 tens vs 3 tens."},
            {"type": "problem", "difficulty": 3, "prompt": "Order least to greatest: 45, 54, 39, 93, 41", "expected_type": "text", "correct_answer": "39, 41, 45, 54, 93", "hints": ["Find smallest tens digit first"], "explanation": "39, 41, 45, 54, 93."},
        ],
        "assessment_items": [
            {"prompt": "Write > < or = between 47 and 74.", "type": "text", "correct_answer": "<", "target_concept": "comparison"},
            {"prompt": "Order least to greatest: 62, 26, 55, 82", "type": "text", "correct_answer": "26, 55, 62, 82", "target_concept": "ordering"},
            {"prompt": "Explain how you compare two two-digit numbers.", "type": "open_response", "rubric": "Mastery: compare tens first, then ones. Proficient: gets correct answers. Developing: compares ones first.", "target_concept": "comparison_strategy"},
        ],
        "resource_guidance": {"required": ["comparison symbol cards", "base-ten blocks"], "recommended": ["number line"]},
        "time_estimates": {"first_exposure": 20, "practice_session": 15, "assessment": 10},
    },
}
