"""Pre-enriched content for Mathematics Developing template nodes."""

MATH_DEVELOPING_CONTENT = {
    "md-01": {
        "enriched": True,
        "learning_objectives": [
            "Add three-digit numbers with and without regrouping",
            "Subtract three-digit numbers including across one regrouping",
            "Use expanded-form and decomposition strategies before reaching for the standard algorithm",
            "Estimate the answer first and judge whether the computed result is reasonable",
        ],
        "teaching_guidance": {
            "introduction": "The child already adds and subtracts within 20 and works with two-digit numbers. The task now is to extend the same place-value thinking to the hundreds, where regrouping can happen at the tens column, the hundreds column, or both. Begin with base-ten blocks so the regrouping is something the child does with their hands before it is something they write down. Names the trade out loud every time: ten ones is one ten, ten tens is one hundred.",
            "scaffolding_sequence": [
                "Build three-digit numbers with base-ten blocks (hundreds flats, tens rods, ones cubes) and read the number aloud in place-value language",
                "Add two three-digit numbers with no regrouping by combining like blocks: hundreds with hundreds, tens with tens, ones with ones",
                "Add two three-digit numbers that regroup at the ones column, physically trading ten ones for a ten before counting the tens",
                "Add two three-digit numbers that regroup at the tens column, trading ten tens for a hundred",
                "Subtract three-digit numbers without regrouping, then with regrouping at the ones column, then at the tens column",
                "Record what the blocks are doing using expanded form (300 + 40 + 7) before introducing column notation",
                "Always estimate first by rounding to the nearest hundred, solve, then compare to the estimate",
            ],
            "socratic_questions": [
                "What do you notice about the ones column? Is there enough to keep as ones, or do we need to trade?",
                "If we trade ten ones for one ten, has the total changed?",
                "Your estimate was 500 and you got 487. Does that seem reasonable, and how do you know?",
                "When we subtract and the top digit is smaller, what can we borrow from, and why does it become ten?",
            ],
            "practice_activities": [
                "Play 'race to 1000': roll three dice, build the number with blocks, add to a running total, race a partner",
                "Solve grocery-receipt problems: add three priced items mentally, then verify on paper",
                "Subtraction story: a savings jar starts at 524 cents, child spends 178 cents, how much remains?",
            ],
            "real_world_connections": [
                "Tracking page numbers read across a chapter book",
                "Counting steps on a long walk or hike",
                "Calculating change from a hundred-dollar bill in a pretend shop",
                "Adding daily step counts across a week",
            ],
            "common_misconceptions": [
                "Adding across columns without regrouping (writing 14 in the ones column instead of carrying the ten)",
                "Subtracting the smaller digit from the larger regardless of position (e.g., treating 43 - 28 as 8 - 3 = 5 in the ones)",
                "Forgetting to update the tens column after borrowing from it",
                "Thinking that 'borrowing' actually removes value from the number, instead of just renaming it",
            ],
        },
        "assessment_criteria": {
            "mastery_indicators": [
                "Adds and subtracts three-digit numbers with one regrouping correctly on 8 of 10 problems",
                "Explains regrouping in place-value language: ten ones is one ten, ten tens is one hundred",
                "Catches an unreasonable answer by comparing it to an estimate before declaring the work done",
            ],
            "assessment_methods": ["mixed paper computation", "oral place-value explanation", "block-based demonstration"],
            "sample_assessment_prompts": [
                "Solve 247 + 365 and show your work in place-value language",
                "Solve 503 - 178 and explain what you traded and why",
                "Estimate 489 + 312 to the nearest hundred. Then solve exactly. Was your estimate close?",
            ],
        },
        "practice_items": [
            {
                "type": "problem",
                "difficulty": 1,
                "prompt": "What is 234 + 152?",
                "expected_type": "number",
                "correct_answer": "386",
                "hints": ["Add the ones, then the tens, then the hundreds, no regrouping needed"],
                "explanation": "234 + 152. Ones: 4 + 2 = 6. Tens: 3 + 5 = 8. Hundreds: 2 + 1 = 3. Answer: 386.",
            },
            {
                "type": "problem",
                "difficulty": 2,
                "prompt": "What is 247 + 365?",
                "expected_type": "number",
                "correct_answer": "612",
                "hints": ["Ones: 7 + 5 = 12, write 2 carry 1", "Tens: 4 + 6 + 1 carried = 11, write 1 carry 1"],
                "explanation": "247 + 365. Ones: 12, write 2 carry 1. Tens: 4+6+1 = 11, write 1 carry 1. Hundreds: 2+3+1 = 6. Answer: 612.",
            },
            {
                "type": "problem",
                "difficulty": 2,
                "prompt": "What is 503 - 178?",
                "expected_type": "number",
                "correct_answer": "325",
                "hints": ["The ones place needs to borrow", "You will need to borrow from the hundreds to make the tens column usable"],
                "explanation": "503 - 178. Cannot do 3 - 8 in ones, borrow from tens, but tens is 0, so borrow from hundreds first. 503 becomes 4 hundreds, 9 tens, 13 ones. 13-8 = 5, 9-7 = 2, 4-1 = 3. Answer: 325.",
            },
            {
                "type": "problem",
                "difficulty": 2,
                "prompt": "Estimate 489 + 312 by rounding each number to the nearest hundred. What is your estimate?",
                "expected_type": "number",
                "correct_answer": "800",
                "hints": ["489 rounds to 500", "312 rounds to 300"],
                "explanation": "489 rounds to 500, 312 rounds to 300, so the estimate is 800. (The exact answer is 801, so the estimate is very close.)",
            },
            {
                "type": "problem",
                "difficulty": 3,
                "prompt": "A library has 624 books. They donate 167 to another school. How many books remain?",
                "expected_type": "number",
                "correct_answer": "457",
                "hints": ["This is subtraction: 624 - 167", "You will need to regroup more than once"],
                "explanation": "624 - 167. Ones: borrow, 14 - 7 = 7. Tens: 1 (after lending) - 6, borrow, 11 - 6 = 5. Hundreds: 5 - 1 = 4. Answer: 457 books remain.",
            },
        ],
        "assessment_items": [
            {
                "prompt": "Solve 358 + 274 and write each step in place-value language.",
                "type": "number",
                "correct_answer": "632",
                "target_concept": "three_digit_addition_with_regrouping",
            },
            {
                "prompt": "Solve 700 - 246.",
                "type": "number",
                "correct_answer": "454",
                "target_concept": "three_digit_subtraction_across_zeros",
            },
            {
                "prompt": "Estimate 678 + 219 to the nearest hundred. Then solve exactly. Is your estimate reasonable?",
                "type": "open_response",
                "rubric": "Mastery: rounds correctly (700+200=900), computes correctly (897), and compares meaningfully. Proficient: rounds and computes correctly but does not compare. Developing: errors in rounding or computation.",
                "target_concept": "estimation_and_verification",
            },
        ],
        "resource_guidance": {
            "required": ["base-ten blocks (hundreds, tens, ones)", "place-value mat", "pencil and paper for column work"],
            "recommended": ["hundred chart", "three-digit number cards", "play money in $1, $10, $100 denominations"],
        },
        "time_estimates": {"first_exposure": 30, "practice_session": 20, "assessment": 20},
        "accommodations": {
            "dyslexia": "Use color-coded place-value columns (hundreds red, tens blue, ones green) and grid paper to keep digits in their columns.",
            "adhd": "Limit to 3 to 5 problems per session. Use blocks for at least half of every session so the child is moving and touching, not only writing.",
            "gifted": "Push toward four-digit problems and have the child explain why the standard algorithm works using place-value reasoning.",
            "visual_learner": "Always model with base-ten blocks alongside the written work, and use expanded-form notation as a bridge.",
            "kinesthetic_learner": "Physically trade ten ones for a tens rod on a place-value mat for every regroup.",
            "auditory_learner": "Speak each step aloud: 'seven plus five is twelve, write two and carry one ten.'",
        },
        "philosophy_specific": {
            "traditional": {
                "introduction": "We extend addition and subtraction into the hundreds. The same place-value rules apply, only there are more columns. Today we add and subtract three-digit numbers, regrouping when a column overflows or falls short.",
                "gradual_release": {
                    "i_do": "Model 247 + 365 aloud, naming each step in place-value language: 'seven plus five is twelve ones, write the two and carry the ten.' Show the same work with base-ten blocks on a place-value mat so the carry is visible.",
                    "we_do": "Work three problems together, child speaking the steps while the parent writes, then swap roles. Include one with regrouping at the ones column, one at the tens, and one with no regrouping at all so the child must judge.",
                    "you_do": "Child solves five mixed problems independently, estimates first on each, then checks their answer against the estimate.",
                },
                "guided_practice": [
                    "Solve five three-digit addition problems with the parent watching and prompting on regrouping only",
                    "Solve five three-digit subtraction problems including one that requires borrowing across two columns",
                    "Estimate each answer first by rounding to the nearest hundred",
                ],
                "independent_practice": [
                    "Worksheet of ten mixed three-digit addition and subtraction problems with answers checked against estimates",
                    "Story-problem set: five short word problems involving sums and differences in the hundreds",
                ],
                "mastery_check": [
                    "Solve eight of ten three-digit problems correctly, including at least three with regrouping",
                    "Explain in place-value language what 'carrying' and 'borrowing' actually do to the number",
                    "Catch at least one unreasonable answer in a set by comparing to the estimate",
                ],
                "spiral_review": [
                    "Re-do two-digit addition and subtraction problems at the start of each session for a week to keep the algorithm sharp",
                    "Mix in place-value warm-ups: 'how many tens are in 470?' before each lesson",
                ],
            },
            "classical": {
                "narrative_introduction": "The Romans, the Greeks, and the merchants of every old town reckoned in coins and weights running into the hundreds, and they did it with the same place-value thinking we use now. To take up addition and subtraction in the hundreds is to take up a craft very old and very useful, and to do it well is to stand in a long line of careful reckoners.",
                "memory_work": {
                    "chants": [
                        "Recite the trade rule: ten ones is one ten, ten tens is one hundred",
                        "Recite the columns in order: ones, tens, hundreds, every problem worked from right to left",
                        "Recite the estimate-then-solve rule: round first, reckon second, compare third",
                    ],
                    "recitations": [
                        "A worked example said aloud in place-value language until the steps run without hesitation",
                    ],
                },
                "copywork": [
                    "Copy a small set of clean three-digit problems and their fully worked solutions into the math copybook, neat and exact, so the form of the algorithm is in the hand as well as the head",
                ],
                "recitation_routine": "Begin each lesson by reciting yesterday's worked example, then add today's. The standard form of the algorithm is reviewed cumulatively until it is automatic.",
                "history_integration": "Tell briefly of the old way of reckoning with the abacus or counting board, where a trade in the ones row really did mean moving a bead to the tens row, and the written algorithm is simply the same trade put down on paper.",
                "read_aloud_suggestions": [
                    "A short story or chapter about a shopkeeper, a treasurer, or a counter of stores, where sums in the hundreds are part of the daily work",
                    "A well-written biography passage about an early merchant or mathematician who reckoned by hand",
                ],
            },
            "charlotte_mason": {
                "lesson_length_minutes": 18,
                "living_book_suggestions": [
                    "A real, beautifully illustrated arithmetic book that walks a child through three-digit problems using meaningful contexts, never a busy workbook",
                    "A short biography of a merchant, scribe, or treasurer in which sums and differences in the hundreds appear in real life",
                ],
                "short_lesson_flow": "Begin with a few minutes of mental warm-up: doubles and place-value questions. Lay out base-ten blocks and a place-value mat. Pose one real problem: the family's grocery total, the books in the home library, the steps taken yesterday and today. Work the problem with the blocks first, then on paper. Stop while the child is still interested.",
                "narration_prompt": "Tell me, in your own words, what you did to find the answer. Where did the regrouping happen, and why?",
                "real_world_objects": [
                    "Base-ten blocks (hundreds, tens, ones) and a place-value mat",
                    "Real coins or play money, including hundred-dollar bills",
                    "A small notebook in which real sums from the household are kept and added across a week",
                ],
                "nature_connection": "Count and record a real outdoor quantity that runs to the hundreds: pinecones gathered across several walks, steps from the house to the mailbox and back over a week, leaves collected for a nature project.",
                "habit_focus": "The habit of accuracy: work the problem once, carefully, with full attention, rather than scratching out and starting over. Estimate first, so an unreasonable answer is noticed at once.",
            },
            "montessori": {
                "prepared_materials": [
                    "Golden bead material (units, ten-bars, hundred-squares) for concrete place value",
                    "Stamp game (colored tiles standing for units, tens, hundreds) as the first level of abstraction",
                    "Small numeral cards 1 through 9000 for building and reading three-digit and four-digit numbers",
                    "Addition and subtraction strip boards held in reserve for review of basic facts",
                ],
                "presentation": {
                    "three_period_lesson": "No new naming is required; this is the application of the place-value names long since given. The presentation is the operation itself, shown silently and slowly with the materials, then named: 'this is dynamic addition, with exchange.'",
                    "steps": [
                        "Lay out the first addend in golden beads on a tray (or stamps on the board), naming each category aloud",
                        "Lay out the second addend on a second tray (or below the first on the stamp game)",
                        "Combine the units; if there are ten or more, count out ten and exchange them for one ten-bar, then place the ten-bar with the tens",
                        "Combine the tens; if there are ten or more, exchange ten ten-bars for one hundred-square",
                        "Combine the hundreds and read the total aloud",
                        "Record the operation on paper only after the material has been used several times",
                    ],
                },
                "control_of_error": "The materials are the control: ten units physically cannot remain as units once gathered, they must be exchanged for a ten-bar, so the child sees and corrects errors of regrouping without being told. The total formed by the materials and the total written on paper must agree.",
                "abstraction_pathway": "From golden beads (quantity felt in the hand) to the stamp game (color stands for category, weight is gone) to the small bead frame to the written algorithm with no material at all. The child moves to the next level only when the current one is effortless.",
                "extensions": [
                    "Carry the operation into four-digit numbers using the same materials and exchanges",
                    "Introduce static subtraction (no exchange), then dynamic subtraction (with exchange)",
                    "Build a small bank of problems the child writes for themselves and works at the shelf over several days",
                ],
                "observation_focus": "Watch whether the child reaches for the material on hard problems and works on paper on easy ones; this is the natural movement toward abstraction. Watch also for the silent exchange done correctly without prompting.",
            },
            "unschooling": {
                "invitations": [
                    "Leave a small play cash register with hundred-dollar bills and a price tag set on the shelf, alongside real items to buy and sell",
                    "Put a long paper receipt from the family shop on the kitchen table and wonder aloud whether the total really adds up",
                    "Set out a set of dice and a notebook with a casual challenge: build a number in the hundreds, add another, see how high you can go",
                ],
                "real_world_contexts": [
                    "Tallying the family grocery bill or a restaurant check",
                    "Tracking points across a long board game or video game session",
                    "Counting savings in a jar, adding each week's contribution",
                    "Calculating distance traveled across a multi-day trip from the car's odometer",
                ],
                "conversation_starters": [
                    "How much do you think all of these together cost?",
                    "I have $500 saved and the bike costs $327. Do I have enough? How much would I have left?",
                    "Want to guess our total before I add it up, and see how close you get?",
                ],
                "resource_bank": [
                    "A real cash register or shop-set with bills and coins available, not required",
                    "Open-ended board games with running scores: Monopoly, Yahtzee, Phase 10",
                    "A simple notebook for keeping the family's running scores, totals, and reckonings",
                    "Online videos that walk through real sums (with the child's permission), if and when interest arrives",
                ],
                "parent_role": "Add aloud in front of the child often. Welcome rough estimates. When a real number question comes up, work it together on paper or with mental math, not as a lesson but as a real thing being figured out. Never grade or correct mid-attempt; ask, instead, whether the answer seems about right.",
                "observation_documentation": "Note across weeks where three-digit sums and differences arose in real life, what strategies the child used (counting up, place-value reasoning, estimation), and whether they grew more comfortable comparing their answer to a quick estimate.",
            },
        },
        "connections": {
            "reading": "Reading three-digit and four-digit numerals fluently in chapter-book page numbers and real-world signage",
            "science": "Recording counts and measurements that run into the hundreds in nature observation logs",
            "history": "Reading dates in the hundreds and reasoning about how many years separate two events",
        },
    },
    "md-02": {
        "enriched": True,
        "learning_objectives": [
            "Read, write, and compare four-digit numbers up to 10,000",
            "Express four-digit numbers in standard form, expanded form, and word form",
            "Identify the value of each digit by its place (thousands, hundreds, tens, ones)",
            "Order a small set of four-digit numbers from least to greatest",
        ],
        "teaching_guidance": {
            "introduction": "The thousand is a leap. The child knows that ten ones make a ten and ten tens make a hundred; today the rule extends one more rung: ten hundreds make a thousand. Build a four-digit number with base-ten materials (a thousand cube, hundred flats, tens rods, ones cubes) before any writing is done, and read the number in place-value language every time. The new column is the thousands.",
            "scaffolding_sequence": [
                "Show a thousand cube alongside ten hundred flats and confirm by stacking that they are equal",
                "Build small four-digit numbers (1,000 to 3,000) with materials and read them in place-value language",
                "Write the standard form from a built quantity: 2,347 = two thousand three hundred forty-seven",
                "Decompose a written four-digit number into expanded form: 2,347 = 2,000 + 300 + 40 + 7",
                "Compare two four-digit numbers by looking at the leftmost differing digit",
                "Order three or four four-digit numbers from least to greatest and back",
                "Read and write the word form of four-digit numbers, attending to the comma and the word 'thousand'",
            ],
            "socratic_questions": [
                "Which digit in 4,728 is worth the most, and what is its value?",
                "Two numbers begin with 6 in the thousands place; how do you decide which is bigger?",
                "If we add one to 9,999, what number do we get, and what happens in every column?",
                "What does the comma in 5,283 actually tell us?",
            ],
            "practice_activities": [
                "Build-a-number game: roll four digit cards, arrange to form the largest possible four-digit number and the smallest, then compare",
                "Treasure-chest counting: imagine a chest of pretend gold and silver coins running into the thousands; read and write the total each day",
                "Newspaper hunt: find four-digit numbers in real headlines (population, distance, dates of the future) and write each in expanded and word form",
            ],
            "real_world_connections": [
                "Reading the year in dates, the population of a nearby town, distances between cities",
                "Reading miles on a car's odometer and predicting what it will say tomorrow",
                "Reading the page count on a long encyclopedia or atlas",
                "Counting steps across a multi-day adventure or a sports season's points",
            ],
            "common_misconceptions": [
                "Reading 2,047 as 'two thousand and forty seven' but writing it as 247 or 2,470",
                "Believing the comma changes the value, rather than just helping us read it",
                "Comparing four-digit numbers by total digit count rather than digit position (thinking 999 > 1,012)",
                "Confusing expanded form 2,000 + 300 + 40 + 7 with the addition 2,347 vs. the written digits",
            ],
        },
        "assessment_criteria": {
            "mastery_indicators": [
                "Reads aloud and writes from dictation any four-digit number up to 9,999 without error",
                "Writes any given four-digit number in standard, expanded, and word form",
                "Orders four four-digit numbers from least to greatest with correct reasoning about leading digits",
            ],
            "assessment_methods": ["oral reading of numbers", "written conversion among forms", "ordering tasks"],
            "sample_assessment_prompts": [
                "Write 4,506 in expanded form and in word form",
                "Order from least to greatest: 4,705, 4,075, 5,047, 4,750",
                "What is the value of the 8 in 6,820? In 6,082? In 8,206?",
            ],
        },
        "practice_items": [
            {
                "type": "problem",
                "difficulty": 1,
                "prompt": "How many hundreds are in 1 thousand?",
                "expected_type": "number",
                "correct_answer": "10",
                "hints": ["Stack hundred flats until they make a thousand cube"],
                "explanation": "Ten hundreds make one thousand: 100 + 100 + 100 + 100 + 100 + 100 + 100 + 100 + 100 + 100 = 1,000.",
            },
            {
                "type": "problem",
                "difficulty": 1,
                "prompt": "What is the value of the 4 in 4,329?",
                "expected_type": "number",
                "correct_answer": "4000",
                "hints": ["The 4 is in the thousands place"],
                "explanation": "The 4 is in the thousands place, so its value is 4,000.",
            },
            {
                "type": "problem",
                "difficulty": 2,
                "prompt": "Write 3,608 in expanded form.",
                "expected_type": "text",
                "hints": ["Break each digit into its place value"],
                "explanation": "3,608 = 3,000 + 600 + 0 + 8, usually written 3,000 + 600 + 8 (the zero tens are skipped).",
            },
            {
                "type": "problem",
                "difficulty": 2,
                "prompt": "Which number is greater: 4,705 or 4,075?",
                "expected_type": "number",
                "correct_answer": "4705",
                "hints": ["Both have 4 thousands; compare the hundreds place next"],
                "explanation": "Both numbers have 4 thousands. In the hundreds place, 4,705 has 7 and 4,075 has 0, so 4,705 > 4,075.",
            },
            {
                "type": "problem",
                "difficulty": 3,
                "prompt": "Order these numbers from least to greatest: 5,280, 5,028, 5,820, 5,208.",
                "expected_type": "text",
                "hints": ["All have 5 thousands; compare the hundreds digit first"],
                "explanation": "Thousands all equal 5. Hundreds digits: 5,028 (0), 5,208 (2), 5,280 (2), 5,820 (8). Two share hundreds=2; compare tens: 5,208 (0) < 5,280 (8). Final order: 5,028; 5,208; 5,280; 5,820.",
            },
        ],
        "assessment_items": [
            {
                "prompt": "Write the standard form for: six thousand, two hundred forty.",
                "type": "number",
                "correct_answer": "6240",
                "target_concept": "word_form_to_standard",
            },
            {
                "prompt": "Write 4,506 in expanded form and in word form.",
                "type": "open_response",
                "rubric": "Mastery: writes 4,000 + 500 + 6 and 'four thousand, five hundred six' with the zero tens correctly skipped. Proficient: minor wording slip. Developing: includes 'zero tens' as a written term or miscounts a place.",
                "target_concept": "form_conversion",
            },
            {
                "prompt": "What is the value of the 8 in each number: 6,820, 6,082, 8,206?",
                "type": "open_response",
                "rubric": "Mastery: 800, 80, 8000 with correct place names. Proficient: correct values without naming the place. Developing: any value mis-identified.",
                "target_concept": "digit_value_by_position",
            },
        ],
        "resource_guidance": {
            "required": ["base-ten material including a thousand cube", "place-value chart with a thousands column", "digit cards 0 through 9"],
            "recommended": ["large numeral cards including 1000, 2000, ... 9000", "real receipts and headlines with four-digit numbers", "expanded-form notation cards"],
        },
        "time_estimates": {"first_exposure": 25, "practice_session": 15, "assessment": 15},
        "accommodations": {
            "dyslexia": "Always pair the spoken number with the written numeral, and use a place-value chart with named columns to anchor every digit. Read aloud slowly and let the child point to each digit as it is named.",
            "adhd": "Use building games (roll-and-build, race to write) so the practice has movement and immediate feedback. Short sessions, frequent re-encounters.",
            "gifted": "Extend into five- and six-digit numbers, and introduce the names ten thousand and hundred thousand briefly; revisit when intermediate band arrives.",
            "visual_learner": "Use color-coded place-value columns (thousands one color, hundreds another) and large numeral cards laid out spatially.",
            "kinesthetic_learner": "Build every four-digit number with materials at least once before writing it. Trade ten hundred-flats for a thousand-cube physically.",
            "auditory_learner": "Read every number aloud in place-value language; chant the place names in order (ones, tens, hundreds, thousands).",
        },
        "philosophy_specific": {
            "traditional": {
                "introduction": "Today we add a new column: the thousands. Ten hundreds make one thousand, just as ten ones make a ten. We will read, write, and compare four-digit numbers up to 9,999.",
                "gradual_release": {
                    "i_do": "Show a thousand cube next to ten hundred-flats and confirm by stacking that they are equal. Build the number 2,347 and read it aloud, naming each place: two thousand, three hundred, four tens, seven ones.",
                    "we_do": "Build three four-digit numbers together, child placing the materials while the parent says the place names, then swap roles. Convert each to expanded and word form on paper.",
                    "you_do": "Child reads, writes, and compares ten four-digit numbers independently, including some that share leading digits and require careful column-by-column comparison.",
                },
                "guided_practice": [
                    "Match standard-form and expanded-form cards for ten four-digit numbers",
                    "Order three sets of four numbers from least to greatest",
                    "Write the value of a circled digit in five different four-digit numbers",
                ],
                "independent_practice": [
                    "Worksheet: convert ten four-digit numbers among standard, expanded, and word form",
                    "Worksheet: compare and order three sets of four-digit numbers",
                ],
                "mastery_check": [
                    "Convert any four-digit number among the three forms with no error",
                    "Order four four-digit numbers correctly and explain reasoning by leading digits",
                    "Identify the value of any digit in any four-digit number",
                ],
                "spiral_review": [
                    "Continue three-digit place-value warm-ups for a week to keep the earlier work fluent",
                    "Daily reading of any four-digit number encountered in real life (sign, page, year)",
                ],
            },
            "classical": {
                "narrative_introduction": "Numbers run on and on, in the same orderly pattern, only the names change as we climb. To learn the thousand is to climb one more rung of a ladder that has no end. The scribes of old kept tallies running into the thousands, marking the harvest, the soldiers, the years, and they did it on the same place-value pattern we use now.",
                "memory_work": {
                    "chants": [
                        "Recite the climb of the columns: ones, tens, hundreds, thousands",
                        "Recite the rule: ten of a kind makes one of the next",
                        "Recite a worked example aloud in word form: four thousand, five hundred, sixty-eight",
                    ],
                    "recitations": [
                        "Recite the names of the four-digit numbers in a chosen list (population of a familiar city, distances between two places) until each runs without hesitation",
                    ],
                },
                "copywork": [
                    "Copy a small list of four-digit numbers in all three forms (standard, expanded, word) into the math copybook, neatly",
                ],
                "recitation_routine": "Begin each lesson by reciting the names of the columns and then reading aloud yesterday's set of four-digit numbers before introducing today's.",
                "history_integration": "Read a brief account of an old census or a great army numbered in the thousands, where the four-digit total mattered to the story.",
                "read_aloud_suggestions": [
                    "A passage from a history of cities or kingdoms in which populations, distances, or harvests are reported in the thousands",
                    "A short biography of an early census-taker, surveyor, or scribe",
                ],
            },
            "charlotte_mason": {
                "lesson_length_minutes": 15,
                "living_book_suggestions": [
                    "A real, beautifully written book that names large quantities in their natural setting: the population of a town, the leagues to a distant city, the years since an old event",
                    "An atlas or simple geography book that lists real four-digit numbers as a matter of course",
                ],
                "short_lesson_flow": "Open with a four-digit number found yesterday in real life (the year on a coin, the page count of a long book, the miles to a relative's home). Build the number with materials. Read it aloud in word form. Write it in expanded form together. Close while interest is still high.",
                "narration_prompt": "Tell me what 4,506 means in your own words. Where does each digit live, and what does it stand for?",
                "real_world_objects": [
                    "Base-ten material including a thousand cube",
                    "Coins, stamps, or buttons in a jar with the running total kept across days",
                    "An atlas open to a page of real distances, populations, and elevations",
                ],
                "nature_connection": "Estimate the leaves on a single tree, the blades of grass on a small lawn patch, or the steps along a familiar trail, and write the four-digit estimate in standard and word form.",
                "habit_focus": "The habit of attention to detail: every digit holds its place by its position, and reading carelessly across a comma leads to error. Read once, accurately.",
            },
            "montessori": {
                "prepared_materials": [
                    "Golden bead material: unit beads, ten-bars, hundred-squares, and the thousand cube",
                    "Large numeral cards 1 through 9000 (the hierarchy cards) for building four-digit numbers",
                    "Small numeral cards 1 through 9000 for the child's own work",
                    "Stamp game with the green thousand stamps for the next level of abstraction",
                ],
                "presentation": {
                    "three_period_lesson": "Show the thousand cube and name it; show the relation by stacking ten hundred-squares against the cube. Build a four-digit number with materials and the large hierarchy cards: lay each card over the next so the number is read as a whole.",
                    "steps": [
                        "Lay out the thousand cube and the hundred-squares; confirm by stacking that ten hundreds equals one thousand",
                        "Build a four-digit number in golden beads on a tray",
                        "Lay the large hierarchy cards over each other to display the same number in standard form",
                        "Read the number aloud: 'two thousand, three hundred, four tens, seven ones'",
                        "Move to small numeral cards for the child's independent work",
                        "When fluent, move to the stamp game with green thousand stamps",
                    ],
                },
                "control_of_error": "The materials and the hierarchy cards form the control: a misplaced card produces a number that does not match the beads on the tray, and the child sees and corrects without correction from outside.",
                "abstraction_pathway": "From golden beads (quantity felt) to hierarchy cards laid over beads (symbol over quantity) to small numeral cards (symbol alone) to the written numeral, then to the stamp game where color stands for category. Each step is taken when the prior one is effortless.",
                "extensions": [
                    "Build numbers with two zeros (3,007; 4,090) and read them, attending to the silent columns",
                    "Compare two built four-digit numbers and put them in order on the mat",
                    "Read aloud a list of four-digit numbers from a real geography book or atlas",
                ],
                "observation_focus": "Watch whether the child reads the silent zero columns correctly. Watch for the spontaneous comparison of two built numbers, the natural impulse to order, which signals readiness for the next operation.",
            },
            "unschooling": {
                "invitations": [
                    "Leave an old atlas, an almanac, or a population-of-cities book on the table, open to a real list of four-digit numbers",
                    "Put a coin jar with a visible running total in the kitchen and add to it daily",
                    "Set out a digit-card game (four cards, build the biggest number you can) on the shelf without explanation",
                ],
                "real_world_contexts": [
                    "Reading the year on a coin, a date on a tombstone, a page count on a long book",
                    "Tracking video-game high scores or sports statistics that run into the thousands",
                    "Reading the population of the family's town, the next town, and the nearest big city, and comparing",
                    "Watching the car's odometer roll over and predicting what comes next",
                ],
                "conversation_starters": [
                    "Which number is bigger, do you think? How can you tell quickly?",
                    "I wonder how many people live in our town. Want to look it up?",
                    "If our car has 8,742 miles on it, what will it say after a thousand more?",
                ],
                "resource_bank": [
                    "A real almanac or atlas accessible to the child",
                    "Number-themed picture books that quietly use four-digit values in context",
                    "A coin jar with a real running total kept openly",
                    "Online lookups for real four-digit facts: population, distance, year, when the child wonders",
                ],
                "parent_role": "Read four-digit numbers aloud in real life, often and casually. When the child asks how big or how far, look it up together. Never quiz; offer the wondering and follow the child's interest.",
                "observation_documentation": "Note across weeks where four-digit numbers came up in real life, whether the child reads them with confidence, and whether they spontaneously compare or estimate.",
            },
        },
        "connections": {
            "reading": "Reading and writing four-digit numerals fluently in real text: years, populations, distances, page counts",
            "science": "Reading population and species counts that run into the thousands in real natural-history sources",
            "history": "Reading dates in the thousands and reasoning about the gap between two historical events",
        },
    },
    "md-03": {
        "enriched": True,
        "learning_objectives": [
            "Add multi-digit numbers (three- and four-digit) using the standard algorithm with regrouping in any column",
            "Line up digits by place value before adding",
            "Estimate the sum first, solve exactly, and compare to check reasonableness",
            "Add three addends column by column, carrying when a column total reaches ten or more",
        ],
        "teaching_guidance": {
            "introduction": "The child already adds three-digit numbers using place-value reasoning. The standard algorithm is the same work written down in the most efficient form: a vertical column for each place, work from right to left, carry when a column reaches ten or more. The aim today is fluency, not invention; the meaning of the carry is already known, and now the writing of it becomes automatic.",
            "scaffolding_sequence": [
                "Line up two four-digit addends by place value on grid paper or a place-value chart",
                "Add the ones column first; if the sum is ten or more, write the ones digit and carry the tens digit above the tens column",
                "Add the tens column including any carried digit, repeat the carry rule",
                "Continue across hundreds and thousands columns, handling carries as they arise",
                "Estimate the sum first by rounding each addend to the nearest hundred or thousand",
                "Solve the exact sum and compare to the estimate; close means likely correct, far means recheck",
                "Practice with three addends: add the column total all the way (e.g., 7 + 8 + 9 = 24, write 4 carry 2)",
            ],
            "socratic_questions": [
                "Why do we always start with the ones column and move left?",
                "What does the little 1 above the tens column actually mean?",
                "Your estimate was 9,000 and you got 8,873; is that close enough to trust?",
                "If three numbers in one column add to 23, what do you write and what do you carry?",
            ],
            "practice_activities": [
                "Receipt addition: take a real grocery receipt and add the prices in dollars and cents using the algorithm",
                "Family-budget challenge: child given three or four real monthly amounts to total",
                "Race-and-check: child solves five problems by the algorithm, then re-solves each by an estimation strategy to verify",
            ],
            "real_world_connections": [
                "Adding the prices of items in a shopping basket",
                "Totaling distances across a multi-leg trip",
                "Adding page counts of books on a reading list",
                "Combining donation totals from several events",
            ],
            "common_misconceptions": [
                "Misaligning columns when one number has fewer digits (e.g., adding 47 to 1,205 by lining up to the left)",
                "Forgetting to add the carried digit into the next column",
                "Writing the full two-digit sum in one column instead of writing the ones digit and carrying the tens digit",
                "Treating the algorithm as magic rather than as a place-value shortcut",
            ],
        },
        "assessment_criteria": {
            "mastery_indicators": [
                "Solves four-digit + four-digit addition problems by the standard algorithm with 90% accuracy",
                "Lines up columns correctly even when addends have different numbers of digits",
                "Estimates before solving and uses the estimate to catch errors",
            ],
            "assessment_methods": ["timed and untimed paper algorithm work", "oral explanation of one worked problem", "estimation comparison"],
            "sample_assessment_prompts": [
                "Solve 3,478 + 2,659 by the standard algorithm. Show every carry.",
                "Solve 47 + 1,205 + 836. Be careful to line up the columns.",
                "Estimate 4,287 + 3,591 to the nearest thousand, then solve exactly.",
            ],
        },
        "practice_items": [
            {
                "type": "problem",
                "difficulty": 1,
                "prompt": "What is 1,234 + 4,521?",
                "expected_type": "number",
                "correct_answer": "5755",
                "hints": ["No regrouping needed; add column by column"],
                "explanation": "Ones: 4+1=5. Tens: 3+2=5. Hundreds: 2+5=7. Thousands: 1+4=5. Answer: 5,755.",
            },
            {
                "type": "problem",
                "difficulty": 2,
                "prompt": "What is 3,478 + 2,659?",
                "expected_type": "number",
                "correct_answer": "6137",
                "hints": ["You will need to carry in more than one column"],
                "explanation": "Ones: 8+9=17, write 7 carry 1. Tens: 7+5+1=13, write 3 carry 1. Hundreds: 4+6+1=11, write 1 carry 1. Thousands: 3+2+1=6. Answer: 6,137.",
            },
            {
                "type": "problem",
                "difficulty": 2,
                "prompt": "What is 47 + 1,205 + 836?",
                "expected_type": "number",
                "correct_answer": "2088",
                "hints": ["Line up the columns by place value", "47 has no thousands and no hundreds"],
                "explanation": "Stack with ones aligned: 47, 1205, 836. Ones: 7+5+6=18, write 8 carry 1. Tens: 4+0+3+1=8. Hundreds: 0+2+8=10, write 0 carry 1. Thousands: 0+1+0+1=2. Answer: 2,088.",
            },
            {
                "type": "problem",
                "difficulty": 3,
                "prompt": "Estimate 4,287 + 3,591 to the nearest thousand, then solve exactly. What is the exact sum?",
                "expected_type": "number",
                "correct_answer": "7878",
                "hints": ["Estimate: 4,000 + 4,000 = 8,000", "Solve column by column"],
                "explanation": "Estimate: 4,287 rounds to 4,000 and 3,591 rounds to 4,000; estimate 8,000. Exact: 4,287 + 3,591 = 7,878 (close to the estimate, so likely correct).",
            },
            {
                "type": "problem",
                "difficulty": 3,
                "prompt": "A school has 1,247 books in the library, 856 in the classrooms, and 392 in the office. How many books in total?",
                "expected_type": "number",
                "correct_answer": "2495",
                "hints": ["Add all three numbers column by column"],
                "explanation": "1,247 + 856 + 392. Ones: 7+6+2=15, carry 1. Tens: 4+5+9+1=19, carry 1. Hundreds: 2+8+3+1=14, carry 1. Thousands: 1+0+0+1=2. Total: 2,495 books.",
            },
        ],
        "assessment_items": [
            {
                "prompt": "Solve 5,839 + 2,476 by the standard algorithm.",
                "type": "number",
                "correct_answer": "8315",
                "target_concept": "four_digit_addition_with_regrouping",
            },
            {
                "prompt": "Solve 86 + 1,407 + 539. Show how you lined up the columns.",
                "type": "open_response",
                "rubric": "Mastery: correct sum 2,032 with columns clearly aligned by place value. Proficient: correct sum, alignment not shown. Developing: misalignment or wrong sum.",
                "target_concept": "column_alignment_with_uneven_addends",
            },
            {
                "prompt": "Estimate 6,318 + 2,795 to the nearest thousand. Then solve exactly. Is your estimate close to your answer?",
                "type": "open_response",
                "rubric": "Mastery: estimate 9,000, exact 9,113, compares meaningfully. Proficient: correct work without explicit comparison. Developing: errors in either step.",
                "target_concept": "estimate_then_verify",
            },
        ],
        "resource_guidance": {
            "required": ["grid paper or place-value chart", "pencil and eraser"],
            "recommended": ["base-ten blocks for review when algorithm slips", "real receipts for practice", "calculator for self-check after manual work"],
        },
        "time_estimates": {"first_exposure": 25, "practice_session": 15, "assessment": 15},
        "accommodations": {
            "dyslexia": "Always use grid paper or a place-value chart so each digit lives in its own box. Color-code the columns and the carried digits.",
            "adhd": "Short sets (three to five problems) with movement breaks. Use timers for short focused bursts, not for whole sessions.",
            "gifted": "Push to five- and six-digit addition and to adding four or five addends at once. Introduce mental-math regrouping for select cases.",
            "visual_learner": "Color-code each place-value column. Show the algorithm beside an expanded-form decomposition so the meaning of the carry stays visible.",
            "kinesthetic_learner": "Trade ten unit cubes for a tens rod physically as the carry is written, until the meaning is solid.",
            "auditory_learner": "Speak each step aloud: 'eight plus nine is seventeen, write seven, carry one.'",
        },
        "philosophy_specific": {
            "traditional": {
                "introduction": "Today we practice the standard algorithm for addition with three- and four-digit numbers. Line up the columns, work from right to left, and carry when a column reaches ten or more. We will estimate first and check our work against the estimate.",
                "gradual_release": {
                    "i_do": "Solve 3,478 + 2,659 on the board step by step, saying each move aloud: 'eight plus nine is seventeen, write seven, carry one to the tens.' Show the carried digit clearly above the next column.",
                    "we_do": "Work three problems together, with the child writing while the parent narrates the steps, then swap. Include one problem with addends of unequal length so column alignment is practiced.",
                    "you_do": "Child solves ten problems independently, estimating each one first and comparing the estimate to the answer.",
                },
                "guided_practice": [
                    "Solve five four-digit addition problems on grid paper, showing every carry",
                    "Solve three problems with three addends each",
                    "Solve three problems with addends of different lengths, aligning columns by place value",
                ],
                "independent_practice": [
                    "Worksheet of ten mixed multi-digit addition problems with estimation column on the side",
                    "Word-problem set: five real-world story problems requiring multi-digit addition",
                ],
                "mastery_check": [
                    "Solve eight of ten four-digit addition problems correctly on first try",
                    "Align columns correctly even when addends have unequal digit counts",
                    "Catch at least one unreasonable answer per ten-problem set by comparing to the estimate",
                ],
                "spiral_review": [
                    "Three-digit addition warm-ups for one week before each session to keep the algorithm fluent",
                    "Random place-value question at the start of each lesson",
                ],
            },
            "classical": {
                "narrative_introduction": "The standard algorithm is the gathered wisdom of many generations of reckoners. It is the shortest written form of the place-value thinking we already know, and it is worth practicing until the hand runs without hesitation. To master it is to inherit a tool the world has used for centuries.",
                "memory_work": {
                    "chants": [
                        "Recite the rule: line them up, right to left, carry when ten or more",
                        "Recite the columns: ones, tens, hundreds, thousands",
                        "Recite the estimate rule: round, reckon, compare",
                    ],
                    "recitations": [
                        "Recite a fully worked four-digit addition aloud in algorithm steps until it runs cleanly",
                    ],
                },
                "copywork": [
                    "Copy three fully worked four-digit addition problems into the math copybook, with the carries written above their columns, neat and exact",
                ],
                "recitation_routine": "Begin each lesson by reciting the algorithm rule and reading aloud yesterday's worked example before adding today's.",
                "history_integration": "Tell briefly that the place-value algorithm came to the West through Arabic mathematicians and replaced the older Roman system that could not easily handle long sums; the child practices a tool that quietly changed the world.",
                "read_aloud_suggestions": [
                    "A short passage about the spread of Hindu-Arabic numerals into Europe (a chapter from a children's history of mathematics)",
                    "A story of a merchant or a treasurer where careful addition of long sums matters to the plot",
                ],
            },
            "charlotte_mason": {
                "lesson_length_minutes": 15,
                "living_book_suggestions": [
                    "A real, well-illustrated arithmetic book that grounds the algorithm in meaningful, lifelike sums",
                    "A story or biography that includes a careful merchant or treasurer at work with long sums",
                ],
                "short_lesson_flow": "Begin with a short mental warm-up of three-digit sums. Pose one real, lifelike problem: total the family's grocery week, the books read this term, the steps walked across a weekend. Work the problem together using the algorithm, on grid paper. Estimate first, solve, compare. Close while interest is still high.",
                "narration_prompt": "Tell me how you solved that sum. Where did you carry, and what did the carry mean?",
                "real_world_objects": [
                    "Grid paper or a quiet, beautiful math copybook",
                    "Real receipts and bills from the household kept and totaled",
                    "Coins or play money for the occasional concrete check",
                ],
                "nature_connection": "Total real outdoor counts across days: birds at the feeder this week, blossoms on a flowering tree, steps along a familiar trail across several visits. The algorithm becomes the way we make sense of real, accumulating quantities.",
                "habit_focus": "The habit of accuracy and the habit of estimation: a careful reckoner estimates before solving, so an unreasonable answer is noticed at once.",
            },
            "montessori": {
                "prepared_materials": [
                    "Golden bead material for review of regrouping when the algorithm slips",
                    "Stamp game for the next level of abstraction: color stands for category, the operation is recorded on paper",
                    "Small bead frame for the abstract operation with no bulk to move",
                    "Numeral cards 1 through 9000 for building addends and reading sums",
                ],
                "presentation": {
                    "three_period_lesson": "No new naming; the work is the abstract form of operations long since shown with the golden beads. The presentation is the silent, careful working of one full problem on the stamp game and then on the small bead frame, with the written record beside it.",
                    "steps": [
                        "Build the two addends with stamps or on the small bead frame",
                        "Combine the units; if ten or more, exchange ten units for one ten and place with the tens",
                        "Combine the tens with any exchange; then the hundreds; then the thousands",
                        "Write the sum on paper beside the material, then on paper alone for the next problem",
                        "Return to the golden beads if the child's confidence falters",
                    ],
                },
                "control_of_error": "The materials are the control: the result on the stamp game or bead frame must match the result on paper, and any miscarriage reveals itself in the disagreement.",
                "abstraction_pathway": "From golden beads (quantity) to stamp game (color for category) to small bead frame (one bead per unit, columns set) to written algorithm with no material. Each step taken only when the prior one is effortless.",
                "extensions": [
                    "Work problems with three and four addends at the stamp game",
                    "Move to five- and six-digit problems on the small bead frame",
                    "Build a personal bank of problems written from real life and solved at the shelf across several days",
                ],
                "observation_focus": "Watch the natural movement toward the paper as the materials become unnecessary; the child who returns to the bead frame on a hard problem is showing exactly the kind of self-correction the method seeks.",
            },
            "unschooling": {
                "invitations": [
                    "Leave a stack of real receipts and a small clipboard on the kitchen counter with a casual suggestion to total a few",
                    "Put a calculator and a notebook side by side and challenge: 'solve by hand first, check with the calculator, who is faster on small ones?'",
                    "Set out a board game like Monopoly where running totals matter, and join in",
                ],
                "real_world_contexts": [
                    "Totaling a grocery basket or a restaurant check before the cashier does",
                    "Adding running totals in a board game or video game",
                    "Adding step counts, miles run, books read, pages written across a week or month",
                    "Combining donation amounts from a school fundraiser",
                ],
                "conversation_starters": [
                    "How much do you think these together will cost?",
                    "Want to add this list of three before I do?",
                    "If your estimate is 6,000 and the answer is 8,500, is one of us off?",
                ],
                "resource_bank": [
                    "Real receipts kept in a basket for whenever the mood strikes",
                    "A calculator accessible for self-checking, not for replacing the work",
                    "Open-ended games involving running totals",
                    "A simple notebook for keeping personal records: pages read, miles walked, dollars saved",
                ],
                "parent_role": "Add aloud in real life often, modeling estimation and a clean column-by-column algorithm whenever it comes up. Welcome rough answers and refinements. Never quiz; offer the wonder of the real number question.",
                "observation_documentation": "Note across weeks where multi-digit addition arose, whether the child reached for paper or mental strategies, whether they estimated first, and whether their results were reliably correct.",
            },
        },
        "connections": {
            "reading": "Reading prices, distances, dates, and page counts that must be totaled accurately",
            "science": "Totaling counts and measurements across multiple observations in a single project",
            "history": "Reckoning years between events on a long timeline by careful addition",
        },
    },
}
