"""Pre-enriched content for Reading Foundational template nodes."""

READING_FOUNDATIONAL_CONTENT = {
    "rf-01": {
        "enriched": True,
        "learning_objectives": ["Identify all 26 uppercase letters by name", "Identify all 26 lowercase letters by name", "Match uppercase to lowercase letters", "Distinguish letters from numbers and symbols"],
        "teaching_guidance": {
            "introduction": "Letters are the building blocks of reading. Each has a name, a shape (two shapes: uppercase and lowercase), and sounds. Start with the letters in the child's own name, making learning personal and meaningful.",
            "scaffolding_sequence": ["Learn letters in the child's first name", "Learn uppercase letters in groups of 3-4 using multisensory methods", "Practice identifying learned letters in real books and signs", "Introduce lowercase alongside uppercase partners", "Match uppercase-lowercase pairs through games and sorting", "Identify all 26 in random order, both cases"],
            "socratic_questions": ["What letter does your name start with? Can you find it on this page?", "This letter looks like that one. How are they different?", "Can you find the letter M hiding somewhere in this room?"],
            "practice_activities": ["Letter hunt: find specific letters in books, signs, packaging", "Form letters with playdough, sand, or finger paint", "Sort magnetic letters into uppercase and lowercase"],
            "real_world_connections": ["Reading stop signs and store names", "Finding letters on a keyboard", "Letters on license plates during car rides"],
            "common_misconceptions": ["Confusing b/d, p/q, m/w (normal at this age, not dyslexia)", "Thinking uppercase and lowercase are different letters", "Confusing letter names with letter sounds"],
        },
        "assessment_criteria": {
            "mastery_indicators": ["Names all 26 uppercase letters in random order", "Names all 26 lowercase letters in random order", "Matches all uppercase-lowercase pairs"],
            "assessment_methods": ["letter card identification", "letter sorting", "environmental print reading"],
            "sample_assessment_prompts": ["What letter is this? (random cards)", "Match these uppercase letters with lowercase partners", "Find 5 letters you know on this cereal box"],
        },
        "practice_items": [
            {"type": "problem", "difficulty": 1, "prompt": "What letter is this: A", "expected_type": "text", "correct_answer": "A", "hints": ["This is the first letter of the alphabet"], "explanation": "This is the letter A, the first letter of the alphabet."},
            {"type": "problem", "difficulty": 1, "prompt": "Is this a letter or a number: 7", "expected_type": "text", "correct_answer": "number", "hints": ["Letters are in the alphabet. Numbers are for counting."], "explanation": "7 is a number, not a letter."},
            {"type": "problem", "difficulty": 2, "prompt": "What is the lowercase partner of B?", "expected_type": "text", "correct_answer": "b", "hints": ["The lowercase version is smaller and shaped a bit differently"], "explanation": "The lowercase partner of B is b."},
            {"type": "problem", "difficulty": 2, "prompt": "Which two letters look very similar: b and d, or b and z?", "expected_type": "text", "correct_answer": "b and d", "hints": ["One pair is a mirror image"], "explanation": "b and d look similar because they are mirror images. This is why many children confuse them."},
            {"type": "problem", "difficulty": 3, "prompt": "Name 5 letters you can find in the word ELEPHANT.", "expected_type": "text", "hints": ["Look at each letter one at a time"], "explanation": "E, L, E, P, H, A, N, T. Any 5 of these: E, L, P, H, A, N, T."},
        ],
        "assessment_items": [
            {"prompt": "Name this letter (show random uppercase).", "type": "text", "target_concept": "uppercase_recognition", "rubric": "Mastery: names instantly. Proficient: names with brief hesitation. Developing: confuses with similar letters."},
            {"prompt": "Name this letter (show random lowercase).", "type": "text", "target_concept": "lowercase_recognition", "rubric": "Mastery: names all instantly. Proficient: hesitates on q, g, j. Developing: confuses b/d, p/q."},
            {"prompt": "Match these 10 uppercase letters with their lowercase partners.", "type": "open_response", "target_concept": "case_matching", "rubric": "Mastery: 10/10 correct. Proficient: 8-9 correct. Developing: 5-7 correct."},
        ],
        "resource_guidance": {"required": ["alphabet cards (upper and lowercase)", "alphabet books"], "recommended": ["magnetic letters", "sandpaper letters", "alphabet puzzles"]},
        "time_estimates": {"first_exposure": 15, "practice_session": 10, "assessment": 5},
        "accommodations": {"dyslexia": "Multisensory essential: see it, say it, trace it, build it. Extra time on b/d/p/q.", "adhd": "Letter hunts with movement. 2-3 letters per session max. Use games.", "gifted": "Move to letter sounds once names are solid. Begin CVC blending early.", "visual_learner": "Large colorful letter cards. Letter wall display.", "kinesthetic_learner": "Sandpaper letters. Form with playdough. Write in sand trays.", "auditory_learner": "Alphabet song variations. Say letter name while tracing."},
        "philosophy_specific": {"classical": "Systematic letter instruction with daily review and recitation.", "charlotte_mason": "Letters discovered in living books and the natural environment.", "montessori": "Sandpaper letters for tactile learning. Movable alphabet.", "traditional": "Letter-of-the-week curriculum. Worksheets and tracing."},
        "connections": {"math": "Alphabetical order is sequential like number order", "science": "Labeling nature journal drawings", "history": "Letters as symbols: ancient alphabets"},
    },
    "rf-02": {
        "enriched": True,
        "learning_objectives": ["Segment spoken words into individual sounds", "Blend individual sounds to form words", "Identify beginning, middle, and ending sounds", "Manipulate sounds: add, delete, and substitute phonemes"],
        "teaching_guidance": {
            "introduction": "Phonemic awareness is the ability to hear and work with individual sounds in spoken words. This happens WITHOUT print. It is purely auditory. The child listens, speaks, and manipulates sounds with their ears and voice before ever connecting sounds to letters.",
            "scaffolding_sequence": ["Identify rhyming words: do cat and hat rhyme?", "Isolate beginning sounds: what sound does 'dog' start with?", "Isolate ending sounds: what sound does 'cat' end with?", "Segment words into sounds: 'map' has three sounds: /m/ /a/ /p/", "Blend sounds into words: /s/ /u/ /n/ makes 'sun'", "Manipulate: change /c/ in 'cat' to /b/ and you get 'bat'"],
            "socratic_questions": ["What sound do you hear at the beginning of 'fish'?", "If I say /d/ /o/ /g/, what word am I saying?", "What happens if I change the /c/ in 'cap' to /m/?"],
            "practice_activities": ["Rhyming games: I say cat, you say a word that rhymes", "Sound boxes: push a counter into a box for each sound", "I Spy by sound: I spy something that starts with /b/"],
            "real_world_connections": ["Hearing rhymes in songs and poems", "Playing I Spy with beginning sounds", "Clapping syllables in names"],
            "common_misconceptions": ["Confusing letter names with letter sounds", "Thinking phonemic awareness requires letters (it doesn't)", "Struggling with middle vowel sounds (hardest position)"],
        },
        "assessment_criteria": {
            "mastery_indicators": ["Segments a CVC word into 3 sounds accurately", "Blends 3 sounds into a word", "Substitutes beginning sounds to make new words"],
            "assessment_methods": ["oral segmenting", "oral blending", "sound manipulation games"],
            "sample_assessment_prompts": ["Tell me each sound in the word 'sit'", "What word do these sounds make: /r/ /u/ /n/?", "Change the first sound in 'hat' to /s/. What word?"],
        },
        "practice_items": [
            {"type": "problem", "difficulty": 1, "prompt": "Do 'cat' and 'bat' rhyme?", "expected_type": "text", "correct_answer": "yes", "hints": ["Rhyming words end with the same sound"], "explanation": "Yes, cat and bat rhyme because they both end with the /at/ sound."},
            {"type": "problem", "difficulty": 1, "prompt": "What sound does 'sun' start with?", "expected_type": "text", "correct_answer": "/s/", "hints": ["Say 'sun' slowly and listen to the very first sound"], "explanation": "Sun starts with the /s/ sound."},
            {"type": "problem", "difficulty": 2, "prompt": "What word do these sounds make: /c/ /a/ /t/?", "expected_type": "text", "correct_answer": "cat", "hints": ["Push the sounds together smoothly"], "explanation": "Blending /c/ /a/ /t/ together makes 'cat'."},
            {"type": "problem", "difficulty": 2, "prompt": "How many sounds are in the word 'ship'?", "expected_type": "number", "correct_answer": "3", "hints": ["sh makes ONE sound, not two"], "explanation": "Ship has 3 sounds: /sh/ /i/ /p/. The 'sh' is one sound even though it uses two letters."},
            {"type": "problem", "difficulty": 3, "prompt": "Change the /m/ in 'map' to /t/. What new word do you get?", "expected_type": "text", "correct_answer": "tap", "hints": ["Keep the /a/ /p/ the same, just change the first sound"], "explanation": "Changing /m/ to /t/ in 'map' makes 'tap'."},
        ],
        "assessment_items": [
            {"prompt": "Segment 'dog' into its individual sounds.", "type": "text", "correct_answer": "/d/ /o/ /g/", "target_concept": "segmenting"},
            {"prompt": "Blend these sounds: /f/ /i/ /sh/. What word?", "type": "text", "correct_answer": "fish", "target_concept": "blending"},
            {"prompt": "Say 'stop' without the /s/. What word is left?", "type": "text", "correct_answer": "top", "target_concept": "deletion"},
        ],
        "resource_guidance": {"required": ["no materials needed - this is purely oral"], "recommended": ["sound boxes with counters", "Elkonin boxes"]},
        "time_estimates": {"first_exposure": 15, "practice_session": 10, "assessment": 10},
        "accommodations": {"dyslexia": "Phonemic awareness is often the core deficit. Go slowly. Extra repetition. Multisensory: tap sounds on arm.", "adhd": "Quick oral games. Stand up and sit down for each sound. Rhyming competitions.", "gifted": "Move quickly to 4-5 phoneme words. Phoneme addition and deletion.", "visual_learner": "Use colored counters in sound boxes to visualize each sound.", "kinesthetic_learner": "Tap arm for each sound. Jump for each sound. Physical segmenting.", "auditory_learner": "Pure strength area. Rhyming games, songs, chants."},
        "philosophy_specific": {"classical": "Systematic phonemic awareness drills before phonics instruction.", "charlotte_mason": "Nursery rhymes and poetry build phonemic awareness naturally.", "montessori": "I Spy game: 'I spy something beginning with /b/.' Sound games.", "traditional": "Structured phonemic awareness program with daily practice."},
        "connections": {"math": "Counting sounds in words is like counting objects", "science": "Listening carefully to identify sounds in nature", "history": "Oral traditions: stories passed down by sound"},
    },
    "rf-03": {
        "enriched": True,
        "learning_objectives": ["Produce the sound each consonant makes", "Identify consonant sounds in initial position", "Identify consonant sounds in final position", "Distinguish between similar consonant sounds"],
        "teaching_guidance": {
            "introduction": "Now we connect sounds to letters. Each consonant letter makes a specific sound. B says /b/, D says /d/, M says /m/. Start with letters that have consistent sounds (b, d, f, h, j, k, l, m, n, p, r, s, t, v, w, z) before introducing letters with multiple sounds (c, g) or silent letters.",
            "scaffolding_sequence": ["Introduce 3-4 consonant sounds at a time with picture cards", "Practice initial sounds: B is for ball, boat, bear", "Practice final sounds: what sound does 'web' end with?", "Distinguish similar sounds: /b/ vs /p/, /d/ vs /t/, /f/ vs /v/", "Identify consonant sounds in any position", "Apply to reading: see the letter, say the sound"],
            "socratic_questions": ["What sound does the letter T make? What words start with that sound?", "Do B and P sound the same? How are they different?", "What letter makes the last sound in the word 'dog'?"],
            "practice_activities": ["Picture sorts: sort pictures by beginning sound", "Sound-letter matching: hear a sound, point to the letter", "Beginning sound bingo"],
            "real_world_connections": ["Letters on street signs make sounds", "First letter of your name makes your name's first sound", "Sounding out simple words on food packages"],
            "common_misconceptions": ["Adding a vowel to consonant sounds: saying 'buh' instead of /b/", "Confusing voiced/unvoiced pairs: b/p, d/t, g/k", "Not realizing c can say /k/ or /s/"],
        },
        "assessment_criteria": {
            "mastery_indicators": ["Produces correct sound for 21 consonant letters", "Identifies beginning consonant sound in 10 words", "Identifies ending consonant sound in 10 words"],
            "assessment_methods": ["letter-sound cards", "picture sorts by sound", "oral identification"],
            "sample_assessment_prompts": ["What sound does this letter make? (flash cards)", "What letter makes the first sound in 'tiger'?", "What letter makes the last sound in 'drum'?"],
        },
        "practice_items": [
            {"type": "problem", "difficulty": 1, "prompt": "What sound does the letter M make?", "expected_type": "text", "correct_answer": "/m/", "hints": ["Think of words: mom, map, milk"], "explanation": "M makes the /m/ sound, like in 'mom'."},
            {"type": "problem", "difficulty": 1, "prompt": "What letter makes the first sound in 'dog'?", "expected_type": "text", "correct_answer": "d", "hints": ["Say 'dog' slowly. What's the first sound? What letter makes that sound?"], "explanation": "Dog starts with /d/, which is the letter D."},
            {"type": "problem", "difficulty": 2, "prompt": "What letter makes the LAST sound in 'cat'?", "expected_type": "text", "correct_answer": "t", "hints": ["Say 'cat' and listen to the very end"], "explanation": "Cat ends with the /t/ sound, which is the letter T."},
            {"type": "problem", "difficulty": 2, "prompt": "Name 3 words that start with the /s/ sound.", "expected_type": "text", "hints": ["Think of things you can see: sun, sand, ..."], "explanation": "Examples: sun, sit, soap, sand, six, snake."},
            {"type": "problem", "difficulty": 3, "prompt": "The letters B and P sound similar. What is different about them?", "expected_type": "text", "hints": ["Put your hand on your throat. Say /b/, then say /p/."], "explanation": "B is voiced (your throat vibrates) and P is unvoiced (just a puff of air). They are made in the same mouth position."},
        ],
        "assessment_items": [
            {"prompt": "Say the sound for each letter: T, S, M, B, R.", "type": "open_response", "target_concept": "consonant_sounds", "rubric": "Mastery: all 5 correct and clean (no added vowel). Proficient: 4-5 correct. Developing: adds vowel sounds ('tuh' instead of /t/)."},
            {"prompt": "What letter makes the first sound in 'jump'?", "type": "text", "correct_answer": "j", "target_concept": "initial_consonant"},
            {"prompt": "What letter makes the last sound in 'bell'?", "type": "text", "correct_answer": "l", "target_concept": "final_consonant"},
        ],
        "resource_guidance": {"required": ["letter-sound cards", "picture cards for sorting"], "recommended": ["alphabet chart with pictures", "sound wall"]},
        "time_estimates": {"first_exposure": 20, "practice_session": 15, "assessment": 10},
        "accommodations": {"dyslexia": "Extra time on voiced/unvoiced pairs. Multisensory: feel throat vibration for voiced sounds.", "adhd": "Quick-fire letter-sound games. Sort picture cards physically. 5-minute focused sessions.", "gifted": "Move quickly through consistent consonants. Introduce c/g duality and silent letters early.", "visual_learner": "Letter-sound cards with pictures. Sound wall display.", "kinesthetic_learner": "Mouth position awareness: feel where tongue and lips go for each sound.", "auditory_learner": "Pure auditory drills: hear the sound, name the letter. Sound discrimination games."},
        "philosophy_specific": {"classical": "Systematic phonics: one sound per lesson, mastered before moving on.", "charlotte_mason": "Consonant sounds learned through real words in living books.", "montessori": "Sandpaper letters: trace while saying the sound. I Spy with letter sounds.", "traditional": "Letter-sound flashcards. Daily drill and practice."},
        "connections": {"math": "Letters and numbers are both symbols that represent something", "science": "Initial sounds of animal names during nature study", "history": "The invention of the alphabet: how humans started writing sounds"},
    },
}
