"""Pre-enriched content for Science Foundational template nodes."""

SCIENCE_FOUNDATIONAL_CONTENT = {
    "sf-01": {
        "enriched": True,
        "learning_objectives": [
            "Use all five senses (sight, hearing, touch, smell, taste where safe) to observe objects and the natural world",
            "Describe an object using at least 3 senses with specific, accurate language",
            "Record observations in a science notebook using both words and drawings",
            "Explain that science begins with careful observation — paying close attention to what is really there",
        ],
        "teaching_guidance": {
            "introduction": "Science begins with paying attention. Before a child can understand WHY leaves change color or HOW magnets work, they must learn to OBSERVE — to really look, listen, touch, smell, and (when safe) taste the world around them. The five senses are a scientist's first tools. A child who can describe an apple as 'red, smooth, cool, slightly sweet-smelling, and crunchy when bitten' is doing real science: careful, accurate observation using multiple senses. This foundational skill makes every future science topic richer.",
            "scaffolding_sequence": [
                "Start with a familiar object (an apple, a pinecone, a rock): hold it, look at it carefully, and describe what you SEE",
                "Add another sense: close your eyes and describe what you FEEL. Is it smooth? Rough? Heavy? Warm? Cool?",
                "Add hearing: shake it, tap it, roll it. Does it make a sound? Describe what you HEAR.",
                "Add smell: carefully smell the object. Describe the smell. Not everything has a smell — that's an observation too!",
                "Add taste (only with food items): describe the taste using specific words (sweet, sour, salty, bitter, crunchy, soft)",
                "Record the observations: draw the object in a science notebook and write describing words for each sense used",
                "Go outdoors: observe a tree, a patch of grass, or the sky using all applicable senses. Record in the notebook.",
                "Compare observations: two children observe the same object. Did they notice the same things? Different things? Both are valid science.",
            ],
            "socratic_questions": [
                "You said the rock is 'brown.' Can you be more specific? What KIND of brown? Are there other colors mixed in?",
                "Close your eyes and hold this pinecone. Describe everything your hands can tell you about it without looking.",
                "We're standing outside. What sounds do you hear? How many different sounds can you count?",
                "Why do you think scientists write down their observations instead of just remembering them?",
            ],
            "practice_activities": [
                "Mystery bag: put objects in a paper bag. The child reaches in WITHOUT looking and describes what they feel. Can they identify the object by touch alone?",
                "Sound walk: go outside, stand still for 2 minutes, and list every different sound you hear. Compare lists with a family member.",
                "Nature observation station: place a natural object (leaf, flower, stone) on a table with a magnifying glass. The child draws it and writes observations for each sense.",
                "Smell jars: put different items in opaque jars (cinnamon, coffee, lemon peel, soil). The child identifies each by smell alone.",
            ],
            "real_world_connections": [
                "Cooking uses all five senses: watching bread rise (sight), hearing it sizzle (hearing), feeling dough (touch), smelling it bake (smell), tasting the result (taste)",
                "Doctors use observation: looking at skin color, listening with a stethoscope, feeling for swelling — medical science starts with senses",
                "Weather observation is daily five-senses science: see the clouds, feel the wind, hear the rain, smell the air after a storm",
                "Nature walks are automatic science labs: every step brings new things to observe with every sense",
            ],
            "common_misconceptions": [
                "Thinking observation means only LOOKING — observation uses ALL available senses, not just sight",
                "Believing that descriptions should be vague ('it's nice' or 'it's brown') — scientific observation requires SPECIFIC language: 'The bark is rough, dark gray with light patches, and smells earthy.'",
                "Assuming observation is passive — good observation is ACTIVE: the child chooses what to focus on, examines carefully, and records precisely",
                "Thinking we should always use all 5 senses — taste should only be used with known-safe food items. Safety is part of science too.",
            ],
        },
        "assessment_criteria": {
            "mastery_indicators": [
                "Describes an object using at least 4 senses with specific language",
                "Records observations accurately in a science notebook with drawings and words",
                "Explains that science starts with careful observation",
            ],
            "proficiency_indicators": [
                "Describes using 2-3 senses",
                "Records observations but with limited detail",
            ],
            "developing_indicators": [
                "Describes using only sight",
                "Uses vague language ('it's nice') rather than specific observations",
            ],
            "assessment_methods": ["multi-sense observation exercise", "science notebook review", "observation comparison"],
            "sample_assessment_prompts": [
                "Describe this object using as many senses as you can. Be as specific as possible.",
                "Show me your science notebook. Point to an observation where you used 3 or more senses.",
                "Why is careful observation important in science?",
            ],
        },
        "practice_items": [
            {
                "type": "problem",
                "difficulty": 1,
                "prompt": "Name the five senses and the body part used for each one.",
                "expected_type": "text",
                "hints": ["Think about: eyes see, ears hear... what about the other three?"],
                "explanation": "The five senses: sight (eyes), hearing (ears), touch (skin/hands), smell (nose), taste (tongue). Each sense gives us different information about the world around us.",
            },
            {
                "type": "problem",
                "difficulty": 1,
                "prompt": "Which sense would you use to find out if a rock is smooth or rough?",
                "expected_type": "multiple_choice",
                "options": ["Sight", "Touch", "Hearing", "Taste"],
                "correct_answer": "Touch",
                "hints": ["Smooth and rough describe how something FEELS."],
                "explanation": "Touch tells you about texture: smooth, rough, bumpy, soft, hard. You would hold the rock and feel its surface with your fingers.",
            },
            {
                "type": "problem",
                "difficulty": 2,
                "prompt": "Go outside and stand still for 1 minute. List at least 5 things you observe using different senses.",
                "expected_type": "text",
                "hints": ["Use multiple senses: What do you SEE? HEAR? FEEL (wind, temperature)? SMELL?"],
                "explanation": "A good observation list uses multiple senses: 'I see white clouds. I hear birds singing. I feel warm wind on my face. I smell cut grass. I see an ant carrying a crumb.' Specific, multi-sense observations are the foundation of science.",
            },
            {
                "type": "problem",
                "difficulty": 2,
                "prompt": "True or false: Scientists should always taste things they are observing.",
                "expected_type": "true_false",
                "correct_answer": "false",
                "hints": ["Is it safe to taste everything? What about chemicals, unknown plants, or dirty things?"],
                "explanation": "False! Taste should ONLY be used with items known to be safe (food items). Never taste unknown substances, chemicals, or wild plants. Safety is an important part of scientific practice.",
            },
            {
                "type": "problem",
                "difficulty": 3,
                "prompt": "Pick any natural object near you (a leaf, rock, flower, or piece of fruit). Draw it in your science notebook and describe it using at least 3 different senses. Be as specific as possible.",
                "expected_type": "text",
                "hints": ["Look at it carefully: color, shape, size. Feel it: texture, weight, temperature. Smell it. Describe each observation with precise words."],
                "explanation": "A strong observation includes specific details for each sense used. Example for a leaf: 'SIGHT: oval shape, dark green on top, lighter underneath, veins branching from the center. TOUCH: smooth and waxy on top, slightly fuzzy underneath, thin and flexible. SMELL: faintly earthy, fresh.' This level of detail is real scientific observation.",
            },
        ],
        "assessment_items": [
            {
                "prompt": "Describe this object using all applicable senses.",
                "type": "open_response",
                "target_concept": "multi_sense_observation",
                "rubric": "Mastery: 4+ senses with specific language. Proficient: 2-3 senses. Developing: sight only, vague descriptions.",
            },
            {
                "prompt": "Why do scientists write down their observations?",
                "type": "open_response",
                "target_concept": "recording_observations",
                "rubric": "Mastery: explains accuracy, memory, sharing, comparison. Proficient: says 'to remember.' Developing: cannot explain.",
            },
        ],
        "resource_guidance": {
            "required": ["science notebook (blank or lined)", "natural objects for observation (rocks, leaves, shells)"],
            "recommended": ["magnifying glass", "collection of objects with interesting textures and smells"],
            "philosophy_specific": {
                "classical": "Structured observation with scientific vocabulary: classify observations by sense, record systematically, memorize the five senses and their functions.",
                "charlotte_mason": "Nature study begins here: the child learns to LOOK at the world with attention and wonder. Original drawings from life in the nature notebook. Outdoor observation is primary.",
                "montessori": "Sensorial materials refine each sense: rough/smooth boards, color tablets, sound cylinders, smelling bottles. Then apply refined senses to nature observation.",
            },
        },
        "time_estimates": {"first_exposure": 20, "practice_session": 15, "assessment": 10},
        "accommodations": {
            "dyslexia": "Observation is primarily sensory, not text-based. Record observations through drawing with verbal labels dictated to parent. Voice recordings of observations. Real objects over written descriptions.",
            "adhd": "Outdoor observation walks channel energy. Mystery bag and smell jars are engaging games. Keep indoor observation to 10 minutes. Drawing observations keeps hands busy. Movement-based: walk to find things to observe.",
            "gifted": "Introduce the concept of quantitative vs qualitative observations (measuring vs describing). Begin using a magnifying glass for micro-observations. Start a year-long observation project (a tree through the seasons).",
            "visual_learner": "Magnifying glass work. Detailed drawings. Color comparisons. Close-up photography of natural objects.",
            "kinesthetic_learner": "Touch-based exploration is primary. Nature walks with physical collection. Sorting objects by texture. Building with natural materials.",
            "auditory_learner": "Sound walks and listening exercises. Describe observations aloud before drawing. Discuss observations as a conversation.",
        },
        "connections": {
            "reading": "Descriptive language in science builds vocabulary used in reading and writing: smooth, rough, translucent, pungent, brittle",
            "math": "Measurement is quantitative observation: how long, how heavy, how many. Science observation leads naturally to measurement.",
            "history": "Historical observation: examining artifacts uses the same careful looking skills as science observation",
        },
    },
    "sf-02": {
        "enriched": True,
        "learning_objectives": [
            "Distinguish living things from nonliving things by identifying characteristics of life",
            "List at least 4 characteristics of living things: they grow, reproduce, need food and water, and respond to their environment",
            "Sort 10 objects correctly into living and nonliving categories with explanations",
            "Identify tricky cases (dead things, things that seem alive but aren't) and explain the reasoning",
        ],
        "teaching_guidance": {
            "introduction": "One of the first big questions in science is: what makes something ALIVE? A dog is alive. A rock is not. But WHY? Living things share characteristics: they grow, they reproduce (make more of themselves), they need food and water, and they respond to their environment (a plant turns toward sunlight, a cat runs from a loud noise). This classification — living vs nonliving — is the foundation of all biology. Once a child can identify what is alive, they can begin to study HOW life works.",
            "scaffolding_sequence": [
                "Take a nature walk and collect 10 items: leaves, rocks, sticks, feathers, acorns, pebbles, flowers, pine cones, soil, shells",
                "Sort the collection into two piles: 'things that are or were alive' and 'things that were never alive'",
                "Introduce the characteristics of life: grows, reproduces, needs food/water, responds to environment. Check each item against these criteria.",
                "Discuss tricky cases: a dead leaf WAS alive (it's a previously living thing). A cloud MOVES but was never alive (movement alone doesn't mean life).",
                "Classify pictures of objects: a fire (not alive — it grows and moves but doesn't reproduce or eat), a crystal (not alive — it 'grows' but doesn't reproduce or eat)",
                "Introduce the term 'organism' for living things: plants, animals, fungi, and bacteria are all organisms",
                "Apply to the child's world: 'Is your pet alive? Is your toy? How do you know?'",
                "Create a living/nonliving poster with drawings and labels for each category",
            ],
            "socratic_questions": [
                "A fire grows and moves. Is it alive? Why or why not?",
                "A dead tree is lying on the ground. Is it a living thing or a nonliving thing? It WAS alive... so what is it now?",
                "Your toy robot moves and makes sounds. Is it alive? What characteristics of life is it missing?",
                "If an alien visited Earth, how would they figure out which things here are alive?",
            ],
            "practice_activities": [
                "Nature walk sorting: collect 10 natural objects and sort them into living, once-living, and never-living categories",
                "Living/nonliving scavenger hunt: walk through the house and list 5 living and 5 nonliving things with explanations",
                "Tricky cases debate: is a seed alive? Is a virus alive? Is fire alive? Discuss using the characteristics of life.",
                "Characteristics of life checklist: for any object, check off which characteristics of life it has. Four or more? It's (or was) alive!",
            ],
            "real_world_connections": [
                "Food comes from living things: fruits from plants, meat from animals, bread from wheat (a plant). Everything we eat was alive.",
                "Pets are living things with needs: food, water, shelter. Understanding 'alive' means understanding responsibility for living creatures.",
                "Wood, cotton, leather, and paper all come from living things. Many of our materials started as organisms.",
                "Gardens are places where we help living things grow: understanding what plants need IS understanding characteristics of life.",
            ],
            "common_misconceptions": [
                "Thinking anything that moves is alive — cars, rivers, and fire all move but are not alive. Movement alone is not a characteristic of life.",
                "Confusing 'dead' with 'nonliving' — a dead animal WAS alive (it's a once-living thing). A rock was NEVER alive. These are different categories.",
                "Thinking plants aren't alive because they don't move visibly — plants grow, reproduce, need water and sunlight, and respond to their environment (turning toward light). They are absolutely alive.",
                "Believing all small things are nonliving — bacteria, insects, and seeds are tiny but alive. Size doesn't determine whether something is living.",
            ],
        },
        "assessment_criteria": {
            "mastery_indicators": [
                "Sorts 10 items correctly into living and nonliving with explanations",
                "Lists 4+ characteristics of living things",
                "Handles tricky cases (dead things, fire, clouds) with correct reasoning",
            ],
            "proficiency_indicators": [
                "Sorts most items correctly but struggles with tricky cases",
                "Lists 2-3 characteristics of living things",
            ],
            "developing_indicators": [
                "Uses only movement as the criterion for living",
                "Cannot consistently distinguish living from nonliving",
            ],
            "assessment_methods": ["object sorting", "characteristics listing", "tricky case reasoning"],
            "sample_assessment_prompts": [
                "Sort these 10 items into living and nonliving. Explain your choices.",
                "Name 4 things that make something alive.",
                "Is a dead flower living or nonliving? Explain your answer.",
            ],
        },
        "practice_items": [
            {
                "type": "problem",
                "difficulty": 1,
                "prompt": "Which of these is a living thing?",
                "expected_type": "multiple_choice",
                "options": ["A rock", "A tree", "A pencil", "A glass of water"],
                "correct_answer": "A tree",
                "hints": ["Living things grow, need food and water, and reproduce. Which one does all of these?"],
                "explanation": "A tree is a living thing: it grows, needs water and sunlight, reproduces (makes seeds), and responds to its environment (grows toward light). Rocks, pencils, and water are nonliving.",
            },
            {
                "type": "problem",
                "difficulty": 1,
                "prompt": "Name 3 characteristics of living things.",
                "expected_type": "text",
                "hints": ["Think about what YOUR body does: grow, eat, respond to things..."],
                "explanation": "Living things: (1) grow and develop, (2) reproduce (make more of themselves), (3) need food and water (energy), (4) respond to their environment. Any 3 of these is correct.",
            },
            {
                "type": "problem",
                "difficulty": 2,
                "prompt": "True or false: Fire is alive because it grows and moves.",
                "expected_type": "true_false",
                "correct_answer": "false",
                "hints": ["Does fire reproduce? Does it eat food? Does it respond to its environment the way a living thing does?"],
                "explanation": "False. Fire grows and moves, but it does NOT reproduce, does not need food in the biological sense, and is not made of cells. It only meets 1-2 characteristics of life, not all of them. It is a chemical reaction, not a living thing.",
            },
            {
                "type": "problem",
                "difficulty": 2,
                "prompt": "Go on a scavenger hunt in your home. Find and list 3 living things and 3 nonliving things. Explain how you know which is which.",
                "expected_type": "text",
                "hints": ["Living: people, pets, houseplants. Nonliving: furniture, toys, dishes. What makes each category different?"],
                "explanation": "Living things in a home: people, pets (dog, cat, fish), houseplants. Nonliving: tables, chairs, books, cups. Living things grow, need food/water, and respond to the environment. Nonliving things do none of these.",
            },
            {
                "type": "problem",
                "difficulty": 3,
                "prompt": "A seed is sitting on a shelf. It is not growing or doing anything. Is it alive? Explain your reasoning using the characteristics of life.",
                "expected_type": "text",
                "hints": ["A seed looks inactive. But what happens when you plant it and add water? Does it have the POTENTIAL for life characteristics?"],
                "explanation": "Yes, a seed IS alive — it is a dormant living thing. It contains a tiny plant embryo that will grow, reproduce, and respond to its environment once it has water and warmth. It has the potential for all characteristics of life, even though it appears inactive. This is a great tricky case!",
            },
        ],
        "assessment_items": [
            {
                "prompt": "Sort these 10 items into living and nonliving. Explain one tricky choice.",
                "type": "open_response",
                "target_concept": "living_nonliving",
                "rubric": "Mastery: all correct with reasoning for tricky cases. Proficient: most correct. Developing: uses only movement as criterion.",
            },
            {
                "prompt": "List the characteristics of living things.",
                "type": "open_response",
                "target_concept": "characteristics_of_life",
                "rubric": "Mastery: 4+ characteristics with examples. Proficient: 2-3. Developing: 0-1.",
            },
        ],
        "resource_guidance": {
            "required": ["collection of natural objects for sorting", "pictures of living and nonliving things"],
            "recommended": ["magnifying glass for close observation", "poster board for living/nonliving display"],
            "philosophy_specific": {
                "classical": "Classification as the first great act of scientific thinking. Memorize the characteristics of life. Systematic sorting with proper vocabulary.",
                "charlotte_mason": "Nature walks to observe living and nonliving things in their natural setting. The child discovers the difference through direct observation before formal definitions.",
                "montessori": "Nomenclature cards: living and nonliving things with photographs. Sorting trays for physical classification. Real specimens (plants, shells, rocks) for hands-on exploration.",
            },
        },
        "time_estimates": {"first_exposure": 20, "practice_session": 15, "assessment": 10},
        "accommodations": {
            "dyslexia": "Sorting physical objects requires no reading. Oral explanations of reasoning. Draw living vs nonliving instead of writing. Labeled picture cards for visual support.",
            "adhd": "Nature walk scavenger hunt provides movement. Sorting real objects is hands-on. Tricky case debates are interactive. 10-15 minute focused sessions.",
            "gifted": "Introduce the concept of cells as the building blocks of life. Discuss viruses (are they alive? Scientists disagree!). Begin classifying living things into kingdoms: plants, animals, fungi.",
            "visual_learner": "Sorting mats with clear labels. Photographs of living and nonliving things. Color-coded categories.",
            "kinesthetic_learner": "Handle real objects. Nature walk collecting. Physical sorting into piles or trays.",
            "auditory_learner": "Discuss each item: 'Is this alive? How do you know?' Verbal reasoning is the primary assessment mode.",
        },
        "connections": {
            "reading": "Living/nonliving vocabulary builds reading comprehension in science texts: organism, reproduce, respond, environment",
            "math": "Sorting and classifying objects is a mathematical skill: grouping by characteristics, counting group sizes",
            "history": "Ancient civilizations understood living vs nonliving: they farmed (living plants), built with stone (nonliving), and kept animals (living)",
        },
    },
    "sf-03": {
        "enriched": True,
        "learning_objectives": [
            "Draw and label all stages of a plant life cycle: seed, sprout, seedling, mature plant, flower, fruit, seed again",
            "Grow a plant from a seed and record observations weekly in a science notebook",
            "Explain what plants need to survive: sunlight, water, soil (nutrients), and air",
            "Describe seed dispersal methods: wind, water, animals, and explosion",
        ],
        "teaching_guidance": {
            "introduction": "The plant life cycle is one of the most beautiful and accessible science topics because the child can watch it happen in real time. Plant a bean seed in a clear cup against the glass, and within days the child will see the root push down, the stem push up, and the first leaves unfurl. Over weeks, the plant grows, flowers, and produces seeds — completing the cycle. This hands-on experience makes abstract concepts (germination, photosynthesis, reproduction) concrete and unforgettable.",
            "scaffolding_sequence": [
                "Examine seeds: open a bean, an apple seed, a sunflower seed. Inside each one is a tiny baby plant (embryo) waiting to grow.",
                "Plant a bean seed in a clear plastic cup against the glass so the child can watch roots and stem develop day by day",
                "Observe and draw germination: the seed splits open, the root grows down, the stem grows up. Record in science notebook.",
                "Discuss what plants need: design a simple experiment — one plant with sunlight, one without. One with water, one without. Observe results.",
                "Study plant parts and their jobs: roots (absorb water), stem (transport), leaves (make food from sunlight), flower (reproduction), fruit (protects seeds)",
                "Watch the plant flower (if using fast-growing varieties like beans or sunflowers) and observe the transition from flower to fruit/seed",
                "Discuss seed dispersal: how do seeds travel? Wind (dandelion), water (coconut), animals (burrs), explosion (touch-me-not)",
                "Complete the cycle diagram: draw the full life cycle as a circle — seed to plant to flower to fruit to seed again",
            ],
            "socratic_questions": [
                "We planted this seed a week ago. What has changed? What do you think will happen next?",
                "One plant is in the sunlight and one is in a dark closet. Which one do you predict will grow better? Why?",
                "A dandelion puff blows in the wind. Why does the dandelion WANT its seeds to fly away?",
                "The seed has a tiny plant inside it. What does it need from the outside world to start growing?",
            ],
            "practice_activities": [
                "Bean in a bag: place a damp paper towel and a bean seed in a zip-lock bag taped to a window. Watch germination happen without soil!",
                "Sunlight experiment: grow two identical plants — one in sun, one in shade. Measure and compare growth weekly. Record in science notebook.",
                "Seed hunt: go outside and find as many different seeds as possible (acorns, dandelion fluff, burrs, pine cones, berries). Sort by dispersal method.",
                "Life cycle diagram: draw the plant life cycle as a circle with arrows. Label each stage: seed → sprout → seedling → plant → flower → fruit → seed.",
            ],
            "real_world_connections": [
                "Every fruit and vegetable in the kitchen came from a plant life cycle: the apple is the fruit, the seeds inside are the next generation",
                "Farmers understand the plant life cycle deeply: planting seeds, providing water and nutrients, harvesting crops",
                "Gardens are plant life cycles in action: the family garden is a living science experiment",
                "Trees in the neighborhood follow the same cycle: flowers in spring, fruit in summer, seeds in fall, dormancy in winter",
            ],
            "common_misconceptions": [
                "Thinking plants get their food from the soil — plants make their own food from sunlight (photosynthesis). Soil provides water and minerals, not food.",
                "Believing seeds need sunlight to germinate — most seeds germinate in the dark, underground. They need WATER and WARMTH, not light, to sprout. Sunlight is needed later for growth.",
                "Thinking all flowers are just decorative — flowers are the reproductive organs of plants. They produce seeds for the next generation.",
                "Assuming fruits are only things we eat as 'fruit' — in science, a fruit is any structure that contains seeds: tomatoes, peppers, acorns, and dandelion fluff are all fruits.",
            ],
        },
        "assessment_criteria": {
            "mastery_indicators": [
                "Draws and labels all stages of the plant life cycle correctly",
                "Maintains a plant growth journal with weekly observations for 4+ weeks",
                "Explains plant needs (sun, water, soil, air) with evidence from experiments",
            ],
            "proficiency_indicators": [
                "Names most life cycle stages but may omit one",
                "Records observations but not consistently weekly",
            ],
            "developing_indicators": [
                "Knows plants grow from seeds but cannot describe the full cycle",
                "Cannot explain plant needs with specificity",
            ],
            "assessment_methods": ["life cycle diagram", "plant journal review", "plant needs explanation"],
            "sample_assessment_prompts": [
                "Draw and label the life cycle of a plant, from seed back to seed.",
                "Show me your plant journal. What changed each week?",
                "What does a plant need to grow? How do you know?",
            ],
        },
        "practice_items": [
            {
                "type": "problem",
                "difficulty": 1,
                "prompt": "What do plants need to grow?",
                "expected_type": "multiple_choice",
                "options": [
                    "Only water",
                    "Sunlight, water, soil, and air",
                    "Just soil and darkness",
                    "Only sunlight",
                ],
                "correct_answer": "Sunlight, water, soil, and air",
                "hints": ["Plants need several things, not just one. Think about what you give your plant every day, plus what nature provides."],
                "explanation": "Plants need sunlight (for making food through photosynthesis), water (for transport and growth), soil (for minerals and support), and air (for carbon dioxide). Remove any one and the plant will struggle or die.",
            },
            {
                "type": "problem",
                "difficulty": 1,
                "prompt": "True or false: A flower is just for decoration — it doesn't serve an important purpose for the plant.",
                "expected_type": "true_false",
                "correct_answer": "false",
                "hints": ["What happens AFTER a flower blooms? What grows in its place?"],
                "explanation": "False. Flowers are the reproductive part of the plant. They produce seeds that become the next generation of plants. Without flowers, most flowering plants could not reproduce.",
            },
            {
                "type": "problem",
                "difficulty": 2,
                "prompt": "Plant a bean seed in a clear cup against the glass. Check it every day for a week. Draw what you see each day in your science notebook.",
                "expected_type": "text",
                "hints": ["Day 1: the seed is dry. Day 2-3: it swells with water. Day 3-5: a root appears. Day 5-7: a stem pushes up. Draw what YOU see — everyone's timing is slightly different."],
                "explanation": "Over about a week, you should observe: the seed absorbs water and swells, the seed coat splits, a root emerges and grows downward, then a stem pushes upward. Drawing each day creates a visual record of germination — real science in action.",
            },
            {
                "type": "problem",
                "difficulty": 2,
                "prompt": "Name two ways seeds travel to new places.",
                "expected_type": "text",
                "hints": ["Think about dandelion fluff, burrs that stick to your socks, and berries that birds eat."],
                "explanation": "Seeds travel by: wind (dandelion, maple helicopter), animals (burrs stick to fur, birds eat berries and spread seeds), water (coconuts float), and explosion (some pods burst open and shoot seeds). This is called seed dispersal, and it helps plants spread to new areas.",
            },
            {
                "type": "problem",
                "difficulty": 3,
                "prompt": "Design an experiment to find out whether plants need sunlight to grow. What would you do? What would you compare?",
                "expected_type": "text",
                "hints": ["You need TWO plants that are the same in every way EXCEPT for sunlight. One gets sun, one doesn't. Everything else stays the same."],
                "explanation": "A good experiment: plant two identical seeds in identical cups with the same soil and water. Place one in sunlight and one in a dark closet. Give both the same amount of water. Observe and measure them each week. The difference in growth is caused by the sunlight (the only thing that's different). This is a controlled experiment — a fundamental concept in science.",
            },
        ],
        "assessment_items": [
            {
                "prompt": "Draw and label the complete plant life cycle.",
                "type": "open_response",
                "target_concept": "plant_life_cycle",
                "rubric": "Mastery: all stages drawn in circle with labels and arrows. Proficient: most stages. Developing: only seed and plant.",
            },
            {
                "prompt": "Show me your plant journal. Describe what happened over the weeks.",
                "type": "open_response",
                "target_concept": "plant_observation",
                "rubric": "Mastery: weekly entries with drawings and measurements showing growth. Proficient: some entries. Developing: sparse records.",
            },
        ],
        "resource_guidance": {
            "required": ["bean seeds", "clear plastic cups", "soil", "water", "science notebook"],
            "recommended": ["magnifying glass for seed examination", "ruler for measuring growth", "fast-growing flower seeds (sunflower, marigold)"],
            "philosophy_specific": {
                "classical": "Plant life cycle memorized as a sequence. Vocabulary drilled: germination, photosynthesis, dispersal. Structured observation logs.",
                "charlotte_mason": "The child plants seeds, tends them daily, draws what they see in their nature notebook. Direct observation is primary — textbooks are secondary. The garden IS the classroom.",
                "montessori": "Botany nomenclature cards: parts of a plant with three-part matching. Seed sprouting trays. Practical life: watering and caring for classroom/home plants.",
            },
        },
        "time_estimates": {"first_exposure": 20, "practice_session": 15, "assessment": 10},
        "accommodations": {
            "dyslexia": "Drawing the life cycle is the primary activity — minimal writing required. Label with single words dictated to parent if needed. The hands-on planting and observing requires no reading.",
            "adhd": "Planting seeds is hands-on and exciting. Daily 2-minute check-ins on the plant maintain engagement without long sessions. Drawing observations keeps hands busy. Outdoor seed hunts provide movement.",
            "gifted": "Introduce photosynthesis at a basic level (plants make food from sunlight + water + air). Compare life cycles of different plants. Design additional experiments (does music affect growth? does the color of light matter?).",
            "visual_learner": "Drawings of each stage are the core activity. Time-lapse videos of plant growth. Colorful life cycle posters.",
            "kinesthetic_learner": "Planting, watering, and tending plants. Seed collecting outdoors. Building a mini-greenhouse from a plastic bottle.",
            "auditory_learner": "Narrate observations aloud before drawing. Discuss predictions: 'What do you think will happen next?' Listen to audiobooks about plants.",
        },
        "connections": {
            "reading": "Plant vocabulary builds reading comprehension: germination, photosynthesis, dispersal, seedling, dormant",
            "math": "Measuring plant growth in centimeters each week. Graphing growth over time. Counting seeds in a fruit.",
            "history": "The Agricultural Revolution: humans learned to plant seeds intentionally, which changed everything. Farming IS the plant life cycle, controlled.",
        },
    },
}
