"""Scope and sequence framework for METHEAN."""

SCOPE_SEQUENCES = {}


def get_scope_sequence(subject_id: str, level: str) -> list[dict]:
    return SCOPE_SEQUENCES.get(subject_id, {}).get(level, [])


def get_next_topics(subject_id: str, level: str, completed_refs: list[str], count: int = 5) -> list[dict]:
    scope = get_scope_sequence(subject_id, level)
    completed = set(completed_refs)
    result = []
    for topic in scope:
        if topic["ref"] in completed:
            continue
        if all(p in completed for p in topic.get("prerequisites", [])):
            result.append(topic)
            if len(result) >= count:
                break
    return result


def get_all_subject_ids() -> list[str]:
    return list(SCOPE_SEQUENCES.keys())


SCOPE_SEQUENCES["mathematics"] = {
    "foundational": [
        {
            "ref": "math_f_01",
            "title": "Counting to 20",
            "description": "Count objects to 20 with one-to-one correspondence. Recognize and write numerals 0 through 20, counting forward and backward from any number within 20.",
            "prerequisites": [],
            "estimated_weeks": 2,
            "key_concepts": ["one-to-one correspondence", "numeral recognition", "counting sequence", "cardinality"],
            "assessment_indicators": ["Counts 20 objects accurately", "Writes numerals 0-20", "Counts backward from 20"],
            "classical_alignment": "Grammar stage: memorization of number sequence",
            "charlotte_mason_alignment": "Living math: counting real objects in nature and daily life",
            "standard_alignment": "K.CC.1-5",
        },
        {
            "ref": "math_f_02",
            "title": "Number Recognition 0-100",
            "description": "Identify, read, and write numerals from 0 to 100. Understand the difference between a number and a numeral and begin to see patterns in the number chart.",
            "prerequisites": ["math_f_01"],
            "estimated_weeks": 2,
            "key_concepts": ["numeral identification", "number names", "number-quantity connection", "hundreds chart patterns"],
            "assessment_indicators": ["Reads any numeral 0-100", "Points to correct numeral when given orally", "Writes numerals to 50 from memory"],
            "classical_alignment": "Grammar stage: memorization of number names and symbols",
            "charlotte_mason_alignment": "Short focused lessons with real-world number identification",
            "standard_alignment": "K.CC.3, 1.NBT.1",
        },
        {
            "ref": "math_f_03",
            "title": "One-to-One Correspondence",
            "description": "Match one object to one number when counting and one object to one other object when comparing sets. Build the foundational understanding that each item is counted exactly once.",
            "prerequisites": ["math_f_01"],
            "estimated_weeks": 1,
            "key_concepts": ["matching", "pairing", "equal sets", "counting accuracy"],
            "assessment_indicators": ["Touches each object exactly once while counting", "Matches objects between two sets", "Identifies when two groups have the same number"],
            "classical_alignment": "Grammar stage: concrete manipulation before abstract number work",
            "charlotte_mason_alignment": "Hands-on with natural objects: stones, shells, seeds",
            "standard_alignment": "K.CC.4-5",
        },
        {
            "ref": "math_f_04",
            "title": "Counting to 100",
            "description": "Extend counting skills to 100 by ones and by tens. Recognize patterns in the counting sequence and understand that after each group of ten comes the next decade.",
            "prerequisites": ["math_f_01", "math_f_02"],
            "estimated_weeks": 2,
            "key_concepts": ["decade numbers", "counting by tens", "number patterns", "hundred"],
            "assessment_indicators": ["Counts to 100 by ones", "Counts to 100 by tens", "Identifies the number that comes after any number to 99"],
            "classical_alignment": "Grammar stage: chanting counting sequences",
            "charlotte_mason_alignment": "Rhythmic counting through songs and movement",
            "standard_alignment": "K.CC.1, 1.NBT.1",
        },
        {
            "ref": "math_f_05",
            "title": "Addition Facts to 10",
            "description": "Learn all addition combinations that sum to 10 or less using manipulatives, number lines, and mental strategies. Build toward automatic recall of basic addition facts.",
            "prerequisites": ["math_f_01", "math_f_02", "math_f_03"],
            "estimated_weeks": 3,
            "key_concepts": ["combining groups", "addition symbol", "sum", "commutative property", "number bonds"],
            "assessment_indicators": ["Recalls addition facts to 10 within 3 seconds", "Demonstrates addition with manipulatives", "Writes addition number sentences"],
            "classical_alignment": "Grammar stage: fact memorization through chanting and drill",
            "charlotte_mason_alignment": "Concrete-to-abstract: manipulatives first, then mental math",
            "standard_alignment": "K.OA.1-5, 1.OA.6",
        },
        {
            "ref": "math_f_06",
            "title": "Subtraction Facts to 10",
            "description": "Learn all subtraction combinations within 10. Understand subtraction as taking away, as finding the difference, and as the inverse of addition.",
            "prerequisites": ["math_f_05"],
            "estimated_weeks": 3,
            "key_concepts": ["taking away", "difference", "subtraction symbol", "inverse of addition", "missing addend"],
            "assessment_indicators": ["Recalls subtraction facts within 10", "Demonstrates subtraction with manipulatives", "Connects subtraction to related addition facts"],
            "classical_alignment": "Grammar stage: paired drill of addition and subtraction families",
            "charlotte_mason_alignment": "Story problems using real scenarios before abstract notation",
            "standard_alignment": "K.OA.1-5, 1.OA.4",
        },
        {
            "ref": "math_f_07",
            "title": "Addition Facts to 20",
            "description": "Extend addition fluency to sums up to 20. Use strategies such as making ten, doubles, and near doubles to compute efficiently.",
            "prerequisites": ["math_f_05", "math_f_09"],
            "estimated_weeks": 3,
            "key_concepts": ["making ten", "doubles", "near doubles", "counting on", "bridging through ten"],
            "assessment_indicators": ["Recalls addition facts to 20 within 5 seconds", "Uses making-ten strategy", "Solves missing addend problems to 20"],
            "classical_alignment": "Grammar stage: systematic drill with strategy introduction",
            "charlotte_mason_alignment": "Short daily practice with manipulatives transitioning to mental math",
            "standard_alignment": "1.OA.6, 2.OA.2",
        },
        {
            "ref": "math_f_08",
            "title": "Subtraction Facts to 20",
            "description": "Extend subtraction fluency to differences within 20. Relate each subtraction fact to its addition counterpart and use strategies like counting back and thinking addition.",
            "prerequisites": ["math_f_06", "math_f_09"],
            "estimated_weeks": 3,
            "key_concepts": ["counting back", "think addition", "fact families", "related facts"],
            "assessment_indicators": ["Recalls subtraction facts within 20", "Uses think-addition strategy", "Writes complete fact families"],
            "classical_alignment": "Grammar stage: fact family memorization",
            "charlotte_mason_alignment": "Oral narration of subtraction stories before written work",
            "standard_alignment": "1.OA.4, 1.OA.6, 2.OA.2",
        },
        {
            "ref": "math_f_09",
            "title": "Place Value Tens and Ones",
            "description": "Understand that two-digit numbers are composed of tens and ones. Use base-ten blocks and place value charts to decompose numbers from 10 to 99.",
            "prerequisites": ["math_f_04"],
            "estimated_weeks": 2,
            "key_concepts": ["tens", "ones", "decomposition", "place value chart", "expanded form"],
            "assessment_indicators": ["Represents any two-digit number with base-ten blocks", "Identifies the tens and ones digit", "Writes numbers in expanded form"],
            "classical_alignment": "Grammar stage: systematic understanding of number structure",
            "charlotte_mason_alignment": "Concrete bundles of sticks or beads grouped by tens",
            "standard_alignment": "1.NBT.2, 1.NBT.3",
        },
        {
            "ref": "math_f_10",
            "title": "Skip Counting by 2s, 5s, and 10s",
            "description": "Count forward by twos, fives, and tens starting from zero. Recognize skip counting patterns on the hundreds chart and understand their connection to multiplication.",
            "prerequisites": ["math_f_04"],
            "estimated_weeks": 2,
            "key_concepts": ["skip counting", "patterns", "multiples", "rhythmic counting"],
            "assessment_indicators": ["Skip counts by 2s to 30", "Skip counts by 5s to 100", "Skip counts by 10s to 100"],
            "classical_alignment": "Grammar stage: rhythmic chanting of skip count sequences",
            "charlotte_mason_alignment": "Movement and music: clapping, marching while skip counting",
            "standard_alignment": "2.NBT.2",
        },
        {
            "ref": "math_f_11",
            "title": "Comparing Numbers Greater Less Equal",
            "description": "Compare two numbers using greater than, less than, and equal to. Use symbols >, <, and = and apply comparison to real-world quantities.",
            "prerequisites": ["math_f_04"],
            "estimated_weeks": 2,
            "key_concepts": ["greater than", "less than", "equal to", "comparison symbols", "ordering"],
            "assessment_indicators": ["Uses >, <, = correctly between two numbers", "Orders a set of numbers from least to greatest", "Compares quantities using objects or drawings"],
            "classical_alignment": "Grammar stage: learning symbols and their precise meaning",
            "charlotte_mason_alignment": "Comparing real quantities: which basket has more apples?",
            "standard_alignment": "K.CC.6-7, 1.NBT.3",
        },
        {
            "ref": "math_f_12",
            "title": "Ordinal Numbers",
            "description": "Use ordinal numbers first through twentieth to describe position in a sequence. Apply ordinal language to everyday situations like lines, races, and calendar dates.",
            "prerequisites": ["math_f_04"],
            "estimated_weeks": 1,
            "key_concepts": ["ordinal position", "first through twentieth", "position vs quantity", "sequence"],
            "assessment_indicators": ["Names ordinal positions first through tenth", "Identifies an object's ordinal position in a line", "Uses ordinal numbers in context"],
            "classical_alignment": "Grammar stage: vocabulary of ordinal terms",
            "charlotte_mason_alignment": "Natural context: who finished first? what is the third book?",
            "standard_alignment": "K.CC.4d (supplementary)",
        },
        {
            "ref": "math_f_13",
            "title": "Measurement Length",
            "description": "Measure the length of objects using nonstandard units and then standard units like inches and centimeters. Compare lengths of two objects directly and indirectly.",
            "prerequisites": ["math_f_11"],
            "estimated_weeks": 2,
            "key_concepts": ["length", "nonstandard units", "inches", "centimeters", "comparison"],
            "assessment_indicators": ["Measures objects using nonstandard units", "Measures to the nearest inch with a ruler", "Compares two objects by length"],
            "classical_alignment": "Grammar stage: vocabulary of measurement and units",
            "charlotte_mason_alignment": "Nature study: measuring plants, sticks, leaves",
            "standard_alignment": "1.MD.1-2, 2.MD.1-3",
        },
        {
            "ref": "math_f_14",
            "title": "Measurement Weight",
            "description": "Explore the concept of weight by comparing objects as heavier or lighter. Use a balance scale and introduce standard units like pounds and kilograms.",
            "prerequisites": ["math_f_11"],
            "estimated_weeks": 1,
            "key_concepts": ["heavy", "light", "balance scale", "pounds", "kilograms"],
            "assessment_indicators": ["Predicts which object is heavier", "Uses a balance scale to compare two objects", "Identifies appropriate unit for measuring weight"],
            "classical_alignment": "Grammar stage: scientific measurement vocabulary",
            "charlotte_mason_alignment": "Hands-on: weighing natural objects and kitchen ingredients",
            "standard_alignment": "K.MD.1-2",
        },
        {
            "ref": "math_f_15",
            "title": "Time Hours and Half Hours",
            "description": "Read and write time to the hour and half hour on analog and digital clocks. Relate clock times to daily routines and understand the meaning of the hour and minute hands.",
            "prerequisites": ["math_f_02"],
            "estimated_weeks": 2,
            "key_concepts": ["hour hand", "minute hand", "o'clock", "half past", "analog vs digital"],
            "assessment_indicators": ["Reads time to the hour on analog clock", "Reads time to the half hour", "Relates time to daily schedule events"],
            "classical_alignment": "Grammar stage: learning to read instruments systematically",
            "charlotte_mason_alignment": "Habit training: connecting clock times to daily rhythms",
            "standard_alignment": "1.MD.3",
        },
        {
            "ref": "math_f_16",
            "title": "Coins Identification",
            "description": "Identify penny, nickel, dime, and quarter by appearance and name. Learn the value of each coin and begin to count small collections of same-denomination coins.",
            "prerequisites": ["math_f_02"],
            "estimated_weeks": 2,
            "key_concepts": ["penny", "nickel", "dime", "quarter", "coin value", "cents"],
            "assessment_indicators": ["Names all four coins on sight", "States the value of each coin", "Counts a group of same-type coins"],
            "classical_alignment": "Grammar stage: identification and value memorization",
            "charlotte_mason_alignment": "Real-world math: playing store with actual coins",
            "standard_alignment": "2.MD.8",
        },
        {
            "ref": "math_f_17",
            "title": "2D Shapes",
            "description": "Identify and describe circles, squares, rectangles, triangles, hexagons, and other common two-dimensional shapes. Describe shapes by number of sides, corners, and overall form.",
            "prerequisites": ["math_f_01"],
            "estimated_weeks": 2,
            "key_concepts": ["sides", "corners", "vertices", "circle", "square", "rectangle", "triangle"],
            "assessment_indicators": ["Names six common 2D shapes", "Describes shapes by attributes", "Identifies shapes in the environment"],
            "classical_alignment": "Grammar stage: precise geometric vocabulary",
            "charlotte_mason_alignment": "Shape hunts outdoors: finding geometry in nature and architecture",
            "standard_alignment": "K.G.1-6",
        },
        {
            "ref": "math_f_18",
            "title": "Patterns and Sequences",
            "description": "Identify, extend, and create repeating patterns using colors, shapes, numbers, and sounds. Recognize growing patterns and begin to describe the rule that generates a pattern.",
            "prerequisites": ["math_f_01"],
            "estimated_weeks": 2,
            "key_concepts": ["repeating pattern", "AB pattern", "ABC pattern", "growing pattern", "pattern rule"],
            "assessment_indicators": ["Extends an AB or ABC pattern", "Creates an original repeating pattern", "Describes the rule of a given pattern"],
            "classical_alignment": "Grammar stage: recognizing order and structure",
            "charlotte_mason_alignment": "Patterns in nature: flower petals, leaf arrangements, seasons",
            "standard_alignment": "K.OA.1 (supplementary, patterning)",
        },
        {
            "ref": "math_f_19",
            "title": "Number Lines",
            "description": "Use number lines to represent numbers, count forward and backward, and visualize addition and subtraction. Understand the number line as a tool for comparing and ordering numbers.",
            "prerequisites": ["math_f_04", "math_f_11"],
            "estimated_weeks": 2,
            "key_concepts": ["number line", "intervals", "jumps forward", "jumps backward", "distance"],
            "assessment_indicators": ["Locates numbers on a number line to 100", "Uses jumps to model addition on a number line", "Uses jumps to model subtraction on a number line"],
            "classical_alignment": "Grammar stage: visual representation of abstract number concepts",
            "charlotte_mason_alignment": "Drawing number lines in nature journals alongside counting exercises",
            "standard_alignment": "1.OA.5, 2.MD.6",
        },
        {
            "ref": "math_f_20",
            "title": "Even and Odd Numbers",
            "description": "Determine whether a number is even or odd by pairing objects or examining the ones digit. Recognize that even numbers can be split into two equal groups.",
            "prerequisites": ["math_f_10"],
            "estimated_weeks": 1,
            "key_concepts": ["even", "odd", "pairs", "equal groups", "ones digit rule"],
            "assessment_indicators": ["Identifies numbers to 20 as even or odd", "Demonstrates even/odd with objects", "Applies the ones digit rule for larger numbers"],
            "classical_alignment": "Grammar stage: classification and rule memorization",
            "charlotte_mason_alignment": "Pairing real objects to discover the concept before stating the rule",
            "standard_alignment": "2.OA.3",
        },
        {
            "ref": "math_f_21",
            "title": "Fractions Visual Half and Quarter",
            "description": "Understand halves and quarters as equal parts of a whole using real objects and drawings. Divide shapes and sets into two or four equal parts and name each part.",
            "prerequisites": ["math_f_11"],
            "estimated_weeks": 2,
            "key_concepts": ["half", "quarter", "equal parts", "whole", "fair sharing"],
            "assessment_indicators": ["Divides a shape into two equal halves", "Divides a shape into four equal quarters", "Identifies whether parts are equal or unequal"],
            "classical_alignment": "Grammar stage: vocabulary of fractional parts",
            "charlotte_mason_alignment": "Real-life fractions: cutting food, sharing equally among children",
            "standard_alignment": "1.G.3, 2.G.3",
        },
        {
            "ref": "math_f_22",
            "title": "Tally Charts and Data",
            "description": "Collect data by asking questions and recording responses using tally marks. Organize data into simple charts and answer questions about the data collected.",
            "prerequisites": ["math_f_01"],
            "estimated_weeks": 1,
            "key_concepts": ["tally marks", "data collection", "chart", "most", "least", "how many"],
            "assessment_indicators": ["Records data using tally marks", "Reads a tally chart to answer questions", "Identifies the most and least popular category"],
            "classical_alignment": "Grammar stage: organized data recording and reading",
            "charlotte_mason_alignment": "Nature surveys: tallying bird sightings, flower types, weather observations",
            "standard_alignment": "1.MD.4, 2.MD.10",
        },
        {
            "ref": "math_f_23",
            "title": "Word Problems Single Step Addition",
            "description": "Solve one-step addition word problems by identifying the action, choosing the operation, and writing a number sentence. Use drawings and manipulatives to represent the story.",
            "prerequisites": ["math_f_07"],
            "estimated_weeks": 2,
            "key_concepts": ["joining", "result unknown", "change unknown", "part-part-whole", "number sentence"],
            "assessment_indicators": ["Identifies addition as the correct operation", "Writes a number sentence for a word problem", "Solves result-unknown addition problems to 20"],
            "classical_alignment": "Grammar stage: translating language into mathematical notation",
            "charlotte_mason_alignment": "Story-based math: narrating problems from daily life before solving",
            "standard_alignment": "1.OA.1-2",
        },
        {
            "ref": "math_f_24",
            "title": "Word Problems Single Step Subtraction",
            "description": "Solve one-step subtraction word problems including take-away, comparison, and missing-part situations. Represent each problem with objects, drawings, or equations.",
            "prerequisites": ["math_f_08"],
            "estimated_weeks": 2,
            "key_concepts": ["take away", "comparison", "how many more", "how many fewer", "difference"],
            "assessment_indicators": ["Identifies subtraction as the correct operation", "Writes a subtraction equation for a word problem", "Solves comparison word problems"],
            "classical_alignment": "Grammar stage: structured problem types for systematic practice",
            "charlotte_mason_alignment": "Real-world narration: how many more do we need? how many are left?",
            "standard_alignment": "1.OA.1-2",
        },
        {
            "ref": "math_f_25",
            "title": "Addition of Three Numbers",
            "description": "Add three single-digit numbers by grouping, using the associative property, and looking for combinations that make ten. Apply strategies to make three-addend problems efficient.",
            "prerequisites": ["math_f_07"],
            "estimated_weeks": 2,
            "key_concepts": ["three addends", "grouping", "associative property", "making ten with three numbers"],
            "assessment_indicators": ["Adds three one-digit numbers", "Groups strategically to make ten first", "Writes and solves three-addend equations"],
            "classical_alignment": "Grammar stage: extending addition drill to three numbers",
            "charlotte_mason_alignment": "Practical math: adding items in a shopping list or recipe",
            "standard_alignment": "1.OA.2",
        },
        {
            "ref": "math_f_26",
            "title": "Mental Math Strategies",
            "description": "Develop and practice mental computation strategies including counting on, making ten, using doubles, and compensation. Build speed and flexibility in mental arithmetic.",
            "prerequisites": ["math_f_07", "math_f_08"],
            "estimated_weeks": 2,
            "key_concepts": ["counting on", "making ten", "doubles plus one", "compensation", "mental computation"],
            "assessment_indicators": ["Uses at least two mental math strategies", "Solves addition and subtraction within 20 mentally", "Explains which strategy was used"],
            "classical_alignment": "Grammar stage transitioning to logic: strategic thinking about computation",
            "charlotte_mason_alignment": "Short daily oral math sessions emphasizing speed and confidence",
            "standard_alignment": "1.OA.6, 2.OA.2",
        },
        {
            "ref": "math_f_27",
            "title": "Estimation Introduction",
            "description": "Develop number sense by estimating quantities and measurements before counting or measuring precisely. Understand that estimation is a useful skill for checking reasonableness.",
            "prerequisites": ["math_f_11"],
            "estimated_weeks": 1,
            "key_concepts": ["estimate", "reasonable", "about", "close to", "benchmark numbers"],
            "assessment_indicators": ["Estimates a quantity within a reasonable range", "Explains whether an answer is reasonable", "Uses benchmarks of 10 and 20 to estimate"],
            "classical_alignment": "Grammar stage: developing intuition about quantities",
            "charlotte_mason_alignment": "Estimation jars and guessing games with natural objects",
            "standard_alignment": "2.OA.1 (supplementary)",
        },
        {
            "ref": "math_f_28",
            "title": "Number Bonds to 20",
            "description": "Master all the ways to decompose numbers up to 20 into two parts. Understand number bonds as the foundation for flexible addition and subtraction strategies.",
            "prerequisites": ["math_f_07"],
            "estimated_weeks": 2,
            "key_concepts": ["decomposition", "number bonds", "part-part-whole", "fact families", "flexibility"],
            "assessment_indicators": ["States all bonds for any number to 10 from memory", "Identifies bonds for numbers 11-20 using making-ten", "Uses number bonds to solve addition and subtraction"],
            "classical_alignment": "Grammar stage: systematic memorization of number relationships",
            "charlotte_mason_alignment": "Hands-on bond exploration with two-color counters",
            "standard_alignment": "K.OA.3-4, 1.OA.6",
        },
        {
            "ref": "math_f_29",
            "title": "Sorting and Classifying",
            "description": "Sort objects by attributes such as color, shape, size, and number. Classify objects into categories and count the number in each group, connecting sorting to early data analysis.",
            "prerequisites": ["math_f_11", "math_f_17"],
            "estimated_weeks": 1,
            "key_concepts": ["attributes", "sorting rule", "categories", "classification", "Venn diagram intro"],
            "assessment_indicators": ["Sorts objects by a single attribute", "Sorts objects by two attributes", "Counts and compares category sizes"],
            "classical_alignment": "Grammar stage: logical classification and category thinking",
            "charlotte_mason_alignment": "Nature sorting: classifying leaves, rocks, seeds by observable properties",
            "standard_alignment": "K.MD.3, 1.MD.4",
        },
        {
            "ref": "math_f_30",
            "title": "Foundational Math Review and Assessment",
            "description": "Comprehensive review of all foundational mathematics topics covering number sense, operations, measurement, geometry, and data. Assess readiness for the developing level.",
            "prerequisites": [],
            "estimated_weeks": 2,
            "key_concepts": ["cumulative review", "readiness assessment", "skill consolidation", "gap identification"],
            "assessment_indicators": ["Demonstrates fluency with addition and subtraction to 20", "Explains place value of two-digit numbers", "Applies measurement and geometry vocabulary correctly"],
            "classical_alignment": "Grammar stage: comprehensive review before advancing to new material",
            "charlotte_mason_alignment": "Gentle assessment through narration, demonstration, and conversation",
            "standard_alignment": "K-1 cumulative",
        },
    ],
    "developing": [],
    "intermediate": [],
    "advanced": [],
    "mastery": [],
}
